### ISSUE TITLE
Blank white screen as soon as mavensmate is opened

### ISSUE THREAD

**Issue by ap23164** [joeferraro/MavensMate#1000]
* **MavensMate Desktop Version**: MavensMate v0.0.11-beta.7

* **Editor**: Visual studio code

* **MavensMate Plugin Version**: 0.10.0

* **Platform/Version**: Windows 10 64-bit

* **Proxy Details**: No Proxy

* **Salesforce API Version**: N/A

* **Salesforce Server**: cs53, cs2

Open MavensMate

**Comment by ap23164** [comment]
I dont think, anyone's going to respond on the issue... Its happening for quite a long time now.. As a workaround, I have stopped using MavensMate since, its not at all stable as far as its new and older versions are concerned. Thanks for making me select Eclipse as an option, since, its working perfect!

FYI, I'm not gonna close the ticket.

**Comment by kidtsunami** [comment]
@ap23164 do you have a screenshot of what is occurring.

Also, how are you opening MavensMate, are you opening it from VS Code or directly? Did this occur with a specific project?

**Comment by ap23164** [comment]
Screenshot:
![blank screen](https://user-images.githubusercontent.com/26812429/28907993-a765acec-783e-11e7-9f8d-7adee4d83996.PNG)

I am trying to open the MavensMate directly, and not from VS Code. As soon as I open it, a spinner comes up, and then its vanished, then there comes blank screen as shown in the screenshot above. Its project independent, since, its happening as soon as we open the MM.

**Comment by kidtsunami** [comment]
Ok, I'll try to have a look at it tomorrow. 

Have you checked where the logs are? (I'm not entirely sure, will have to fire up my PC to check).

Thanks for submitting this issue @ap23164, I'll do my best to get to the bottom of it.

**Comment by ap23164** [comment]
I'll share a screenshot with the logs.

But thanks for looking into it

**Comment by ap23164** [comment]
![capture_2](https://user-images.githubusercontent.com/26812429/28908502-a782525e-7841-11e7-8816-eec2abac6544.PNG)

Following is the screenshot of the logs

**Comment by ap23164** [comment]
Any luck on it?

**Comment by kidtsunami** [comment]
@ap23164 Unfortunately no, I was unable to recreate it with multiple versions of the beta on Win10.

The logs look very much like mine, so I'm really unsure of how to help you. I would just encourage you to uninstall and reinstall and see how it goes. I'm very sorry this is occurring.

**Comment by ap23164** [comment]
Hmm... I tried uninstall and reinstall.. Tried installing version 6 as well... Checked with my colleagues, their MM is working fine. It must be something wrong with my PC. But, any pointers regarding what could be the issue behind it will definitely be appreciated. Thanks

**Comment by opensourcejunkie** [comment]
This is happening with me as well, whenever I try to use to a new version. Downgrading to v0.0.11-beta3 works for me; you might give that a shot. Here's the link: https://github.com/joeferraro/MavensMate-Desktop/releases/tag/v0.0.11-beta.3

@kidtsunami, if it helps you reproduce the problem, I'm running Mavensmate on Mac OSX:

<img width="249" alt="screen shot 2017-08-06 at 1 38 30 am" src="https://user-images.githubusercontent.com/4969719/29000887-03386518-7a48-11e7-820d-6748fc53314c.png">

Thanks for your work on this; I'm looking forward to the day when I can upgrade :-)

**Comment by ap23164** [comment]
Hi @opensourcejunkie , Thanks a lot for your help..!! Really appreciate that!

I installed the beta3 version in my PC, and it seems to have the same issue. Not really sure, what causing the issue. Just for your reference.

**Comment by ap23164** [comment]
Just FYI: I tried to change some compatibility and some other settings.. and it worked, but it doesnt work all the time.

**Comment by kidtsunami** [comment]
Mind sharing some more details about what has caused it to intermittently work? We may be able to provide a guide to investigate this issue.

**Comment by ap23164** [comment]
Hmm.. Not too sure, what happened. It seems like, if we troubleshoot compatibility, it works. Not sure though, as I tried today as well, and screen is still blank.  I'm still wondering how it worked that time. Let me do some trial and error, and get back to you.

**Comment by ap23164** [comment]
I have found something.. Not sure, if it will work with you guys, but I tried it and worked.
1. Troubleshoot Compatibility
2. User recommended settings.
3. Click on 'Test The Program'. It will open MM, wont work though.
4. Click on Next and select Save the current settings(not able to recall the exact statement, its the first statement)
5. It will show resolved troubleshoot window. Here, close it.
6. Close all MM windows if open.
7. Force Run the program as administrator

voila! MM opens up

FYI: I'm using MM beta 3 version

**Comment by kidtsunami** [comment]
@ap23164 does force running the program as administrator work without troubleshooting?

**Comment by ap23164** [comment]
Sadly, no.. Only Run as Administrator doesn't work.

**Comment by kidtsunami** [comment]
Unfortunately @ap23164 given Salesforce's launch of [their own extension for VS Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode), Development and Support for MavensMate is [officially over](http://mavensmate.com/).
