### ISSUE TITLE
Auto-Complete Hangs In String Literals

### ISSUE THREAD

**Issue by opensourcejunkie** [joeferraro/MavensMate#1001]
* **MavensMate Desktop Version**: v0.0.11-beta3

* **Editor**: Sublime

* **MavensMate Plugin Version**: v7.0.2

* **Platform/Version**: OSX 10.10.5

* **Proxy Details**: N/A

* **Salesforce API Version**: 36.0

* **Salesforce Server**: na50

Hey, thanks for the beautiful software that is MavensMate. I'm running into an issue with the Sublime plugin where it is attempting to provide autocomplete options when typing string literals, and is hanging in the process. This causes all typing and work to halt until it finishes, about 10 seconds later.

This may be a somewhat uncommon manifestation, due to the unusual way that I am using string literals; others might not see it as much or at all, depending on the cause. For testing purposes, my code classifies log entries by having the log message be the code that generated them. So variables and code exist in the file that also exist in the string literal, and as soon as I get to a '.' it starts to hang. 

For example, when I try to type the following line:
`
log.similar('log.similar(inception)').finest('log.similar(inception).finest(inception1)');
`

Sublime hangs at the following place:
`
log.similar('log.')
`

The issue does not manifest when autocomplete runs outside of a string literal, only in strings. Disabling the MavensMate plugin solves the issue (not elegantly of course :-)). Also, applying the following setting also solves the issue:
`
"mm_autocomplete" : false,
`

The second solution works fine for me, since I don't particularly use autocomplete anyway. But in case it helps to diagnose the issue for others, I figured a ticket would be in order. Thanks again for providing such a great tool at no charge
 :-)

<img width="249" alt="screen shot 2017-08-06 at 1 38 30 am" src="https://user-images.githubusercontent.com/4969719/29001010-4158116a-7a4b-11e7-86fc-f78a659d7c5f.png">
<img width="847" alt="screen shot 2017-08-06 at 2 02 00 am" src="https://user-images.githubusercontent.com/4969719/29001015-560b35e2-7a4b-11e7-98c9-25f62eb0e83a.png">

**Comment by kidtsunami** [comment]
@opensourcejunkie given Salesforce's launch of [their own extension for VS Code](https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode), Development and Support for MavensMate is [officially over](http://mavensmate.com/).

Good news is their extension should have better autocomplete!

**Comment by ChuckJonas** [comment]
There's also [Salesforce Language Support](https://marketplace.visualstudio.com/items?itemName=chuckjonas.apex-autocomplete) that works well with Mavensmate in vscode.  The autocomplete is much more robust than anything Mavensmate ever provided in SublimeText.

 _(disclaimer: I'm the author)_
