### ISSUE TITLE
After entering credentials the redirecting screen never goes through and then the white blank screen appears since the timeout has reached.

### ISSUE THREAD

**Issue by Azmathulla** [joeferraro/MavensMate#1002]
latest as per internet, MavensMate-Desktop-Setup-0.0.11-beta.7-ia32

sublime text 3

latest as per internet, MavensMate for sublime text v7.o.2
![maven2_error](https://user-images.githubusercontent.com/12094387/29057749-3a6249e4-7c2a-11e7-8109-700e6a19b832.png)

 

Windows 10 64-bit

Yes, Inside company, not sure proxy configs

36.0

cs22

After entering credentials the redirecting screen never goes through and then the white blank screen appears since the timeout has reached.

![maven1_error](https://user-images.githubusercontent.com/12094387/29057683-d5e13660-7c29-11e7-840d-c306f6c00c76.png)
Please help!

**Comment by kidtsunami** [comment]
@Azmathulla was this with an existing project or a new one? I have you tried restarting everything and connecting to a dev org?

**Comment by Azmathulla** [comment]
@kidtsunami , It is a first time installation in my office and my experience, i have done installing both sublime & mavensmate desktop, i have also configured the package control for setting up mavensmate plugin on the sublime text.

Now when i go further and create new project, after credentials are given for developer/sandbox/production it lands on re-directing page and nothing goes through further!

Kindly guide me to fix this ASAP. lot to code and i'm struggling from a week on mavensmate set up.

Thanks

**Comment by kidtsunami** [comment]
At this point @Azmathulla I would recommend that you either use the Eclipse Force.com IDE or the developer console if this is blocking your work.

I currently can not reproduce what you're experiencing.

**Comment by Azmathulla** [comment]
@kidtsunami , can you quickly tell me the steps you simply followed in-order to install mavensmate, so that i have not missed one of them.

Also can you kindly tell me if aside.io is a good developing tool for production works, in case of security, speed & reliability?

Appreciate for your answers!!

**Comment by kidtsunami** [comment]
@Azmathulla you can follow the instructions here: https://github.com/joeferraro/MavensMate

I have no experience with aside.io so I'm not sure I can recommend it?

**Comment by Azmathulla** [comment]
@kidtsunami , can you tell if any proxy setting has to to enabled on mavens mate desktop, since i'm working from office LAN connectivity.

kindly guide
