### ISSUE TITLE
Error initializing project: Unrecognized package.xml metadata type: StandardValueSet

### ISSUE THREAD

**Issue by Mavensmate** [joeferraro/MavensMate#1022]
I have installed mavenmate v0.0.10 and i got this error when i launch open project
"Error initializing project: Unrecognized package.xml metadata type: StandardValueSet''

**Comment by e02d96ec16** [comment]
Maybe your need to change the API version set in your MM/project

> In API version 38.0 and later, standard picklists are represented by the StandardValueSet type.

**Comment by Mavensmate** [comment]
Please clarify where do i set API version 38.0 in my mavensmate project..   Thanks

**Comment by e02d96ec16** [comment]
Sorry, it's not for the project, it's just for MM.

I find mine in the burger menu > Settings, but I'm not using the latest version which was redesigned a fair bit.

**Comment by Mavensmate** [comment]
sorry am still not getting it where to change the version ,there is no option to change version in MavensMate(MM) ? please assist
