### ISSUE TITLE
Installation issues on Linux Mint (Nov 15 2013 release)

### ISSUE THREAD

**Issue by ianzepp** [joeferraro/MavensMate#139]
While installing onto a fresh Linux Mint setup, I ran into the following issues (in order):

1. Curl is not installed. Must apt-get.
2. Git is not installed. Must apt-get.
3. Trying to pull down / run the install script failed with an error about "branch named 'master' already exists" (see screenshot 1).

![screenshot from 2013-11-24 11 45 46](https://f.cloud.github.com/assets/757705/1609051/a5c000b2-552a-11e3-966f-3d98545d5c56.png)

4. However, it appears that MavensMate was added to the SublimeText3 menubar. 
5. Trying to create a new project failed due to the mm_workspace missing.
6. This was missing because the entire "mavensmate.sublime-settings" file was blank/missing. Searched online for a sample, found one, tried to save, and got this error:

![screenshot from 2013-11-24 11 57 14](https://f.cloud.github.com/assets/757705/1609057/fe34199a-552a-11e3-85f4-eae61c50dc9e.png)

7. Looking through the directory structure for this location, I discovered that the "User" directory was actually a "User" file, and the file contained what should have been the contents of the "mavensmate.sublime-settings" file. So I renamed the original "User" file, create a directory called "User", and moved the original contents into "User/mavensmate.sublime-settings".

![screenshot from 2013-11-24 11 57 30](https://f.cloud.github.com/assets/757705/1609062/1cc25c50-552b-11e3-94f7-86f80637a865.png)

8. Then, trying to create a new project failed due to being unable to find the "subl" executable, even though we are already running in Sublime. Researching this discovered that the default was "/usr/local/bin" instead of "/usr/bin":

![screenshot from 2013-11-24 12 00 01](https://f.cloud.github.com/assets/757705/1609069/679afdfe-552b-11e3-9834-98ee9f39d2b9.png)

9. At this point, trying to create a new MavensMate project simply silently fails.

Thanks!

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
