### ISSUE TITLE
Filter Apex debug log upon test execution, just as the SF developer console can

### ISSUE THREAD

**Issue by qsbpetf** [joeferraro/MavensMate#142]
To easy spot errors and other interesting data when using System.debug() in Apex it would be nice to have a checkbox [ ] DEBUG [___________] for filtering (showing only) lines with debug output "|DEBUG|" and maybe a checkbox [ ] TEXT [__________] for free text filtering in the debug log. Why not a [ ] REGEXP [__________] as well ;)

Thank you all for a GREAT tool!

**Comment by Alexalex1432** [comment]
I just had the thought that this would be really useful.  @joeferraro I feel like I could implement this (since I imagine it would all be in the page that displays the log) if you can point me in the direction where those pages are generated

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe

**Comment by qsbpetf** [comment]
Hi Joe!

Just installed latest version.
Thanks

/Peter

On Wed, Oct 14, 2015 at 7:56 PM, Joe Ferraro <notifications@github.com>
wrote:

> Hi, thanks for using MavensMate and thanks for helping us making it better
> by submitting an issue! MavensMate has undergone a significant re-write as
> of January 2015 and in order to focus our time on new bugs, we are closing
> all open issues that were submitted before this data. I encourage you to
> try to newest version of MavensMate and re-open this issue if it remains a
> problem.
>
> Cheers,
>
> -Joe
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joeferraro/MavensMate/issues/142#issuecomment-148135671>
> .
>



-- 
Peter Friberg
Senior developer, Architect, Consultant
Fluido Sweden AB
office: Drottninggatan 71D, Stockholm
mob: +46 708 211 679
email: peter.friberg@fluidogroup.com

Let's keep the conversation going! Follow Fluido on social media:
Twitter @FluidoTweets *http://bit.ly/fluidotweets
<http://bit.ly/fluidotweets>*
LinkedIn *http://bit.ly/fluidolinkedin <http://bit.ly/fluidolinkedin>*
Facebook *http://bit.ly/fluidofacebook <http://bit.ly/fluidofacebook>*
Homepage www.fluidogroup.com

Offices:
Sweden, Drottninggatan 71D, Stockholm
Denmark, Bredgade 33A, Copenhagen
Norway, Karl Johans gate 25, Oslo
Finland, Tekniikantie 14, Espoo
