### ISSUE TITLE
Keychain issue while connecting to Mercurial

### ISSUE THREAD

**Issue by pankaj1009** [joeferraro/MavensMate#150]
Result: [OPERATION FAILED]:Unable to retrieve password from the keychain store.

I am getting this error when I tried to save any class or visualforce page. I have imported my cloned project from TortoiseHg(Mercurial version system) which resides on my local   machine.

I tried this solution "your other option is to delete the config directory, right click the project name in the Sublime Text sidebar, and MavensMate > Create MavensMate project" but still I am getting the same error.

 Is there any workaround for this ?

**Comment by navini** [comment]
I have come across the same issue. Did anyone figure out a solution? Thanks

**Comment by joeferraro** [comment]
this has been resolved in the upcoming release
