### ISSUE TITLE
'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by fourq** [joeferraro/MavensMate#184]
After clicking "Crete Project" in the browser, I get this message: 'NoneType' object has no attribute '__getitem__'.

![mm_none_type](https://f.cloud.github.com/assets/1033604/1956731/96838200-81fc-11e3-85de-db406be454bc.png)

Console out:

<MavensMate.lib.server.lib.handler.Handler object at 0x7fe4a427e090>
[MAVENSMATE UI]: >>> handling request
[MAVENSMATE UI]: /project/existing
[MAVENSMATE UI]: >>> running an async operation
[MAVENSMATE UI]: vyj6nl24
[MAVENSMATE UI]: {'org_type': 'sandbox', 'username': '<email>', 'project_name': 'salesforce', 'workspace': '/home/rocky/projects', 'directory': '/home/rocky/projects/salesforce', 'password': '<pass+token>', 'org_url': '', 'action': 'existing'}
[MAVENSMATE UI]: b'{"project_name":"salesforce","username":"<email>","password":"<pass+token>","org_type":"sandbox","directory":"/home/rocky/projects/salesforce","org_url":"","workspace":"/home/rocky/projects","action":"existing"}'
[MAVENSMATE UI]: worker created
[MAVENSMATE UI]: >>> running thread arguments on next line![MAVENSMATE UI]: worker thread started

[MAVENSMATE UI]: placed into queue
[MAVENSMATE UI]: -o new_project_from_existing_directory -c SUBLIME_TEXT_3
[MAVENSMATE UI]: responding with async request id!
RUNNING DEBUG BACKGROUND WORKER!!!
b'{"project_name":"salesforce","username":"<email>","password":"<pass+token>","org_type":"sandbox","directory":"/home/rocky/projects/salesforce","org_url":"","workspace":"/home/rocky/projects","action":"existing"}'
[MAVENSMATE UI]: {"status": "pending", "id": "vyj6nl24"}
[MAVENSMATE UI]: >>> handling request
[MAVENSMATE UI]: /status?id=vyj6nl24
[MAVENSMATE UI]: >>> status request
[MAVENSMATE UI]: >>> params: 
[MAVENSMATE UI]: {'id': 'vyj6nl24'}
[MAVENSMATE UI]: >>> request id: vyj6nl24
[MAVENSMATE UI]: >>> async queue: 
[MAVENSMATE UI]: {'vyj6nl24': <BackgroundWorker(Thread-12, started 140619896837888)>}
[MAVENSMATE UI]: found async thread, is it alive????
[MAVENSMATE UI]: True
[MAVENSMATE UI]: >>> request is not ready
[MAVENSMATE UI]: responding with async request id!
[MAVENSMATE UI]: {"status": "pending", "id": "vyj6nl24"}
[MAVENSMATE UI]: >>> got a response body
[MAVENSMATE UI]: {"body": "'NoneType' object has no attribute '__getitem__'", "body_type": "text", "success": false}

[MAVENSMATE UI]: >>> handling request
[MAVENSMATE UI]: /status?id=vyj6nl24
[MAVENSMATE UI]: >>> status request
[MAVENSMATE UI]: >>> params: 
[MAVENSMATE UI]: {'id': 'vyj6nl24'}
[MAVENSMATE UI]: >>> request id: vyj6nl24
[MAVENSMATE UI]: >>> async queue: 
[MAVENSMATE UI]: {'vyj6nl24': <BackgroundWorker(Thread-12, stopped 140619896837888)>}
[MAVENSMATE UI]: found async thread, is it alive????
[MAVENSMATE UI]: False
[MAVENSMATE UI]: >>> request is probably ready, returning response!!

**Comment by joeferraro** [comment]
this has been resolved in the upcoming release
