### ISSUE TITLE
Malformed Request saving metadata

### ISSUE THREAD

**Issue by kennesk** [joeferraro/MavensMate#222]
Hi - When I try to save an Apex class or page from MavensMate I get the following error. This happens on any file and in any of the Saleforce orgs I am a System Admin for.
 Result: [OPERATION FAILED]:Malformed request https://na15.salesforce.com/services/data/v29.0/query/?q=Select+LastModifiedById%2C+LastModifiedDate%2C+LastModifiedBy.Name%2C+Markup+From+ApexPage+Where+Name+%3D+%27hellowworld%27. Response content: <HTML><HEAD>

Looks like there is a '.'  between 'LastModifiedBy' and 'Name'?

- Windows 7
- MavensMate for Sublime Text v3.4.4
- Sublime Text 3
- tried API version 26.0 and 29.0

Thanks.

**Comment by joeferraro** [comment]
this has been resolved in the upcoming release
