### ISSUE TITLE
Connecting to existing project error

### ISSUE THREAD

**Issue by sumitvakil** [joeferraro/MavensMate#255]
MavensMate version: v3.4.6
Sublime Text version: Build 3059
OS: Mac OS X 10.9.2

I followed the instructions here http://mavensmate.com/Plugins/Sublime_Text/Existing_Projects to create a project from an existing folder. I have checked and double checked the directory layout and the instructions. However, after providing the Salesforce credentials to MavensMate, I consistently get the following log file. The error towards the end of the file is the same every time. The directory referenced in the error, mm_projects exists and has write permissions for the logged in user (me). Hence I am assuming that the directory test under mm_projects is not getting created. I tried manually creating the "test" directory before attempting to connect to the project, but no luck. The log then complains that the "test" folder already exists.

 --------------------------------------------
 ---------- NEW OPERATION REQUESTED ---------
 --------------------------------------------

new_project_from_existing_directory
Namespace(client='SUBLIME_TEXT_3', format='json', operation='new_project_from_existing_directory', quiet=False, respond_with_html=False, ui_switch=True, verbose=False)
{'verbose': False, 'args': Namespace(client='SUBLIME_TEXT_3', format='json', operation='new_project_from_existing_directory', quiet=False, respond_with_html=False, ui_switch=True, verbose=False), 'client': 'SUBLIME_TEXT_3', 'ui': True, u'directory': u'/Users/sav/Documents/src/test/test1/myproj', 'operation': 'new_project_from_existing_directory'}

 --------------------------------------------
 UI operation requested, attempting to launch MavensMate UI
 ---------------------
result from command execution
{"body": "UI Generated Successfully", "body_type": "text", "success": true, "time": "1.2474348545074463"}
<type 'str'>
---------------------

 ---------------------
 RESPONDING TO REQUEST
 ---------------------

{"body": "UI Generated Successfully", "body_type": "text", "success": true, "time": "1.2474348545074463"}

 --------------------------------------------
 ---------- NEW OPERATION REQUESTED ---------
 --------------------------------------------

new_project_from_existing_directory
Namespace(client='SUBLIME_TEXT_3', format='json', operation='new_project_from_existing_directory', quiet=False, respond_with_html=False, ui_switch=False, verbose=False)
{u'username': u'jsmith-customer@acme.com', u'project_name': u'test', 'verbose': False, 'args': Namespace(client='SUBLIME_TEXT_3', format='json', operation='new_project_from_existing_directory', quiet=False, respond_with_html=False, ui_switch=False, verbose=False), u'org_url': u'', u'org_type': u'developer', 'client': 'SUBLIME_TEXT_3', 'ui': False, u'workspace': u'/Users/sav/Documents/src/mm_projects', u'directory': u'/Users/sav/Documents/src/test/test1/myproj', 'operation': 'new_project_from_existing_directory', u'password': u'acme-12348', u'action': u'existing'}

--------------------------------------------
------\> 
{u'username': u'jsmith-customer@acme.com', u'project_name': u'test', u'org_url': u'', u'org_type': u'developer', u'workspace': u'/Users/sav/Documents/src/mm_projects', u'directory': u'/Users/sav/Documents/src/test/test1/myproj', u'password': u'acme-12348', u'action': 'existing'}
\>\>\>\>\>\> 
/Users/sav/Documents/src/mm_projects/test
sending to (https://www.salesforce.com/services/Soap/u/28.0)
message:
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:ns0="urn:partner.soap.sforce.com" xmlns:ns1="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Header/>
   <ns1:Body>
      <ns0:login>
         <ns0:username>jsmith-customer@acme.com</ns0:username>
         <ns0:password>acme-12348</ns0:password>
      </ns0:login>
   </ns1:Body>
</SOAP-ENV:Envelope>
headers = {'SOAPAction': u'""', 'Content-Type': 'text/xml; charset=utf-8', u'User-Agent': u'MavensMate'}
http succeeded:
<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns="urn:partner.soap.sforce.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soapenv:Body><loginResponse><result><metadataServerUrl>https://na14.salesforce.com/services/Soap/m/28.0/00Dd0000000etmP</metadataServerUrl><passwordExpired>false</passwordExpired><sandbox>false</sandbox><serverUrl>https://na14.salesforce.com/services/Soap/u/28.0/00Dd0000000etmP</serverUrl><sessionId>00Dd0000000etmP!AQ4AQJ6DI.fl0DUCanxmLiBJpCEwbe.cW5UBgCXeFr0dBdv0KQWRz3QEeiygj70YV6gN9hp.0uwz23CNL8NYa4p7o80jFymK</sessionId><userId>005d0000001AaonAAC</userId><userInfo><accessibilityMode>false</accessibilityMode><currencySymbol>$</currencySymbol><orgAttachmentFileSizeLimit>5242880</orgAttachmentFileSizeLimit><orgDefaultCurrencyIsoCode>USD</orgDefaultCurrencyIsoCode><orgDisallowHtmlAttachments>false</orgDisallowHtmlAttachments><orgHasPersonAccounts>false</orgHasPersonAccounts><organizationId>00Dd0000000etmPEAQ</organizationId><organizationMultiCurrency>false</organizationMultiCurrency><organizationName>Customer Org</organizationName><profileId>00ed0000001270dAAA</profileId><roleId>00Ed0000000uIeWEAU</roleId><sessionSecondsValid>7200</sessionSecondsValid><userDefaultCurrencyIsoCode xsi:nil="true"/><userEmail>jsmith@acme.com</userEmail><userFullName>Customer Joe</userFullName><userId>005d0000001AaonAAC</userId><userLanguage>en_US</userLanguage><userLocale>en_US</userLocale><userName>jsmith-customer@acme.com</userName><userTimeZone>America/Los_Angeles</userTimeZone><userType>Standard</userType><userUiSkin>Theme3</userUiSkin></userInfo></result></loginResponse></soapenv:Body></soapenv:Envelope>
LOGIN RESULT
(LoginResult){
   metadataServerUrl = "https://na14.salesforce.com/services/Soap/m/28.0/00Dd0000000etmP"
   passwordExpired = False
   sandbox = False
   serverUrl = "https://na14.salesforce.com/services/Soap/u/28.0/00Dd0000000etmP"
   sessionId = "00Dd0000000etmP!AQ4AQJ6DI.fl0DUCanxmLiBJpCEwbe.cW5UBgCXeFr0dBdv0KQWRz3QEeiygj70YV6gN9hp.0uwz23CNL8NYa4p7o80jFymK"
   userId = "005d0000001AaonAAC"
   userInfo = 
      (GetUserInfoResult){
         accessibilityMode = False
         currencySymbol = "$"
         orgAttachmentFileSizeLimit = 5242880
         orgDefaultCurrencyIsoCode = "USD"
         orgDisallowHtmlAttachments = False
         orgHasPersonAccounts = False
         organizationId = "00Dd0000000etmPEAQ"
         organizationMultiCurrency = False
         organizationName = "Customer Org"
         profileId = "00ed0000001270dAAA"
         roleId = "00Ed0000000uIeWEAU"
         sessionSecondsValid = 7200
         userDefaultCurrencyIsoCode = None
         userEmail = "jsmith@acme.com"
         userFullName = "Customer Joe"
         userId = "005d0000001AaonAAC"
         userLanguage = "en_US"
         userLocale = "en_US"
         userName = "jsmith-customer@acme.com"
         userTimeZone = "America/Los_Angeles"
         userType = "Standard"
         userUiSkin = "Theme3"
      }
 }
[MAVENSMATE CAUGHT ERROR]
Traceback (most recent call last):
  File "/Users/josephferraro/Development/Github/mm/tools/pyinstaller-dev/mm/build/pyi.darwin/mm/out00-PYZ.pyz/lib.project", line 117, in retrieve_and_write_to_disk
  File "/Users/josephferraro/Development/Github/mm/tools/pyinstaller-dev/mm/build/pyi.darwin/mm/out00-PYZ.pyz/lib.project", line 1098, in __put_project_file
IOError: [Errno 2] No such file or directory: u'/Users/sav/Documents/src/mm_projects/test/test.sublime-project'

---------------------
result from command execution
{"body": "An error has occurred. Please enable plugin logging, retry your operation and paste any relevant log(s) to a new GitHub issue.", "body_type": "text", "success": false}
<type 'str'>
---------------------

 ---------------------
 RESPONDING TO REQUEST
 ---------------------

{"body": "An error has occurred. Please enable plugin logging, retry your operation and paste any relevant log(s) to a new GitHub issue.", "body_type": "text", "success": false}

Thanks,

Sumit

**Comment by ankushsomani09** [comment]
I am also facing the same type of issue.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
