### ISSUE TITLE
MM doesn't work with portable Sublime Text install

### ISSUE THREAD

**Issue by rkaramc** [joeferraro/MavensMate#269]
Installed MM on a portable version of ST3 - but getting the error message below. How can I fix the paths to make MM work?!

Workspace path is `	"mm_workspace" : "C:\\Users\\_____\\Documents\\dev\\sfdc",`
ST3 is installed on "D:\\Tools\\sublimetext3".

Error message in ST3 console:
`[MAVENSMATE]: response from mm: {"body": "Please set mm_workspace to the location where you'd like your mavensmate projects to reside", "stack_trace": "Traceback (most recent call last):\n  File \"D:\\tools\\sublimetext3\\Data\\Packages\\MavensMate\\mm\\lib\\request.py\", line 63, in execute\n    self.__setup_connection()\n  File \"D:\\tools\\sublimetext3\\Data\\Packages\\MavensMate\\mm\\lib\\request.py\", line 54, in __setup_connection\n    verbose=self.args.verbose)\n  File \"D:\\tools\\sublimetext3\\Data\\Packages\\MavensMate\\mm\\lib\\connection.py\", line 33, in __init__\n    self.workspace              = params.get('workspace', self.get_workspace())\n  File \"D:\\tools\\sublimetext3\\Data\\Packages\\MavensMate\\mm\\lib\\connection.py\", line 123, in get_workspace\n    raise MMException(\"Please set mm_workspace to the location where you'd like your mavensmate projects to reside\")\nMMException: Please set mm_workspace to the location where you'd like your mavensmate projects to reside\n", "success": false}
`

**Comment by ruwanthalk** [comment]
1)GO to C:\Users\YOURUSERNAME\AppData\Roaming
2)If there is "Sublime Text 3" folder delete it
3)In CMD execute  mklink /j "Sublime Text 3"  "PORTABLE ST PATH\Data"
4)Open ST3 MavensMate goto setting then goto user settings then search "mm_windows_subl_location" give the "PORTABLE ST PATH/sublime_text.exe"
5)Restart ST3

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe

**Comment by Guitarbum722** [comment]
Way to go @jow5 - That worked splendidly!  Thanks for the suggestions everyone.
