### ISSUE TITLE
The local MavensMate server did not respond properly. This likely means it is not running or it is malfunctioning. Try restarting your text editor and MavensMate.app.

### ISSUE THREAD

**Issue by rwparris2** [joeferraro/MavensMate#295]
I get the error "The local MavensMate server did not respond properly. This likely means it is not running or it is malfunctioning. Try restarting your text editor and MavensMate.app." every time I try to create a new project.

I'm on windows 7
Sublime Text 3 build 3059 (I've tried both x86 & 64 bit versions)
MavensMate-SublimeText v3.5.0

I tried installing it with the windows installer and via the manual instructions.

Here is the output of sublime's console:

```
plugins loaded
[MAVENSMATE]: Loading MavensMate for Sublime Text
[MAVENSMATE UI]: >>> starting threaded MavensMate server!
[MAVENSMATE]: Calling mm_interface
[MAVENSMATE]: OPERATION: new_project
[MAVENSMATE]: {}
[MAVENSMATE]: executing mm terminal call:
[MAVENSMATE]: "C:\Program Files (x86)\MavensMate\App\python.exe" -E "C:\Users\rparris\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\mm.py" -c SUBLIME_TEXT_3 --ui -o new_project
[MAVENSMATE]: {}
[MAVENSMATE]: response from mm: {"body": "UI Generated Successfully", "body_type": "text", "success": true, "time": "1.6629998683929443"}
```

I've enabled logs but they don't share any unique information.

When I input the information into the new projects page and click "Create project", I get the error "The local MavensMate server did not respond properly. This likely means it is not running or it is malfunctioning. Try restarting your text editor and MavensMate.app."

Chrome console shows the following error "OPTIONS http://127.0.0.1:7777/project net::ERR_CONNECTION_RESET "

It looks like the local MavensMate server isn't running at all, even though the sublime logs says it was started.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
