### ISSUE TITLE
MM reports a successful save, but fails save due to error behind scenes: UNABLE_TO_LOCK_ROW

### ISSUE THREAD

**Issue by Katulka** [joeferraro/MavensMate#320]
I am using MM 3.5.2 with ST3.

I am working in a Summer 14 sandbox and attempting to save a change to an existing class.  MM says it saved, success.  But changes are not saved. I tried developer console through SF UI/Browser and immediately got this error instead:

UNABLE_TO_LOCK_ROW
Failed to create createContainerMember for containerId=1dcC00000004GonIAE: unable to obtain exclusive access to this record

This could be a rare event and hard to reproduce as this looks like SF has a lock on the class, but for certain it was not a successful save.

Here is the console:

Writing file /c/mm_projs/Full Stage/src/classes/SDQGetP.cls with encoding UTF-8 (atomic)
[MAVENSMATE]: Calling mm_interface
[MAVENSMATE]: OPERATION: compile
[MAVENSMATE]: {'params': {'files': ['c:\\mm_projs\\Full Stage\\src\\classes\\SDQGetP.cls']}, 'context': <sublime.View object at 0x00000000046DB5F8>}
[MAVENSMATE]: executing mm terminal call:
[MAVENSMATE]: "C:\Program Files (x86)\MavensMate\App\python.exe" -E "C:\Users\m\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\mm.py" -c SUBLIME_TEXT_3 -o compile --verbose
[MAVENSMATE]: {"project_name": "Full Stage", "workspace": "c:\\mm_projs", "files": ["c:\\mm_projs\\Full Stage\\src\\classes\\SDQGetP.cls"]}
[MAVENSMATE]: response from mm: 
[MAVENSMATE]: Issue handling compile result in callback
[MAVENSMATE]: No JSON object could be decoded
[MAVENSMATE]: HANDLING COMPILE!
[MAVENSMATE]: 

Here is the MM Panel:

MavensMate for Sublime Text v3.5.2
                                                                          
Operation: Compiling: c:\mm_projs\Full Stage\src\classes\SDQGetP.cls
Timestamp: Wed, 30 Jul 2014 18:43:31
   Result: Success

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
