### ISSUE TITLE
Access Denied issue when trying to create a new force.com project

### ISSUE THREAD

**Issue by ktatta** [joeferraro/MavensMate#325]
I've installed sublime and mavensmate on windows 8. When I try to create a new project, I see an error in the browser saying "An error has occurred. Please enable plugin logging, retry your operation and paste any relevant log(s) to a new GitHub issue."

When I looked at the logs, it appears to be an access issue. I've edited my workspace folder so that all the users has full control to read/write but the issue still persists.

Heres the log info:
[MAVENSMATE CAUGHT ERROR]
Traceback (most recent call last):
  File "C:\Users\ktatt001\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\lib\project.py", line 113, in retrieve_and_write_to_disk
    util.rename_directory(os.path.join(config.connection.workspace,self.project_name,"unpackaged"), os.path.join(config.connection.workspace,self.project_name,"src"))
  File "C:\Users\ktatt001\AppData\Roaming\Sublime Text 3\Packages\MavensMate\mm\lib\util.py", line 231, in rename_directory
    os.rename(old_directory_name, new_directory_name)
WindowsError: [Error 5] Access is denied

**Comment by jeffrutter** [comment]
Hello,

I wanted to share what was the solution for me on this issue. I tried to create a new project in Mavensmate and was getting the same error code. I realized after uninstalling the McAfee trial software on my computer (To reinstall something better....) that it definitely had something to do with the firewall settings the trial software was using. My new AV service prompted me to decide whether to block the plug-in and after opting out of that I was able to create the 3 projects I had been trying to create all along.

Perhaps checking your Antivirus settings or Firewall settings could help!

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
