### ISSUE TITLE
Consistently taking over 30 seconds to save a file compared with 5 seconds through Developer console

### ISSUE THREAD

**Issue by donmac23** [joeferraro/MavensMate#361]
I like using MM but this is kind of a showstopper. I'm really hoping I have some kind of setting wrong. Here are the relevant settings I am using (on Win 7 64 bit machine, version 3.5.4):

	"mm_compile_on_save" : true,
	"mm_compile_with_tooling_api" : true,

...have tried setting mm_compile_with_tooling_api to false but made little difference. Any tips on how I can get MM to be saving changes as fast as the dev console?

note: Eclipse also seems to be a lot faster from the few times I have been using it - well under 10 secs too. TIA for any help.

**Comment by danwatt** [comment]
I am seeing this as well. It usually appears to be a problem on Sandbox instances (CS8 and CS7 as of late). I have not observed this problem on any NA* instances.

**Comment by harmon** [comment]
I've seen that too ever since I've used MavensMate (> 1 year). My guess is that:

**Comment by Avarga954** [comment]
I think it would be pretty helpful if people experiencing this issue provided what instance they are on. As this may be an issue with the Salesforce Instance combined with MavensMate. most of my team and I are on CS7 experiencing this problem however one of our teammates is on cs25 and is experiencing no issue.

@joeferraro 
Also I downgraded to version 4.5  and I am still getting this issue.

**Comment by joeferraro** [comment]
Really appreciate your insight @Avarga95 and I agree, it's virtually impossible for us to understand whether there's an issue on the MavensMate side given there are so many Salesforce.com servers/orgs and very little we're doing other than passing files to compile and receiving a response.

**Comment by joeferraro** [comment]
for folks having issues with compile times, you may want to install the latest mm-app beta, as i've introduced a streamline compilation method that circumvents the metadata api when compiling apex & vf metadata: https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.9-beta4

please update this thread with your experiences.

**Comment by farbotkol** [comment]
The update in v0.0.9-beta4 has made a significant improvement compile time. From approx 5Mins to approx <10 seconds. Thank you

**Comment by joeferraro** [comment]
@farbotkol thanks for the feedback. the fact that this update has made such a significant improvement to compilation time is evidence that the salesforce.com metadata api was the bottleneck. you could still run into issue retrieving metadata or compiling non-apex/lightning/visualforce metadata because we are using the metadata api for those types.

**Comment by donmac23** [comment]
Just tried it out. Using v5 of MM with the Mavensmate-app installed. Getting around 10-15 secs on CS6 sandbox for my compiles. Certainly better than the 30+ secs I was getting earlier on when I raised this issue. Thanks @joeferraro

**Comment by troyconquer** [comment]
Fixed here too. Thanks @joeferraro . Really appreciate this tool and your hard work.

**Comment by joeferraro** [comment]
thanks for the updates guys

**Comment by sabbella** [comment]
I am facing the same issue. My instance is cs16. Can you please let me know how to install the update? I installed the .exe file from the above link. But not sure, how to point sublime to the updated mavens mate.  I am using windows.
