### ISSUE TITLE
 Unable to compile on MavenMate

### ISSUE THREAD

**Issue by vinjoshi** [joeferraro/MavensMate#374]
I installed Maven(as plugin to sublime) and created the project for SFDev. The metadata is downloaded but under MavensMate, only open project and create project options are enabled. Other options under MavensMate are disabled as well. I’m not able to deploy the class to server nor I'm able to create new metadata from menu.. Any Idea what can be the issue? As of now, sublime is not registered.. I'm running on Windows 7 64 bit machine.

I tried to roll back to earlier build as well (Sublime Text Build 3059 x64 Setup), but still facing the same issue.

Text from console :

DPI scale: 1.25
startup, version: 3059 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/vinjoshi/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/vinjoshi/AppData/Roaming/Sublime Text 3/Local
hardware concurrency: 4
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/vinjoshi/AppData/Roaming/Sublime Text 3/Installed Packages
found 4 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 3 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
startup cache, total files: 154 cache hits: 154
pre session restore time: 0.139734
using gamma: 1.9 (err: 81.5966)
startup time: 0.179734
first paint time: 0.179734
launching: /C/Program Files/Sublime Text 3/plugin_host.exe
loaded 866 snippets
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin Package Control.Package Control
reloading plugin Visualforce.visualforce_completions
reloading plugin MavensMate.config
reloading plugin MavensMate.mavensmate
reloading plugin MavensMate.util
plugins loaded
[MAVENSMATE]: Loading MavensMate for Sublime Text
[MAVENSMATE UI]: starting local MavensMate UI server
[MAVENSMATE]: mm_installer -->
[MAVENSMATE]: checking for updated mm version
[MAVENSMATE]: mm is up to date (0.2.4), no further action needed
Package Control: Skipping automatic upgrade, last run at 2014-11-13 20:31:36, next run at 2014-11-13 21:31:36 or after

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe
