### ISSUE TITLE
Resource Bundles

### ISSUE THREAD

**Issue by cjones700** [joeferraro/MavensMate#375]
I have been unable to get any resource bundle to work. I use js, css and image files in my static resources. Is there a problem with that?

**Comment by nwalsh82** [comment]
I had the same problem when I used an archive without folders, just files. I created a new archive with a folder structure and moved the files in and the resource-bundles have been created as expected. Now I just have to change my references ...

**Comment by jungleeforce** [comment]
@nwalsh82 thanks for commenting it out. That helped! Resource bundle only works if there is a folder structure inside of the zip files..

**Comment by cjones700** [comment]
@joeferraro @jungleeforce @nwalsh82 I agree. This was the problem. It seems that resourec bundler doesn't wokr if there is no base folder. It works in Atom, but seems to error in sublime text.

**Comment by conceptualben** [comment]
Same problem here and creating a folder structured made it work. Thanks.

**Comment by joeferraro** [comment]
Hi, thanks for using MavensMate and thanks for helping us making it better by submitting an issue! MavensMate has undergone a significant re-write as of January 2015 and in order to focus our time on new bugs, we are closing all open issues that were submitted before this data. I encourage you to try to newest version of MavensMate and re-open this issue if it remains a problem.

Cheers,

-Joe

**Comment by viraj89** [comment]
Tried everything after the comments, but still unable to create a bundle! I know that might sound awful but I need you guys help here and tell me what's wrong with my way. I have a folder called "folder". In that folder I have folder "CSS" and it has 2 css files, then I have "JS" folder and it has 5 js files. and so on. What I did is right clicked the "folder" and selected Add to "folder.rar" and then uploaded this to my static resource. This I see successfully at the static at MM! 

Now the challenging thing begins. I select the folder.resource --> MM---> Create Resource Bundle(s) 

It do create folder as shown in the video but it has nothing in it. :( 

Deleted the rar file from static resource, refreshed then tried. Did almost 5 times, didn't work. 

Please help me @joeferraro, @cjones700, @nwalsh82 , @jungleeforce 

Thanks.
