### ISSUE TITLE
Custom folder structure to organize files

### ISSUE THREAD

**Issue by all2human** [joeferraro/MavensMate#381]
Add functionality to MavensMate to support custom folders for apex classes, pages, etc.  I read that a new Force.com IDE in development called The Welkin Suite will allow for custom folders

**Comment by lukecotter** [comment]
I would also like to see this. Looks like it already works when saving individual files.

**Comment by joeferraro** [comment]
I've been wary of spending too much time implementing a solution for this because it has been on the roadmap at Salesforce for quite a while and when it eventually goes GA will cause re-work and general gnashing of teeth.

**Comment by CitrusFruits** [comment]
Is it really on the roadmap? It seems like Salesforce can be pretty slow moving machine in terms of making developer's lives easier. 

I may be rephrasing the original question, but for clarity, would it be possible to have support within the staticresources, pages, components, and classes folders to allow the user to create their own folder sub-structures on their machine, but not actually affecting the organization of the the remote static resources?

**Comment by joeferraro** [comment]
@CitrusFruits there's lot to think about: how would this impact a git repository, for example? For developers not using MavensMate, this would be a huge pain. 

The preferred solution would be mavensmate-specific "package" metadata, stored in a json configuration file of some sort in the project root or config directory that, when applied, provides a package explorer-like functionality without actually impacting the underlying file/folder structure of the project. 

This then becomes a UI/UX effort to:

1. Provide an interface to CRUD the "packages" themselves via our HTML views
2. Visualize the "packages" in the editors themselves (in the project sidebar, perhaps), so consideration of the APIs of Sublime Text and Atom is required.  Do they have support for this kind of project visualization? If not, we'll need to roll our own (easier to do with Atom given the entire chrome is hackable).

**Comment by CitrusFruits** [comment]
Oh man, I didn't even think of git repos. Thanks for the clarity, you definitely bring up some good reasons to be hesitant to make such a change. It looks like it's more of a platform implementation focused challenge.

I guess another approach would be to just straight up have a "Fake Folders" plugin for Sublime, allowing users to create UI only folders/packages in Sublime, completely independent of what MavensMate would do. At this point though, it's not really the burden, responsibility, or domain of you/the MavensMate team.

Solid work Mr. Ferraro, and thanks for developing such an awesome tool.

**Comment by all2human** [comment]
I think we will be waiting for a long time before Salesforce solves this
problem.  The Welkin Suite IDE has solved the issue but it is still a beta
product.

On Wed, Apr 1, 2015 at 11:01 AM, Andrew Duensing <notifications@github.com>
wrote:

> Oh man, I didn't even think of git repos. Thanks for the clarity, you
> definitely bring up some good reasons to be hesitant to make such a change.
> It looks like it's more of a platform implementation focused challenge.
>
> I guess another approach would be to just straight up have a "Fake
> Folders" plugin for Sublime, allowing users to create UI only
> folders/packages in Sublime, completely independent of what MavensMate
> would do. At this point though, it's not really the burden, responsibility,
> or domain of you/the MavensMate team.
>
> Solid work Mr. Ferraro, and thanks for developing such an awesome tool.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joeferraro/MavensMate/issues/381#issuecomment-88515552>
> .
>



-- 
John Collins | Salesforce Developer



3585 Engineering Drive | Norcross  GA, 30092
Office: (678) 421-3000 | Mobile: (678) 862-9650
Email: jcollins@rentpath.com

**Comment by orospakr** [comment]
I submit that It would be particularly useful for capturing third party open source Salesforce libraries as git submodules, thus achieving deterministic dependency freezing.  The "Deploy from Git" buttons that seem popular are way too ephemeral for my taste.

**Comment by joeferraro** [comment]
Closing until packaging enhancements go live on the platform sometime in the next 12-18 months
