### ISSUE TITLE
Cannot locate CaseComment object and related Workflows

### ISSUE THREAD

**Issue by ErikduvetC** [joeferraro/MavensMate#392]
I'm having trouble locating my created Workflow for "Case Comment" (Standard object relate to Case) object in Mavensmate's Edit project. the CaseComment's workflow is not located under Workflows (as I initially thought) and there is no CaseComment object located in Custom Objects. How can I retrieve this for later commits?

**Comment by ralphcallaway** [comment]
looks like CaseComment is returned in list metadata calls for CustomObject or Workflow, tested with ant using v35 ant-salesforce.jar

@ErikduvetC while the edit project page doesn't show these as options you can add them manually to your project manifest (`src/package.xml`).

Here's an example of what you would add
```
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    ...
    <types>
        ...
        <members>CaseComment</members>
        <name>CustomObject</name>
    </types>
    <types>
        ...
        <members>CaseComment</members>
        <name>Worflow</name>
    </types>
    ...
    <version>34.0</version>
</Package>
```

**Comment by ralphcallaway** [comment]
http://salesforce.stackexchange.com/questions/100517/list-metadata-missing-casecomment
