### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by thvd** [joeferraro/MavensMate#394]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with MavensMate. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable MavensMate on @Sourcegraph by going to https://sourcegraph.com/github.com/joeferraro/MavensMate and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by joeferraro** [comment]
Unfortunately, I cannot enable this right now as sourcegraph is requesting private access to 2 organizations of which I am a member.
