### ISSUE TITLE
Can't create new Project

### ISSUE THREAD

**Issue by jonboy99** [joeferraro/MavensMate#407]
Hi,
I've setup Mavents mate with Sublime text and setup my "mm_workspace". However whenever i go to New Project it just opens a text file called "mmriwwok".Has anyone see this before? I've googled around and can't find anything near this issue.

**Comment by joeferraro** [comment]
Please be sure to reference the contributing documentation before submitting new issues: https://github.com/joeferraro/MavensMate/blob/master/CONTRIBUTING.md

Can you specify your platform version and the version of MavensMate you're running?

**Comment by jonboy99** [comment]
I'm running Window 7, and i've installed Mavensmate for Sublime Text v4.02

**Comment by jonboy99** [comment]
Fixed this now. My Pc was opening html files in notepad instead of Chrome, hence when Sublime text tried to open the web mage to create a new project it opened a text file. So i resolved this by setting the default app for opening html pages to Chrome.
