### ISSUE TITLE
Apex XML String Bug

### ISSUE THREAD

**Issue by ZergyPoo** [joeferraro/MavensMate#409]
Hello, I've just recently started using the MavensMate plugin for Sublime Text, and I really dig it. 

One of the things I'm noticing is that when I run Apex scripting through your plugin, it is treating XML strings strangely.

For example, let's say my code is:

String xml = '\<test\>this is some test xml\</test\>';

System.debug(xml);

My debug output only yields "this is some test xml".

When I execute anonymous through eclipse or through the developer console in the browser, I get the full xml string output.

**Comment by leehildebrand** [comment]
I am noticing this same behavior tonight. For the Apex:
			String xmlString = '<job>';
				xmlString += '<planned_duration>7200</planned_duration>';
				xmlString += '<steps type="array">';
					xmlString += '<step>';
						xmlString += '<name>Pick up goods</name>';
					xmlString += '</step>';
				xmlString += '</steps>';
			xmlString += '</job>';
system.debug('*************** xmlString: '+xmlString);

MavensMate outputs:
22:48:14.507 (507908944)|USER_DEBUG|[250]|DEBUG|*************** xmlString: 7200Pick up goods

Developer Console Outputs:
22:51:37:527 USER_DEBUG [250]|DEBUG|*************** xmlString: <job><planned_duration>7200</planned_duration><steps type="array"><step><name>Pick up goods</name></step></steps></job>

**Comment by ralphcallaway** [comment]
closing out as the latest version (app: v0.0.10, st3: v7)  doesn't have a log viewer, it just downloads logs to the `project/debug/logs` directory, which doesn't have any of the escaping issues experienced here
