### ISSUE TITLE
MavensMateWindowServer.app Source

### ISSUE THREAD

**Issue by rickschmidt** [joeferraro/MavensMate#410]
I was looking for the source for MavensMateWindowServer.app to test some changes to the web views. Does that exist anywhere? Any reference I can find 404's.

**Comment by ralphcallaway** [comment]
the latest version (app: v0.0.10, and st3 v7) they're available in this repo 

ui elements are in the `lib/mavensmate/ui` folder, the server itself is `bin/server`
