### ISSUE TITLE
mm api and windows command prompt, mm compile returns list index out of range

### ISSUE THREAD

**Issue by defabien** [joeferraro/MavensMate#415]
Dear joeferraro,

## Problem background

_I'm trying to use mm on windows for some grunt magic in creating and managing staticresources for one page apps with a big codebase. Using components to split and manage my js code only takes me so far and the built in static resource bundles are not exposed in the mm API (AFAIK) for easy use in grunt._

_My current grunt solution would consist of concatenating, minifiying js/css, zipping it to a .resource and then compiling it with mm, once I do that I can add some other magic grunt allows like watch._

## How far I got

After some trail and error with the windows command prompt and mm api (adding it to the PATH variable) I managed to get the mm command to work.

##### commands without json input seem to work nicely i.e. 

    mm compile_project

or 

    mm list_connections

##### commands with json input work when I pipe json via echo, i.e.

    echo {"username": "****@****.be", "password": "k********", "org_type": "production"}
    | mm new_connection

## The problem

However, I'm having problems with mm compile

When I'm doing 

    echo {"project_name": "vlm_sandbox", "files":["src/static.resources/users.resource"]}
    | mm compile

or

    echo {"project_name":"vlm_sandbox", "files": ["C:/Users/Fabien/Desktop/salesforce/********/src/staticresources/users.resource"]}
    | mm compile

I get the error

    {"body": "list index out of range", "body_type": "text", "success": false}

Do you have any idea why this might occur? I think I might be supplying the wrong url, though I did confirm the file lives in C:/Users/Fabien/Desktop/salesforce/********/src/staticresources/users.resource

Any feedback is greatly appreciated, getting this to work would open up a great realm of possibilities for me.

**Comment by defabien** [comment]
I ran the rest referencing a class, i.e. "files":["src/classes/AccountWrapper.cls"], works fine. I'll do some more testing.

**Comment by defabien** [comment]
It also works with components, pages, but when I include a staticresource, it fails with the "list index out of range" error.

**Comment by defabien** [comment]
Here is the error in the mm.log

```plaintext
[MAVENSMATE CAUGHT ERROR]

Traceback (most recent call last):

  File "C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.commands.metadata", line 357, in execute

IndexError: list index out of range
```

**Comment by harmon** [comment]
Hi Defabien,

I'm not quite familiar with how you are utilizing mavensmate, but when I'm developing in Sublime, and I try to save a class file (.cls) that has not been created yet on Salesforce, I get that same error "list index out of range". Essentially it means I need to create the resource either through the web GUI first (and then sync it down to Sublime so Mavensmate knows about it), or I need to use the mavensmate command to create the resource first through the API. Trying to "compile" a new resource doesn't seem to work for me, I need to "create" it first. Unfortunately, I'm not sure how to use the CLI to accomplish this.

I hope that sheds some light on it for you!

- Adam
