### ISSUE TITLE
Server Diff SubMenu Disabled / Greyed Out

### ISSUE THREAD

**Issue by Avarga954** [joeferraro/MavensMate#417]
I am unable to use any of the functions underneath the Server Diff Sub Menu, they are both greyed out.
All of the other sub menus are working fine.. 

I am using sublime version 3 and the latest build of mavens mate 0.2.4 I upgraded right before posting to check to see if this was addressed in the latest version.. However my problem was not solved, Below is what gets output into my console after I fired up mavens mate. (please note this was the first reboot after upgrade)

startup, version: 3065 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/addison.varga/Library/Application Support/Sublime Text 3/Packages
state path: /Users/addison.varga/Library/Application Support/Sublime Text 3/Local
hardware concurrency: 8
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/addison.varga/Library/Application Support/Sublime Text 3/Installed Packages
found 5 files for base name Default.sublime-keymap
found 1 files for base name Default.sublime-mousemap
found 4 files for base name Main.sublime-menu
loading bindings
loading pointer bindings
found 1 files for base name Default.sublime-theme
theme loaded
app ready
startup cache, total files: 178 cache hits: 178
pre session restore time: 0.216179
using gpu buffer for window
using gamma: 2 (err: 6.9282)
first paint time: 0.297352
startup time: 0.337328
launching: /Applications/Sublime Text.app/Contents/MacOS/plugin_host
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Git.add
reloading plugin Git.annotate
reloading plugin Git.commit
reloading plugin Git.diff
reloading plugin Git.flow
reloading plugin Git.git
reloading plugin Git.history
reloading plugin Git.repo
reloading plugin Git.stash
reloading plugin Git.status
reloading plugin Git.statusbar
reloading plugin Package Control.bootstrap
loaded 837 snippets
reloading plugin Package Control.Package Control
reloading plugin MavensMate.config
reloading plugin MavensMate.mavensmate
reloading plugin MavensMate.util
plugins loaded
[MAVENSMATE]: Loading MavensMate for Sublime Text
[MAVENSMATE UI]: starting local MavensMate UI server
[MAVENSMATE]: mm_installer -->
[MAVENSMATE]: checking for updated mm version
[MAVENSMATE]: mm is up to date (0.2.4), no further action needed
Package Control: No updated packages

**Comment by Avarga954** [comment]
![screen shot 2015-03-17 at 2 40 58 pm](https://cloud.githubusercontent.com/assets/5193459/6698226/2eef4792-ccb4-11e4-8301-3a4470d09bc4.png)

**Comment by sebastiankessel** [comment]
I have this exact same problem. Any ideas why it could be happening or workarounds are much appreciated

**Comment by enriquegq** [comment]
The same over here. For me the diff feature works only when there's a conflict between the version of the file on the server and the one I try to save.

**Comment by joeferraro** [comment]
Server diffs are currently only available during conflict resolution
