### ISSUE TITLE
Some flows not deploying properly

### ISSUE THREAD

**Issue by abd3** [joeferraro/MavensMate#420]
I'm using Mac OS X 10.10, Sublime Text 3 (Build 3080) and MavensMate for Sublime Text v4.0.2

I can request all metadata from my org successfully, including all of the versions of flows.
When I attempt to deploy those flows, if there is more than one version of a flow, then the Metadata tab in the Deploy window shows the latest version of the flow without a version number (e.g., "Benefits_Flow" instead of "Benefits_Flow-6". Package.xml shows the same thing. If I attempt to deploy the flow (without a version number) the flow will not successfully deploy.

![screen shot 2015-03-25 at 16 26 15](https://cloud.githubusercontent.com/assets/11654102/6834639/b8210890-d30b-11e4-8cca-9e7467bf98da.png)
![screen shot 2015-03-25 at 16 29 03](https://cloud.githubusercontent.com/assets/11654102/6834687/12fa762a-d30c-11e4-9635-005c4ae117aa.png)

![screen shot 2015-03-25 at 16 28 37](https://cloud.githubusercontent.com/assets/11654102/6834680/03b75b42-d30c-11e4-85cb-331f851e48f1.png)

**Comment by abd3721** [comment]
FYI, I've confirmed that this issue also exists in Mavensmate 0.0.20 for Atom.io 0.184.0
![screen shot 2015-03-26 at 11 30 07](https://cloud.githubusercontent.com/assets/11654102/6849771/86c6ee40-d3ab-11e4-88be-b3b7f089506c.png)
