### ISSUE TITLE
New Metadata Creation Doesn't Respect mm_compile_with_tooling_api

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/MavensMate#426]
mm: v.0.0.35-alpha1(node.js)
st3: node branch commit 0cd0e3a5a69bd802fba1cebccb5435b971d75f3f

When a new apex class it's done with the metadata api not the tooling api when `mm_compile_with_tooling_api` is set to true

**Comment by joeferraro** [comment]
this is expected. "compilation" in this case does not refer to creation. happy to create a feature request to CRUD apex/vf via tooling api, but it's not in scope for v1
