### ISSUE TITLE
Anonymous Apex Window Doesn't Allow Paste in MavensMateWindowServer

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/MavensMate#431]
mm: v.0.0.35-alpha1(node.js)
st3: node branch commit 0cd0e3a5a69bd802fba1cebccb5435b971d75f3f

the apex execute window when opened in MavensMateWindowServer, does not allow paste from a keyboard short-cut (it just beeps when I try)

paste works when right clicking the apex code box

no errors being shown in the MavensMateWindowServer console when pressing apple-v

**Comment by joeferraro** [comment]
https://github.com/joeferraro/MavensMate/commit/e6d24a7bcd89c66a3103e728f3c71262cf747947
