### ISSUE TITLE
Execute Apex Results not Shown After Executing

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/MavensMate#432]
mm: v.0.0.35-alpha1(node.js)
st3: node branch commit 0cd0e3a5a69bd802fba1cebccb5435b971d75f3f

if i enter invalid apex and click execute I get a error message, but if the apex is valid and i execute, no results are shown and the logs tab is not visible

this happens both using the web kit app and when the page is done in chrome

**Comment by joeferraro** [comment]
right, logs are streamed to the file system now versus returned in the response. the process to return logs is to ensure you run the "start logging" command before running commands where you'll expect a log. i agree this UX isn't the greatest, open to suggestions

**Comment by ralphcallaway** [comment]
@joeferraro will think about options

short term, added some explanatory text to the ui windows that relate to logs would cut down on github issue submissions ;) (i.e. logs available in project/debug/logs, you need to set start logging first)

devil's advocate here, if you're executing apex, you nearly always want the log, which would imply the default should be to have the log available without extra steps ...

that said, i would love to have less UI, so pretty excited about the new logging setup, just has a bit of a learning curve

**Comment by joeferraro** [comment]
https://github.com/joeferraro/MavensMate/commit/75c67560ad47e7adc8605a1ea6298f9590627777 closes this issue
