### ISSUE TITLE
Can I create a project with sessionid instead of username/password?

### ISSUE THREAD

**Issue by chiragmehta84** [joeferraro/MavensMate#437]
Can I create a project with sessionid instead of username/password?

PS: Sorry to submit this as issue instead of feature request

**Comment by ralphcallaway** [comment]
@chiragmehta84 with github issues/feature requests are all in the sam bucket

i don't believe this is possible today, although it can definitely be done, what's the use case?

**Comment by chiragmehta84** [comment]
@ralphcallaway I was able to achieve to work with a project using sessionid.

Let's say I want to create project for an org with 
- instance name "na17"
- orgid "00D00000000001" 
- session id "abdefghijklmnopqrstuvwxyz" 
(you can use chrome extensions like Grey Tab etc to see Session Id).

Now
1) Create project with developer (or any other) org credentials
2) Once created navigate to Config -> .session file
3) This file will look like below. 
4) Update metadata_server_url and server_url with na17 or ap1 or appropriate instance name. Also update last 00D.... with your org Id
5) Update sid with session id
6) Save the field and now Right click on Project and say Refresh from Server
7) That's it, you are done and have project with sessionid. 

{"metadata_server_url": "https://na17.salesforce.com/services/Soap/m/28.0/00D00000000001", "endpoint": "https://www.salesforce.com/services/Soap/u/28.0", "user_id": "005o0000000PCmH", "server_url": "https://na17.salesforce.com/services/Soap/u/28.0/00D00000000001", "sid": "abdefghijklmnopqrstuvwxyz"}

UseCase : We use CloudEntr to connect to various customer Salesforce Orgs, this way we don't share org password with team instead provide access to specific org on CloudEntr. CloudEntr is the simple and secure way that businesses access the cloud.

PS : Every time you log out of org, session id will change so once you re-login don't forget to change session id in .session field

**Comment by RajeshKandisa** [comment]
@chiragmehta84 Thats a neat trick.
