### ISSUE TITLE
Compile with tooling api not being respected

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/MavensMate#443]
Compiling apex classes is using the metadata api, even though compile with tooling api setting is true.

Node Version: v0.0.35-alpha1

**Comment by joeferraro** [comment]
@ralphcallaway are you still experiencing this?

**Comment by ralphcallaway** [comment]
@joeferraro i'll keep an eye out for this, that version is pretty old so figure it's easier to wait for it to re-appear than keep this open
