### ISSUE TITLE
Resource bundle bug

### ISSUE THREAD

**Issue by NumaanMohd** [joeferraro/MavensMate#445]
Hi joeferraro,

I cannot create a resource bundle of static resource in my sublime text(windows version). It is only creating a resource bundle of static resource with folder structure in it but I don't have a folder structure I just have css and js files in it. 

Do we have a solution for this??

**Comment by KaushikRay** [comment]
same issue

**Comment by steals** [comment]
If you have just one css file in you static resource then you do not need to create resource bundle at all. Just open your resource file in /src/staticresources folder, modify it and save.
