### ISSUE TITLE
Unit tests failing on API version 34: Server raised fault: 'INVALID_OPERATION: runTests can only be used with a testLevel of RunSpecifiedTests'

### ISSUE THREAD

**Issue by markdamo** [joeferraro/MavensMate#451]
Im trying to run some test classes from my org but have not started to see this error message from MavensMate UI.

"Server raised fault: 'INVALID_OPERATION: runTests can only be used with a testLevel of RunSpecifiedTests'"

I've tried to set the debug levels to 'Info' for all areas of test but still getting the same issue.  Anyone any ideas what this could mean?

**Comment by markdamo** [comment]
Anyone?

**Comment by melaniewright** [comment]
I have this problem too, since refreshing my sandbox and upgrading to v34.0 - guessing it's related to [the new testLevel parameter on the sf:deploy command](http://salesforce.stackexchange.com/questions/12965/how-run-tests-in-default-namespace-for-sandbox-using-ant).

@markdamo have you had any luck getting this going yet?

**Comment by melaniewright** [comment]
I've downgraded to v33.0 and I can run tests again.

**Comment by markdamo** [comment]
Perfect... I have just downgraded to 33.0 and can now run tests... MelanieWright your a *star*

**Comment by sterno** [comment]
Having the same issue and yes, rolling back to version 33 solves it.  It would be nice to get a fix for this though as I end up having to switch back and forth between versions depending on what I'm doing.

**Comment by jimrae** [comment]
I am also having the same issue, and the same workaround (switching to v33) does address it.

**Comment by xiiDev** [comment]
I've downgraded to v33.0 and I can run tests again.

**Comment by CoolerB** [comment]
Why it was closed, as unit tests still not working on 34 version?!

**Comment by ulaskutuk** [comment]
Rolling back to 33 fixes the issue!

**Comment by stunaite** [comment]
Hi, How do I roll back to api 33.0?

Thanks in Advance

**Comment by stunaite** [comment]
PS: Change API version in class and class test xml files with no effect.

**Comment by ulaskutuk** [comment]
go to MavensMate --> Settings --> Default. 
And update default api version to 33

**Comment by stunaite** [comment]
Had to change that on settings-> project once they override default. Thank you so much!

**Comment by LKozakewycz** [comment]
I have been having this issue too.

**Comment by ckoppelman** [comment]
I have this issue both in MavensMate and in ant when I use `runTests="true"` in my `sf:deploy`.

**Comment by joeferraro** [comment]
@ckoppelman what kind of environment is this? (prod, sandbox, etc)

**Comment by ckoppelman** [comment]
In MavensMate, sandbox.

**Comment by joeferraro** [comment]
@ckoppelman are you using mm-app? If so, what version?

**Comment by ckoppelman** [comment]
@joeferraro  unit testing in mm-app works fine.  It's the testing in v6.0.0 of MM for Sublime.  Maybe I need to rollback my mm version?  Or upgrade it?

**Comment by techman97** [comment]
Confirmed - I had my user settings file at v34, got this error (class was at v28).  Set my user settings api version to v33 and all is now well.  Looks to be a change with the way unit tests are run with Winter '16 now.  Yay!

**Comment by ckoppelman** [comment]
Any word on this bug?

**Comment by TracerBullet21** [comment]
I am also having this issue. Any word on it being resolved?

I am using CI so I need to be using api version 36 for metadata pulls and would prefer not to change my settings everytime I want to use MM's superior Test running app.
