### ISSUE TITLE
MavensMate fails to differentiate various versions of dashes in Apex editor

### ISSUE THREAD

**Issue by orikkers** [joeferraro/MavensMate#453]
There are a few versions of dashes that exist and when Apex is edited in Sublime, the plugin fails to show difference between regular dash, en-dash and em dash. This causes picklist values to be duplicated when value is assigned in code to the picklist as a string as salesforce treats those as different values. 

Here are examples ``` - – — ``` - sublime shows ```-``` for all of them. 

Steps to reproduce. 
1. Create a class in Developer Console or Eclipse IDE
2. Put one line of code  for testing ``` String s = '–' ; //long dash \U2013 not \U2012 ```
4. Save.
3. Load class in sublime - a regular dash ```\U2012``` is shown.

**Comment by joeferraro** [comment]
hm. is this a Sublime Text issue or MavensMate issue?

**Comment by OlegForce** [comment]
Depends on how you send the class body via salesforce tooling api.
