### ISSUE TITLE
New Project command does not work in 0.0.38-beta1

### ISSUE THREAD

**Issue by steals** [joeferraro/MavensMate#458]
Just synced 0.0.38-beta1 tag and tried to create a new project. (using SublimeText plugin branch "node" as client)
MavensMate fails with the following error: https://gist.github.com/steals/ac2875891a6c1c9cbff3

npm: '2.11.2'
node: '0.12.5'
SublimeText plugin  branch "node"
MavensMate tag 0.0.38-beta1 ( tried sync with multitenant branch - same error)

**Comment by joeferraro** [comment]
@steals love the eagerness! you've just volunteered to be a beta tester! i just published beta2 and synced the ST `node` branch. let me know if this helps.

**Comment by steals** [comment]
I like to be a beta tester :)

I've synced MavensMate and ST plugin and now I have following error:
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 158, in on_api_ready
    m.plugin_loaded()
  File "/Users/eru/Library/Application Support/Sublime Text 3/Packages/MavensMate/mavensmate.py", line 75, in plugin_loaded
    mm.start_server()
  File "/Users/eru/Library/Application Support/Sublime Text 3/Packages/MavensMate/lib/cli.py", line 80, in start_server
    if server_port == None:
NameError: global name 'server_port' is not defined

Actually there is an error during installation (when I run npm install -g . in the MavensMate folder):
> mavensmate@0.0.38-beta2 postinstall /usr/local/lib/node_modules/mavensmate
> node bin/postInstall

MavensMateWindowServer chmod+x successful
Could not copy to Sublime Text packages directory: undefined
mavensmate@0.0.38-beta2 /usr/local/lib/node_modules/mavensmate

So I manually copy the folder to the node_modules/mavensmate folder inside ST Packages folder.

**Comment by steals** [comment]
Reverted your last commit in ST plugin and successfully created a project.
