### ISSUE TITLE
deploy-resource-bundle does not work

### ISSUE THREAD

**Issue by steals** [joeferraro/MavensMate#462]
Here is the logs https://gist.github.com/steals/a318a0801bd1e6921cc1
Probably JSForce metadata api deploy method ( deploy.js line 65: self.project.sfdcClient.deploy(zipStream, { rollbackOnError : true, performRetrieve: true }); ) does not work with streams opened by fs.createReadStream..

**Comment by joeferraro** [comment]
@steals are you running node 0.12.x? https://github.com/joeferraro/MavensMate-SublimeText/issues/599#issuecomment-121248351

**Comment by steals** [comment]
@joeferraro Yes, switched to 0.10.36 and now it works.

**Comment by steals** [comment]
@joeferraro 
Noticed that nested folder with the name of resource bundle is created and added to static resource every time when I run "Deploy Resource Bundle" command.
![screen shot 2015-07-16 at 11 45 12 am](https://cloud.githubusercontent.com/assets/682252/8718910/9781b3c0-2bb0-11e5-9ca1-d12d0df86f9e.png)
![screen shot 2015-07-16 at 11 47 31 am](https://cloud.githubusercontent.com/assets/682252/8718911/97af2b98-2bb0-11e5-8263-a33789b69b6b.png)
