### ISSUE TITLE
Debug Logging values not being honored when executing Apex via the "Execute Apex ..." dialog.

### ISSUE THREAD

**Issue by stephenroden** [joeferraro/MavensMate#466]
Issue
-----
1. Debug Logging values not being honored when executing Apex via the "Execute Apex ..." dialog.
2. No change in debug options between using tooling and not.

Configuration
-------------
Sublime Text 3
Mavensmate for Sublime Test 4.0.5
Mavensmate API v0.2.41
Open on a Salesforce project.

Assumptions
-----------
That the first line of returned Salesforce logs indicate the log levels being applied.
That the logging options should differ between using tooling and not.

To repeat
---------
Select Mavensmate / Execute Apex ...

Type in 
System.debug('Hello world');
Click Execute.

First line of debug log
31.0 APEX_CODE,DEBUG;APEX_PROFILING,DEBUG;CALLOUT,INFO;DB,INFO;VALIDATION,INFO;WORKFLOW,INFO

Select Debug Options
Change the logging levels on anything to something different.
Click Execute

First line of debug log
31.0 APEX_CODE,DEBUG;APEX_PROFILING,DEBUG;CALLOUT,INFO;DB,INFO;VALIDATION,INFO;WORKFLOW,INFO

Note that the two first lines are identical.

Change the mm_compile_with_tooling_api value and repeat.  Causes identifical output.
I would have expected a different set of flags at the very least.

Going to Salesforce console in the browser
Repeating the process, and using open raw log to view the returned log, you get
34.0 APEX_CODE,DEBUG;APEX_PROFILING,ERROR;CALLOUT,ERROR;DB,ERROR;SYSTEM,ERROR;VALIDATION,ERROR;VISUALFORCE,ERROR;WORKFLOW,ERROR

and when I change the log levels ...

34.0 APEX_CODE,DEBUG;APEX_PROFILING,ERROR;CALLOUT,ERROR;DB,FINEST;SYSTEM,ERROR;VALIDATION,ERROR;VISUALFORCE,ERROR;WORKFLOW,ERROR

Note that DB value went from ERROR to FINEST.

I'm assuming that the difference in the number of items between using the developer console and Mavensmate is related to using tooling or not.
This raises another related issue where the logging options in Mavensmate remain at six items whereas Salesforce console has eight.

**Comment by ZTLoft** [comment]
I'm running into a very similar issuel--but in the Test Runner UI. Even when I change my project settings to another API version, and toggle off (or on) the Tooling API, my debug log and API versions are stuck at:

33.0 APEX_CODE,FINER;APEX_PROFILING,INFO;CALLOUT,INFO;DB,INFO;SYSTEM,DEBUG;VALIDATION,INFO;WORKFLOW,ERROR

Changing my default settings seems to have no affect either. I'm hitting this on both a Windows 7 machine & Mac OSX (Yosemite)--both running Mavensmate for Sublime Text v4.0.5.

**Comment by joeferraro** [comment]
good news guys, this is fixed in the upcoming v5. :+1: 

https://github.com/joeferraro/MavensMate/commit/3c6d2f6475a33ff71fdbfbad8462cdf9b5f52ea4

**Comment by ZTLoft** [comment]
Awesome!

**Comment by stephenroden** [comment]
Thanks Joe.

**Comment by mimidealerteam** [comment]
This just started happening to me today. I have always had the log levels set as follows: "Apex Code Log Level" set to Debug, and all others set to none. When I ran a test this morning, this was the first line: "35.0 APEX_CODE,FINEST;APEX_PROFILING,INFO;CALLOUT,INFO;DB,INFO;SYSTEM,DEBUG;VALIDATION,INFO;VISUALFORCE,INFO;WORKFLOW,FINE" 

I can't change the debug logs and now the log is cutting off before I can get to my debug lines that  I need to see.
