### ISSUE TITLE
Beta8 doesn't parse the file conflicts with server message properly

### ISSUE THREAD

**Issue by yippie** [joeferraro/MavensMate#476]
Save a file with the setting mm_compile_check_conflicts = true.  If there is a conflict, I get the following error.  Changing the setting to false allows it to compile to the server.

Operation: Compiling: ComponentViewOverrideMVN.page
Timestamp: Thu, 23 Jul 2015 16:19:00
   Result: [OPERATION FAILED]: Whoops, unable to parse the response. Please enable logging (http://mavensmate.com/Plugins/Sublime_Text/Plugin_Logging) and post relevant log(s) to a new issue at https://github.com/joeferraro/MavensMate-SublimeText
[RESPONSE FROM MAVENSMATE]: {
    "result": {
        "lastModifiedDate": "", 
        "runTestsEnabled": "false", 
        "createdDate": "", 
        "numberTestErrors": 0, 
        "ignoreWarnings": false, 
        "id": "", 
        "numberComponentErrors": 0, 
        "checkOnly": false, 
        "done": true, 
        "numberTestsCompleted": 0, 
        "success": false, 
        "numberComponentsTotal": 0, 
        "numberComponentsDeployed": 0, 
        "status": "Conflict", 
        "rollbackOnError": false, 
        "createdByName": "", 
        "details": {
            "runTestResult": {
                "totalTime": "0.0", 
                "numTestsRun": "0", 
                "numFailures": "0"
            }, 
            "componentSuccesses": [], 
            "conflicts": {
                "ComponentViewOverrideMVN.page": {
                    "remote": {
                        "Markup": "<apex:page> VF Content goes here </apex:page>", 
                        "LastModifiedDate": "2015-07-23T20:53:40.000+0000", 
                        "tempPath": "/var/folders/pf/w7b79qy525732pzwxrdkdt080000gn/T/mm_115623-3659-z8k4h6 [SERVER COPY].page", 
                        "LastModifiedById": "00530000005T9xZAAS", 
                        "LastModifiedBy": {
                            "Name": "Madmin", 
                            "attributes": {
                                "url": "/services/data/v33.0/sobjects/User/00530000005T9xZAAS", 
                                "type": "User"
                            }
                        }, 
                        "attributes": {
                            "url": "/services/data/v33.0/sobjects/ApexPage/066f000000018vfAAA", 
                            "type": "ApexPage"
                        }
                    }, 
                    "local": {
                        "lastModifiedById": "00530000005T9xZAAS", 
                        "type": "ApexPage", 
                        "id": "066f000000018vfAAA", 
                        "lastModifiedByName": "Madmin", 
                        "createdDate": "2015-01-15 16:59:51", 
                        "fullName": "ComponentViewOverrideMVN", 
                        "mmState": "clean", 
                        "createdByName": "Madmin", 
                        "fileName": "unpackaged/pages/ComponentViewOverrideMVN.page", 
                        "createdById": "00530000005T9xZAAS", 
                        "lastModifiedDate": "2015-07-02 13:27:37"
                    }
                }
            }, 
            "componentFailures": []
        }, 
        "completedDate": "", 
        "startDate": "", 
        "createdBy": "", 
        "numberTestsTotal": 0
    }, 
    "complete": true, 
    "operation": "compile-metadata", 
    "id": "715ea0b0-3180-11e5-8c91-dbb25b99dc19"
}

**Comment by joeferraro** [comment]
@yippie can you do me a favor and pull the latest from the `node` branch of the ST plugin (no longer requires node, instead requires `mavensmate-app` https://github.com/joeferraro/mavensmate-app/releases) and re-test. i cannot reproduce. fyi @steals are you seeing this?

**Comment by yippie** [comment]
I had not updated the ST plugin in a while so that might have been the issue (a version miss-match). I will try and test if this fixed it.
