### ISSUE TITLE
Very slow when saving files

### ISSUE THREAD

**Issue by aleramesh** [joeferraro/MavensMate#478]
I am using mavensmate(v4.0.5) with sublime 3 on OS X and the save time is too long. Sometimes it takes like close to 5 minutes.

I tried switching tooling api on and off but still same..Anybody has suggestions??

**Comment by ralphcallaway** [comment]
i've seen this before, it looks like there is a retrieve call that is part of the process of saving an apex call, and everyone once in a while salesforce is really, really slow returning the retrieve call (like 5 minutes)

**Comment by joeferraro** [comment]
toggling `mm_compile_check_conflicts` to `false` could help, otherwise not much we can do given the bottleneck is often the Salesforce Metadata API. Our upcoming `5.0.0` produces some significant performance boosts as we've tried to circumvent the Metadata APIs usage wherever possible.
