### ISSUE TITLE
Unit test runner unable to detect tests when "test" is not prefix or suffix

### ISSUE THREAD

**Issue by yippie** [joeferraro/MavensMate#479]
When opening the Apex Test Runner UI only two classes show up in the list when there should be closer to 30.  I did not find any errors or notes in the logs around this.

**Comment by joeferraro** [comment]
so you have 30 test apex classes in your project? do they have the name "test" in them?

**Comment by yippie** [comment]
Yes, and they are all marked with @isTest.  For example the following class does not show in the unit test ui runner

@isTest
private class LockRelatedRecordsTestMVN {
....
}

**Comment by joeferraro** [comment]
ah i see the issue, here's the source that determines whether we have a test:

```
if (util.startsWith(fn, 'test') || util.endsWith(fn, 'test')) {
  classes.push(bf);
}
```

**Comment by yippie** [comment]
@joeferraro I assume you either don't have access or it would take much much longer to check for @isTest in the file instead of using the name?

It would be nice if test classes were marked in the .cls-meta.xml file, now that unit test classes are not allowed to be mixed with production classes this seems like something they should and can do.  Oh well, one can dream.
