### ISSUE TITLE
Error: Could not index Apex Symbols: Cannot read property 'Name' of undefined

### ISSUE THREAD

**Issue by steals** [joeferraro/MavensMate#481]
Faced a new error: https://gist.github.com/steals/3242cdfbbeec3d2845f9
Occurs after refresh file from server or compile any file.

MM: latest
MM ST: latest
MM APP: 0.0.1-alpha13

**Comment by joeferraro** [comment]
Can you describe what you were doing?

**Comment by steals** [comment]
@joeferraro Just tried to refresh a visualforce page from server. After that tried to save changes of that page and got same error.
Actually changes were saved to the server, but Sublime Text showed Result: [ERROR]: Request to the local MavensMate server failed. Can't convert 'int' object to str implicitly
And after that it shows this error for every command (instead of progress bar)

**Comment by joeferraro** [comment]
Argh, ok. Probably best to rollback while I figure this out.

Thanks

**Comment by steals** [comment]
cli.py line 156 - need to change to str(port_number)

**Comment by joeferraro** [comment]
reffed: https://github.com/joeferraro/MavensMate-SublimeText/commit/c5d6e58f9caaae8a49196247e8ca0f13a9604368

**Comment by joeferraro** [comment]
@steals are you still seeing this issue?

**Comment by joeferraro** [comment]
I'm going to close for now, feel free to open if it crops back up
