### ISSUE TITLE
Not able to open project in MavensMate

### ISSUE THREAD

**Issue by sun2say** [joeferraro/MavensMate#482]
Hi. MavensMate does not open a project with any of the browsers. Currently, when I tried opening/edit project, it uses Microsoft Word by default. It was working till last week. There wasn't any changes at SublimeText. 

Please advise.

Thanks,
Sam

**Comment by joeferraro** [comment]
Your system's default opener for .html files changed.

**Comment by sun2say** [comment]
Thanks Joe!
Can you please explain more on this. Is this file belong to Sublim Test or Window system file. Where can i find this file for modification.

Appreciate your help!

Thanks,
Sam

**Comment by sun2say** [comment]
Hi Joe,

I found the default setting and changed. Now it working. 
I really thank You so much for the help!

Thanks,
Sam
