### ISSUE TITLE
MM + Sublime3 mavensmate plugin not loading

### ISSUE THREAD

**Issue by pacman6642** [joeferraro/MavensMate#483]
I received this running the sublime plugin on OSX that was older but I can't remember the version. Had to restart my macbook and then sublime showed Could not contact local MavensMate server when I would open it. Removed the plugin then installed the package through package control but I am still receiving this in the mavens mate console

MavensMate for Sublime Text v5.0.0-beta.1

[ERROR]: Could not contact local MavensMate server, please ensure the MavensMate app is installed and running (https://github.com/joeferraro/mavensmate-app/releases). MavensMate will not run properly until resolved.

Is there somewhere I can look to get more information?

**Comment by joeferraro** [comment]
This is a prerelease, if you prefer not to install prereleases you should set your install_prereleases Package Control setting to false. If you'd like to test this prerelease (OSX and Linux only right now), you need to install and run mavensmate-app as the instructions indicate.

**Comment by pacman6642** [comment]
Thanks Joe, It just seemed that MM stopped working suddenly but I was in the middle of fire fighting for my client so I can't really remember what happened last night. Either way I got the prerelease working and I'm liking the app so far. Thanks for all the work you put into this!

**Comment by joeferraro** [comment]
cheers @pacman6642  :+1:
