### ISSUE TITLE
Could not contact local MavensMate server - v5.0.0-beta-2

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/MavensMate#484]
After the v5.0.0-beta.2 installed I'm frequently getting error messages when mavens mate loads

MavensMate Console
```
MavensMate for Sublime Text v5.0.0-beta.2

[ERROR]: Could not contact local MavensMate server, please ensure the MavensMate app is installed and running (https://github.com/joeferraro/mavensmate-app/releases). MavensMate will not run properly until resolved. If you are seeing this message unexpectedly, you may not realize that you are running a prerelease copy of MavensMate for Sublime Text. For more information please visit https://github.com/joeferraro/MavensMate/issues/483#issuecomment-130609793
```

i've added the sublime text console in a [gist](https://gist.github.com/ralphcallaway/fde1e15b1cc40df777b0)

working on getting a mavens mate log, somehow my user specific mavenmate settings file got overwritten with the default (will create a separate issue), will update the issue if i can capture a log

**Comment by joeferraro** [comment]
1. have you installed https://github.com/joeferraro/mavensmate-app/releases?
2. re: settings, see MavensMate > Settings > Settings Help

**Comment by ralphcallaway** [comment]
getting some logs now

from mmst.log
```
=============> Loading MavensMate for Sublime Text
/usr/local/bin/node
/usr/local/bin/npm
None
<urlopen error [Errno 61] Connection refused>
```

key details from the console
```
[MAVENSMATE]: reloading modules
reloading plugin MavensMate.util
plugins loaded
[MAVENSMATE]: =============> Loading MavensMate for Sublime Text
[MAVENSMATE]: /usr/local/bin/node
[MAVENSMATE]: /usr/local/bin/npm
[MAVENSMATE]: None
[MAVENSMATE]: <urlopen error [Errno 61] Connection refused>
```

**Comment by ralphcallaway** [comment]
@joeferraro have not installed any apps, thought the sublime text package handled that ... taking a look, i didn't get any package messages when the upgrade happened

noted regarding the settings, any idea why my old user settings were overwritten?

**Comment by ralphcallaway** [comment]
@joeferraro regarding the settings, are there no longer any project specific settings?

**Comment by ralphcallaway** [comment]
@joeferraro okay, i think i got this, i had a version of mavensmate.app installed, but looks like it was the old version (v0.38.7), went ahead and uninstalled the old version and replaced and the new version looks pretty different (couldn't find a way to tell the version from the new app)

restarting sublime text, looks like we're good, i'm getting a new error related to not finding a project, which makes sense for the setting

is the plugin supposed to be handling installing the new version of the app? if not, might help to add some details to the release notes about wiping and reinstalling ...

**Comment by joeferraro** [comment]
no the plugin will not download and install the new app, will add the wipe and reinstall instructions

**Comment by ralphcallaway** [comment]
@joeferraro working now, here's what i had to do
- remove the old version of the mavensmate.app
- install the new version of mavensmate.app from the release
- open the mavensmate.app and set my workspace
- open sublime text

things that are happening that seem tricky
- no save action in the mavensmate app when changing settings, the first time it didn't save my changes, but next time it did, hard to tell when that happens
- mavensmate app closes when i close the window, which then leads to an error when st 3 starts
- mavensmate app doesn't auto-start when sublime text loads, so i have to remember to open it everytime i start working on stuff
- new app loses the workspace settings I already had (as already covered in #485) from before the install

excited to be trying out the new version!!

**Comment by ralphcallaway** [comment]
@joeferraro closing this out now that i'm running

**Comment by darshanprasad** [comment]
@ralphcallaway You might already know this now, but just in case:

You can set the "mm_start_mavensmate_app" to true under MavensMate -> Settings -> User Plugin Settings if you would like to automatically start the MavensMate app when you open Sublime Text.

**Comment by Patlatus** [comment]
@darshanprasad Does this work for you?
This setting doesn't work for me, even though I corrected value inside
"mm_mavensmate_app_location" : {
		"osx": "/Applications/MavensMate.app",
		"windows": "C:\\Program Files\\MavensMate\\MavensMate.exe",
		"linux": ""
	}
from "windows": "C:\\Program Files\\MavensMate.exe", to "windows": "C:\\Program Files\\MavensMate\\MavensMate.exe",

**Comment by darshanprasad** [comment]
@Patlatus It's working on OSX for me.  I think you might need to use double forward-slash since the single slash is getting escaped.  Try:

"windows": "C:\\Program Files\\MavensMate\\mavensmate.exe"

Hope it helps.

**Comment by Patlatus** [comment]
Actually I already has double  forward-slash, this editor just displays it wrong...
