### ISSUE TITLE
Explore ways to improve exposure to updated settings management in v5

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/MavensMate#485]
When the v5.0.0-beta2 release was installed my user specific settings file was overwritten unexpectedly.

Also noticing that I can't find mavensmate under the package settings (sublime text menu->preferences->package settings). Thinking that may be due to an error loading the package (see #484)

**Comment by joeferraro** [comment]
settings have been overhauled in v5, see MavensMate > Settings > Settings Help

**Comment by ralphcallaway** [comment]
so that's pretty unexpected, although i get what you're going for, but I imagine you'll get more support requests initially because people don't understand why their settings disappeared, perhaps backing them up so they're available for later? this may already be happening, but seems like you'd want to include this in the package install message ...

**Comment by joeferraro** [comment]
definitely will be included in messages: https://github.com/joeferraro/MavensMate-SublimeText/blob/master/messages/5.0.0.txt

backing them up is a good call, need to think about how to surface them, thx

**Comment by joeferraro** [comment]
one thought: when `mavensmate-app` starts, look for existence of deprecated ST user settings. parse JSON and update global settings with deprecated user settings where possible.

**Comment by ralphcallaway** [comment]
hmm, guessing it didn't show because it's a beta, and with semver 5.0.0-beta2 < 5.0.0 (so installing 5.0.0-beta2 wouldn't show the 5.0.0.txt)

did some googling, but wasn't able to find much, not sure what if there is anything to do there, creating release messages for beta seems like extra cruft

parsing and copying seems like it could work, but that seems like it would just get you back to a place where user's have settings that are no longer valid

if the deprecated settings are just ignored, perhaps just leave everything as is, and then display a warning on load that the following settings are deprecated? i.e. in the mavensmate console, or in the app logs ...

**Comment by joeferraro** [comment]
> parsing and copying seems like it could work, but that seems like it would just get you back to a place where user's have settings that are no longer valid

i'd parse and copy only the ones that are valid in global settings https://github.com/joeferraro/MavensMate/blob/master/lib/mavensmate/config/default.js

**Comment by ralphcallaway** [comment]
@joeferraro makes sense, seems like that would reduce the amount of effort for setting it up (i.e. copying your workspace over)

i'd still consider just leaving the st 3 user settings alone since that's the expectation set by package control that those won't be touched. or if you do overwrite them store a backup of the old settings

**Comment by joeferraro** [comment]
the main argument against leaving them alone is it could cause confusion for the user given many of those settings are no longer managed within ST (so they see the settings in user settings, they attempt to manage them there but mavensmate is not respecting them)
