### ISSUE TITLE
Error deploying dashboard to production: 'NoneType' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by smohyee** [joeferraro/MavensMate#487]
I updated the subscriptions in my sandbox project to include dashboards and reports.

I changed the running user of one dashboard using the metadata file in MM, then attempted to deploy just the dashboard (not any underlying reports) to production. The dashboard and its reports already exist in production as well. 

The error received upon attempting to deploy to server: 'NoneType' object has no attribute '__getitem__'

Also tried deploying a dashboard along with its underlying reports, but recieved the same error. Any ideas?

EDIT for info:

Windows 7
Sublime 3 with MM v4.0.5

Steps to reproduce:
1. Subscribe to dashboard metadata for sandbox project
2. Deploy changed dashboard metadata file to production

MM UI console output :

<MavensMate.lib.server.lib.handler.Handler object at 0x00000000046BDB00>
[MAVENSMATE UI]: >>> handling request
[MAVENSMATE UI]: /generic/async
[MAVENSMATE UI]: >>> running an async operation
[MAVENSMATE UI]: olsap9m5
[MAVENSMATE UI]: {'ajax_args': ['--html'], 'rollback_on_error': True, 'project_location': 'C:\\Users\\i57380\\Documents\\MavensMate Workspace\\Verisk Health Sandbox', 'new_deployment_name': '', 'destinations': [{***personal deployment + desitination info omitted***}
[MAVENSMATE UI]: b'{"destinations":[{"username":"smohyee@.....","org_type":"production","id":"....."}],"check_only":false,"run_tests":false,"rollback_on_error":true,"package":{"Dashboard":["Jim_s_Dashboard","Jim_s_Dashboard/Enterprise_Account_Health_Dashboard"]},"project_name":"Verisk Health Sandbox","new_deployment_name":"","debug_categories":[{"category":"Apex_code","level":"DEBUG"}],"project_location":"C:\\\\Users\\\\i57380\\\\Documents\\\\MavensMate Workspace\\\\Verisk Health Sandbox","finish":false,"command":"deploy","ajax_args":["--html"]}'
[MAVENSMATE UI]: worker created
[MAVENSMATE UI]: >>> running thread arguments on next line!
[MAVENSMATE UI]: worker thread started
[MAVENSMATE UI]: -c SUBLIME_TEXT_3 --html -o deploy
[MAVENSMATE UI]: placed into queue
[MAVENSMATE UI]: {"id": "olsap9m5", "status": "pending"}
[MAVENSMATE UI]: >>> handling request
[MAVENSMATE UI]: /status?id=olsap9m5
[MAVENSMATE UI]: >>> status request
[MAVENSMATE UI]: >>> params: 
[MAVENSMATE UI]: {'id': 'olsap9m5'}
[MAVENSMATE UI]: >>> request id: olsap9m5
[MAVENSMATE UI]: >>> async queue: 
[MAVENSMATE UI]: {'olsap9m5': <BackgroundWorker(Thread-802, started 5848)>}
[MAVENSMATE UI]: found thread in request queue, checking if alive
[MAVENSMATE UI]: True
[MAVENSMATE UI]: >>> request is not ready
[MAVENSMATE UI]: {"id": "olsap9m5", "status": "pending"}
[MAVENSMATE UI]: mm command: 
[MAVENSMATE UI]: "C:\Users\i57380\AppData\Roaming\Sublime Text 3\Packages\User\MavensMate\mm\mm.exe" -c SUBLIME_TEXT_3 --html -o deploy
[MAVENSMATE UI]: >>> handling request
[MAVENSMATE UI]: /status?id=olsap9m5
[MAVENSMATE UI]: >>> status request
[MAVENSMATE UI]: >>> params: 
[MAVENSMATE UI]: {'id': 'olsap9m5'}
[MAVENSMATE UI]: >>> request id: olsap9m5
[MAVENSMATE UI]: >>> async queue: 
[MAVENSMATE UI]: {'olsap9m5': <BackgroundWorker(Thread-802, started 5848)>}
[MAVENSMATE UI]: found thread in request queue, checking if alive
[MAVENSMATE UI]: True
[MAVENSMATE UI]: >>> request is not ready
[MAVENSMATE UI]: {"id": "olsap9m5", "status": "pending"}
[MAVENSMATE UI]: >>> handling request
[MAVENSMATE UI]: /status?id=olsap9m5
[MAVENSMATE UI]: >>> status request
[MAVENSMATE UI]: >>> params: 
[MAVENSMATE UI]: {'id': 'olsap9m5'}
[MAVENSMATE UI]: >>> request id: olsap9m5
[MAVENSMATE UI]: >>> async queue: 
[MAVENSMATE UI]: {'olsap9m5': <BackgroundWorker(Thread-802, started 5848)>}
[MAVENSMATE UI]: found thread in request queue, checking if alive
[MAVENSMATE UI]: True
[MAVENSMATE UI]: >>> request is not ready
[MAVENSMATE UI]: {"id": "olsap9m5", "status": "pending"}
[MAVENSMATE UI]: >>> handling request
[MAVENSMATE UI]: /status?id=olsap9m5
[MAVENSMATE UI]: >>> status request
[MAVENSMATE UI]: >>> params: 
[MAVENSMATE UI]: {'id': 'olsap9m5'}
[MAVENSMATE UI]: >>> request id: olsap9m5
[MAVENSMATE UI]: >>> async queue: 
[MAVENSMATE UI]: {'olsap9m5': <BackgroundWorker(Thread-802, started 5848)>}
[MAVENSMATE UI]: found thread in request queue, checking if alive
[MAVENSMATE UI]: True
[MAVENSMATE UI]: >>> request is not ready
[MAVENSMATE UI]: {"id": "olsap9m5", "status": "pending"}
[MAVENSMATE UI]: >>> got a response body
[MAVENSMATE UI]: {"body": "'NoneType' object has no attribute '__getitem__'", "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 93, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.commands.deploy\", line 102, in execute\nTypeError: 'NoneType' object has no attribute '__getitem__'\n", "success": false}

[MAVENSMATE UI]: >>> handling request
[MAVENSMATE UI]: /status?id=olsap9m5
[MAVENSMATE UI]: >>> status request
[MAVENSMATE UI]: >>> params: 
[MAVENSMATE UI]: {'id': 'olsap9m5'}
[MAVENSMATE UI]: >>> request id: olsap9m5
[MAVENSMATE UI]: >>> async queue: 
[MAVENSMATE UI]: {'olsap9m5': <BackgroundWorker(Thread-802, stopped 5848)>}
[MAVENSMATE UI]: found thread in request queue, checking if alive
[MAVENSMATE UI]: False
[MAVENSMATE UI]: >>> request is ready, returning response

**Comment by joeferraro** [comment]
please update your issue according to these guidelines, thanks 
https://github.com/joeferraro/MavensMate/blob/master/CONTRIBUTING.md

**Comment by smohyee** [comment]
Ok, updated per the instructions. Existing issues with similar error messages seem to involve creating projects, not deploying them.

**Comment by jeniferbbc** [comment]
I had a similar behavior on one of my projects and just discovered the pattern which may or may not help you.  If I move a report previously deployed to a different folder and try to deploy, it fails.  For example, Report A is in the Custom Folder A in my target org (Org B) and Source org (Org B). I move it to Custom Folder B in my source org (Org A), then try to deploy that change to Org B,  it fails.
