### ISSUE TITLE
Unable to deploy only a single class??

### ISSUE THREAD

**Issue by skiesnpies** [joeferraro/MavensMate#489]
![mavensmate](https://cloud.githubusercontent.com/assets/1230577/9379598/632ef622-4722-11e5-9ae2-b89e2115007f.png)

Hi, am unable suddenly to deploy single classes using mavens as the twisty to select classes is missing. Also when I search for a class, none are returned - it seems as though I can deploy ALL classes or none. This is only happening (currently) on certain orgs. Any thoughts?

**Comment by joeferraro** [comment]
Please update your issue according to the guidelines https://github.com/joeferraro/MavensMate/blob/master/CONTRIBUTING.md

**Comment by skiesnpies** [comment]
Sorry about missing off the version details etc. 
I am on OS X 10.10.4 , mavens version V4.0.5 and sublime 3083. 
To re-produce the issue, I am clicking Mavensmate/Deploy to Server and when the window pops up, I am clicking the Metadata tab. The window show refreshes and after a few seconds I can see all of the deployment types / classes / Apexpages etc, all of them are expandable but not the classes section.

**Comment by skiesnpies** [comment]
is there anything I can do to help debug the issue?

**Comment by hussainDCB** [comment]
I am facing same issue, can you please help me how we can deploy single component which is in the local.
