### ISSUE TITLE
[Errno 54] Connection reset by peer

### ISSUE THREAD

**Issue by vyuvalv** [joeferraro/MavensMate#493]
Does anyone know how to deal with this kind of Error. I cannot update any project to Salesforce server from Mavensmate.

I have tried the following on mavensmate but each one give me same error :

    Metadata > Update Project Metadata Index
    Utilities > Refresh Apex Symbols Tables for this project
    Utilities > Reset Metadata container

I really don't understand how did that happened everything was working fine and suddenly it stopped working... Any help would be appreciated.

**Comment by nirsharonclick** [comment]
Same here

**Comment by fishdag** [comment]
Also encountered the same problem.
I'm using MavensMate for Sublime Text v4.0.5, on Sublime Text 3.

**Comment by volubilis** [comment]
Same here about an hour ago. No particular reason...

**Comment by motiko** [comment]
It happens to me from an Israeli IP address. 
Using VPN solves the problem. 
Salesforce please..

**Comment by volubilis** [comment]
I used a vpn from the united states and it did not work. I also installe Force.com IDE and it would not let me access the organisation data. everything else on salesforce works fine

**Comment by amitZil** [comment]
Same issue - "Connection reset by peer"

Please assist

**Comment by joeferraro** [comment]
Guys nothing changed on our side, this is likely a Salesforce issue. Until it's proven this is a MavensMate issue, will close.

**Comment by ulaskutuk** [comment]
same

**Comment by motiko** [comment]
It does seems like a Salesforce related issue.
If someone can advance further and debug this  please post back to : http://salesforce.stackexchange.com/questions/89076/mavensmate-errno-54-connection-reset-by-peer
@volubilis did you try to deploy with Force.com plugin and got the same error ? Can you please open a ticket to  Salesforce support if this is the case.

**Comment by ulaskutuk** [comment]
Really dont understand, how can you close the issue ? Apparently it is not working, I can understand that nothing changed in mavensmate side but still it is NOT working.

**Comment by joeferraro** [comment]
@ulaskutuk did you see this comment? this is evidence that this is not a MavensMate issue.

>  I also installed Force.com IDE and it would not let me access the organisation data.

**Comment by volubilis** [comment]
Actually I did open a case they said they have sent this to technical and will get back to me. No luck with Eclipse IDE... "can not fetch organisation detail". I am now fiddling with atom...I was able to get my organisation data... which is promising by "Can't alter metadata in an active org" when I compile so I am  strugling with where I can set mm_compile_with_tooling_api to false...

**Comment by joeferraro** [comment]
@volubilis are you trying to compile code directly in production?

**Comment by volubilis** [comment]
yes

**Comment by joeferraro** [comment]
FYI: the tooling api does not support that functionality and generally it is not a best practice

**Comment by volubilis** [comment]
Thanks Joe. I do understand and appreciate your advice.

**Comment by volubilis** [comment]
My previous answer was too hasty and I realise that I probably did not get you. Actually I do not necessarily want to compile in a working environment, I just want to deploy directly to a production environment. Working in a sandbox is just a pain. Setting up a full operational copy in a sandbox takes too much time and deployment from sandbox to production is just killing in terms of time...any advice on how to be more efficient is welcome.

**Comment by ulaskutuk** [comment]
Anyone who is having this issue, I had a call with SF and got resolve this. Try to use custom url instead of saying developer or production.

**Comment by vyuvalv** [comment]
@ulaskutuk you are right!!!! - Custom URL did solve my problem !!!!  thanks a lot...

**Comment by ulaskutuk** [comment]
@vyuvalv no problem. I believe instead of closing issue with saying "that this is not a MavensMate issue". We should be trying to help people ;) I'm glad it worked for you buddy

**Comment by kimonniez** [comment]
vyuvalv, can you give a custom url? Thx in advance

**Comment by joeferraro** [comment]
do you guys have "My Domain" enabled in your org? If so, if your login policy prevents logging in at login.salesforce.com, this could be your issue.

![mavensmate-dev-ed___salesforce_com_-_developer_edition](https://cloud.githubusercontent.com/assets/54157/9466731/fbb22640-4b04-11e5-938a-3300936169bc.png)

**Comment by vyuvalv** [comment]
@kimonniez you should grab it from your Org Instance.
login and just copy paste the following : 
https://XXX.salesforce.com/

@joeferraro  in my case I "MyDomain" is NOT enabled. - so this is not the reason.

**Comment by joeferraro** [comment]
@vyuvalv good info, thx

**Comment by kimonniez** [comment]
Thx for all!!!
