### ISSUE TITLE
catch expired password exception when adding project

### ISSUE THREAD

**Issue by joeferraro** [joeferraro/MavensMate#494]
Error: Could not add project: INVALID_OPERATION_WITH_EXPIRED_PASSWORD: The users password has expired, you must call SetPassword before attempting any other API operations

**Comment by zokito** [comment]
any workarounds except for creating a new project?

**Comment by joeferraro** [comment]
What version are you running?

**Comment by zokito** [comment]
v0.0.1-beta7
