### ISSUE TITLE
Code Coverage not accurate 

### ISSUE THREAD

**Issue by joeferraro** [joeferraro/MavensMate#497]
courtest of @yippie

Mavensmate-app v0.0.1-beta6.

It appears that the code coverage shown after running unit tests in the unit test UI is not the total coverage but instead, the coverage from one of the test methods that covered the class. I also found, that the line coverage highlighting and the % can come from different test methods.

To verify, create a class with two methods that do something (need at least one line of real code in them). Then create a test class for that class with two unit test methods, one for each of the two methods in the first class. When you run the unit tests and click on view coverage it will report 50-60% coverage and only highlight one of the methods in the class as being covered.

**Comment by joeferraro** [comment]
@ralphcallaway @yippie @steals any chance you guys could help me reproduce this issue in an easy way?

**Comment by yippie** [comment]
@joeferraro Do you need logs or a step by step?  The second paragraph I did to double check it and was able to verify, at least on that one org.

**Comment by joeferraro** [comment]
if you could set up a dev org and replicate this issue in its most basic form, it'd be super helpful (and include logs)

**Comment by yippie** [comment]
@joeferraro I just sent you an email with some logs and screenshots.

**Comment by joeferraro** [comment]
@yippie :+1: :+1:
