### ISSUE TITLE
Operation failed (after compile) - Loads of XML and JSON

### ISSUE THREAD

**Issue by LKozakewycz** [joeferraro/MavensMate#499]
I seem to be getting a lot of this at the moment after I compile a file:

```
Result: [OPERATION FAILED]: ERROR:suds.client:<?xml version="1.0" encoding="UTF-8"?>

<SOAP-ENV:Envelope xmlns:ns0="urn:partner.soap.sforce.com" xmlns:ns1="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="urn:partner.soap.sforce.com" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">


   <SOAP-ENV:Header>
      <tns:SessionHeader>
         <tns:sessionId>******************************************</tns:sessionId>
      </tns:SessionHeader>
   </SOAP-ENV:Header>
   <ns1:Body>
      <ns0:getUserInfo/>
   </ns1:Body>
</SOAP-ENV:Envelope>


{"checkOnly": false, "completedDate": "2015-08-27T11:21:02.000Z", "createdBy": "**************", "createdByName": "**************", "createdDate": "2015-08-27T11:20:58.000Z", "details": {"componentSuccesses": [{"changed": true, "componentType": null, "created": false, "createdDate": "2015-08-27T11:21:00.000Z", "deleted": false, "fileName": "unpackaged/package.xml", "fullName": "package.xml", "success": true}, {"changed": true, "componentType": "ApexComponent", "created": false, "createdDate": "2015-08-27T11:21:00.000Z", "deleted": false, "fileName": "unpackaged/components/**************.component", "fullName": "**************", "id": "**************", "success": true}], "runTestResult": {"numFailures": "0", "numTestsRun": "0", "totalTime": "0.0"}}, "done": true, "id": "**************", "ignoreWarnings": false, "lastModifiedDate": "2015-08-27T11:21:02.000Z", "numberComponentErrors": "0", "numberComponentsDeployed": "1", "numberComponentsTotal": "1", "numberTestErrors": "0", "numberTestsCompleted": "0", "numberTestsTotal": "0", "rollbackOnError": true, "runTestsEnabled": true, "startDate": "2015-08-27T11:20:59.000Z", "status": "Succeeded", "success": true}
```

Windows 8.1 (64 bit)
& Windows 10 (64 bit)
MM 4.0.5
ST 3083

**Comment by ralphcallaway** [comment]
@LKozakewycz can you please update your issue according to the guidelines? thanks! https://github.com/joeferraro/MavensMate/blob/master/CONTRIBUTING.md

**Comment by LKozakewycz** [comment]
@ralphcallaway - I'm pretty sure my post was mostly compliant with your guidelines - never had an issue with that format in my previous issues.

I would like to add to this issue though:

This error occurs after every first compile with the current session (i.e. when I first use Mavensmate for the day and when I haven't used Mavensmate for a couple of hours).

The compile actually works, but I am given an error in the form of the log stated in the original post.

**Comment by ralphcallaway** [comment]
@LKozakewycz your post is definitely better than a lot we get, main thing i'm looking for is the mavensmate logs which will show what was going on when that error happened, for v6 and earlier see https://mavensmate.com/Plugins/Sublime_Text/Plugin_Logging

you're on a bit of an older version, did you install with package control? curious if this is issue is still occurring with v6 ...
