### ISSUE TITLE
Shortcut for implementing methods of an Interface

### ISSUE THREAD

**Issue by aleramesh** [joeferraro/MavensMate#504]
The below example is for Java:
TestInterface.Java:

    public interface TestInterface {
    	public void methodOne();
    }

In Eclipse for Java, If I want to implement methods of the Interface, it would show up all the methods from the Interface and then I can choose whichever I want.. Below screenshot.

![implement_interface](https://cloud.githubusercontent.com/assets/11079913/9550225/1440235e-4d78-11e5-830f-99879ebc03f2.png)

Is there any such thing for Apex, Without opening the interface and copying the method name..Any shortcut for this kind of scenario?

**Comment by ralphcallaway** [comment]
@aleramesh somewhat, there are the apex class templates, for example the batch class template has all the methods filled out for that interface

if you have a specific set of interfaces that you re-use you can add to the templates

nothing available now that would populate the methods based on an ad-hoc interface declaration

**Comment by aleramesh** [comment]
Excellent! 

The reason we are looking for this feature is, We are implementing a framework and we need to implement/extend few Interfaces/classes frequently.

I followed your approach and added one of our class to the template locally and it is working fabulous.

Thanks so much for the suggestion.

**Comment by ralphcallaway** [comment]
@aleramesh closing this out since it sounds like you've got what you needed, please re-open if that's not the case
