### ISSUE TITLE
Using Beta MM, Lightning component won't save to server

### ISSUE THREAD

**Issue by tglaess** [joeferraro/MavensMate#505]
Using the new beta MM and Sublime, I was able to create a Lightning Bundle. When I made changes to the component and saved the file however, it only saved to my local drive. It did not deploy to SF at all. I've had no issues with VF or Apex files.

**Comment by joeferraro** [comment]
Please setup logging in your global settings and paste any relevant logs

**Comment by tglaess** [comment]
I actually just got it to work. ".cmp" was not in the list of extensions that MM was automatically compiling. Adding that fixed the issue.

**Comment by joeferraro** [comment]
@tglaess cheers. i've added to the default extensions for the ST plugin and to global settings

**Comment by joeferraro** [comment]
closing as this has been delivered in a recent ST beta
