### ISSUE TITLE
Implement capability of running specific test methods 

### ISSUE THREAD

**Issue by joeferraro** [joeferraro/MavensMate#506]
/runTestsAsynchronous/
```
[{
"classId" : "<classId 1>",
"testMethods" : ["testMethod1","testMethod2","testMethod3"]
},{
"classId" : "<classId 2>",
"testMethods" : ["testMethod1","testMethod2"]
}]; 
```

**Comment by joeferraro** [comment]
https://github.com/joeferraro/MavensMate/commit/199f66bbe6e719457c484441fb611e2255c16afa closes

**Comment by joseph-ortiz** [comment]
Where do I pass in the array of specific methods to test in your comment at the top?

I tried searching the documentation here but didn't see details on how to execute this.

https://mavensmate.com/Plugins/Sublime_Text/Apex_Testing

**Comment by samuel012** [comment]
Hello @joseph-ortiz , although this comment is almost 8 months delayed, I hope this still helps you, or the others also looking for answers.

How I did it via UI:

1. open the test class
1. In sublime, press ctrl+shift+p
1. type "apex unit"
1. select "run apex unit test methods for this class
![image](https://cloud.githubusercontent.com/assets/5159877/18491248/107e10bc-7a38-11e6-88fa-cd0db046fe52.png)
1. enter comma-separated method names you want to run in the test class you opened
![image](https://cloud.githubusercontent.com/assets/5159877/18491301/4cf0aea6-7a38-11e6-9edb-d0d8f21bf7d2.png)
1. press enter
1. results will appear in the mavensmate panel
![image](https://cloud.githubusercontent.com/assets/5159877/18491459/15c3fd38-7a39-11e6-81a1-b3967ea16592.png)




Cheers.

**Comment by joeferraro** [comment]
cheers for the example @samuel012
