### ISSUE TITLE
manual clone of mm executable times out

### ISSUE THREAD

**Issue by CloudHugger** [joeferraro/MavensMate#509]
I have been trying to get mm executable installed to mavensmate for past few hours without success. No proxy to worry about, and using Win 7 OS. After many failed package control install fails due to 'timing out' I finally tried via the option of git cloning i.e. 

cd /path/to/sublime text/packages/directory
git clone https://github.com/joeferraro/MavensMate-SublimeText.git 'MavensMate'

This is consistently returning error 'Failed to connect to github.com port 443: Timed out' . I can download the zipped git but dont know how to deploy it via that mechanism, as previous downloads and installs to a mavensmate/mm directory also resulted in 'could not find the mm executable' error despite putting zip contents in an mm folder everywhere I could think of.  Any suggestions on why this git clone issue would happen ?

**Comment by joeferraro** [comment]
this is likely a github network issue

**Comment by CloudHugger** [comment]
Thanks @Joe. You are correct. Thanks for your feedback.
