### ISSUE TITLE
mm_use_browser_as_ui not respected

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/MavensMate#510]
### Version Info
- mavens mate app: v5.0.0-beta9 ?? (not 100% sure since I don't see any way to find the version i have downloaded, but i think that's the most recent one i downloaded
- st 3: v5.0.0-beta3 (from package control list packages, the loading version is beta2)

### Steps to Reproduce
1. open mavensmate app
1. set mm_use_browser_as_ui to true in mavens mate app
1. for good measure close st3 and mavensmate app, then reopen both
1. run create new apex class command from st3 command palette

###  Expected Outcome
- Opens mavensmate ui in browser

### Actual Outcome
- Opens in Mavensmate app

### Discussion
Not sure if this was intentional, if so should probably drop that from the list of settings. Was trying to troubleshoot new metadata not working and thought the browser might have some more error messages I could see.

**Comment by joeferraro** [comment]
FYI `mm_use_browser_as_ui` is left around intentionally for rapidly testing during development

**Comment by ralphcallaway** [comment]
@joeferraro got it, will use the web kit inspector command in the future (pretty sure you'd documented that already, i just forgot about it)

**Comment by jonathanwiesel** [comment]
I don't see why this cannot be respected regardless of it's for development or not. If a user would prefer to use the browser instead the app why not let him?

**Comment by ralphcallaway** [comment]
@joeferraro i'd second re-opening this and making this a true setting, now that the latest beta uses oauth it'd be a big boon to use the browser instead of electron so i can use password managers and also so my browser session info is available to mavensmate

**Comment by jonathanwiesel** [comment]
+1 on the password manager communication. In fact in the issue #914 that is what I'm trying to accomplish.
