### ISSUE TITLE
No logging for new metadata operation

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/MavensMate#511]
### Version Info
- app: v5.0.0-beta9 (could be wrong no where to find this)
- st3: v5.0.0-beta3 (from package control list packages)

### Steps to Reproduce 
- open st3 and run create new apex class command from command palette
- select default template and put in a name

### Expected Outcome
- see some logs for the new metadata command

### Actual Outcome
- see logs in mmst.log for initiating the new metadata command ui, but nothing for the command itself

**Comment by ralphcallaway** [comment]
this seems to be the case for all core level logging, all i get is the st3 console logs and the mmst.log folder

**Comment by joeferraro** [comment]
@ralphcallaway can you help me understand what the issue is here? Do you have logging configured in mavensmate-app?

**Comment by ralphcallaway** [comment]
@joeferraro i believe so, but it's quite possible i don't have it setup correctly, given i get a mmst.log i'm assuming that it's at least partially configured correctly

i have `mm_log_location` set in the mavensmate app and in the st3 user settings, both are pointing to the same folder and i've confirmed that the directory is valid by copying and pasting into a bash terminal `cd` command

i have `mm_log_level` set to DEBUG in both the mavensmate app and in the st3 user settings

seems like that would be sufficient to generate logs, but i'll i'm getting is mmst.log which matches the output of the sublime text console, sure this is user error, but not sure what

**Comment by zokito** [comment]
I have the same situation but Sublime plugin identifies itself a v5.0.0-beta2 although i just checked out a v5.0.0-beta3 tag. 

No mm logs are being generated.

**Comment by joeferraro** [comment]
can you guys send screenshots of your mavensmate-app settings ui with debug configured as well as the contents of your ~/.mavensmate-config.json file? thx for the help

**Comment by zokito** [comment]
For my case it started working after couple of restarts App + Sublime with no config changes.

**Comment by ralphcallaway** [comment]
<img width="700" alt="screenshot 2015-09-08 11 28 56" src="https://cloud.githubusercontent.com/assets/841021/9742401/22e50ee4-561d-11e5-88da-f9bf28647a96.png">

here's my json, not sure if the extra quotation marks are mucking things up, trying to remove those ...

```
{
  "mm_workspace": [
    "/Users/ralphcallaway/Documents/eclipse 3.7"
  ],
  "mm_api_version": "33.0",
  "mm_compile_check_conflicts": true,
  "mm_timeout": 600,
  "mm_default_subscription": [
    "ApexClass",
    "ApexComponent",
    "ApexPage",
    "ApexTrigger",
    "StaticResource"
  ],
  "mm_ignore_managed_metadata": true,
  "mm_use_keyring": true,
  "mm_compile_with_tooling_api": true,
  "mm_subl_location": {
    "windows": "C:\\Program Files\\Sublime Text 3\\sublime_text.exe",
    "linux": "/usr/bin/subl",
    "osx": "/Applications/Sublime Text 3.app/Contents/SharedSupport/bin/subl"
  },
  "mm_atom_exec_path": {
    "windows": "C:\\Program Files\\Atom\\Atom.exe",
    "linux": "/usr/bin/subl",
    "osx": "usr/local/bin/atom"
  },
  "mm_log_location": "\"/Users/ralphcallaway/Documents/eclipse 3.7/mmlogs\"",
  "mm_log_level": "DEBUG",
  "mm_play_sounds": true,
  "mm_template_location": "remote",
  "mm_template_source": "joeferraro/MavensMate-Templates/master",
  "mm_apex_file_extensions": [
    ".page",
    ".component",
    ".cls",
    ".object",
    ".trigger",
    ".layout",
    ".resource",
    ".remoteSite",
    ".labels",
    ".app",
    ".dashboard",
    ".permissionset",
    ".workflow",
    ".email",
    ".profile",
    ".scf",
    ".queue",
    ".reportType",
    ".report",
    ".weblink",
    ".tab",
    ".letter",
    ".role",
    ".homePageComponent",
    ".homePageLayout",
    ".objectTranslation",
    ".flow",
    ".datacategorygroup",
    ".snapshot",
    ".site",
    ".sharingRules",
    ".settings",
    ".callCenter",
    ".community",
    ".authProvider",
    ".customApplicationComponent",
    ".quickAction",
    ".approvalProcess",
    ".html"
  ],
  "mm_http_proxy": "",
  "mm_https_proxy": "",
  "mm_mavensmate_app_path": {
    "windows": "C:\\Program Files\\MavensMate\\mavensmate.exe",
    "linux": "/usr/bin/mavensmate-app/MavensMate",
    "osx": "/Applications/MavensMate.app"
  },
  "mm_purge_on_delete": true,
  "mm_use_browser_as_ui": true
}

**Comment by ralphcallaway** [comment]
@joeferraro removing the extra quotation marks in the json config file got the logging working, i'm good now, but leaving open in case you want to flag this for adding an exception when the log location is invalid like the subl location ...

**Comment by joeferraro** [comment]
yep, i've run into the wrapping quotes issue myself. still trying to figure out the best way to catch and handle

**Comment by ralphcallaway** [comment]
@joeferraro was thinking about that a bit, since a lot of these config values don't really cause much headaches if they're bad, but some do

maybe a settings health check? would be non-blocking, could be pretty rough, and could be a pretty helpful tool when looking through github tickets

another good spot would be in the st3 console, but seems like we could go overboard if we did the check ever time things launched

other thought would be to have it done on load of the mavensmate app, and just display a message like the 'update available' alert, that just prints out the invalid settings ...

anyway, hoping i can get a break from project work soon so i can dig back in on this stuff, contributing is way better than beta testing

**Comment by joeferraro** [comment]
@ralphcallaway I think you're on the right track. let's noodle on it a bit, then we can open up a separate enhancement ticket. for now, i'm just catching the extra quotes and throwing an error on the screen
