### ISSUE TITLE
New Apex Class Just Spinning Indefinitely 

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/MavensMate#512]
### Version Info
- app: v5.0.0-beta9 (i think)
- st3: v5.0.0-beta3

### Steps to Reproduce 
1. run new apex class command from st3 command palette
1. select default template and enter apex class name
1. click create metadata

### Expected Outcome
New apex class created and opened in sublime text

### Actual Outcome
Creating new metadata loading spinner comes up, but never completes. Apex class is created in org.

### Discussion
Seems like I've got something screwed up locally, but i'm not getting logs out of the mmst.log (see #511 ). Other operations like refresh metadata are working fine. As a workaround I just check the class was created in the org then clean/refresh the project.

Tried doing this in the web browser to see if we had some js errors that would provide some guidance but blocked by #510 

Given the logs don't seem to show anything for core operations I'm having trouble getting useful diagnostic info for this ...

**Comment by ralphcallaway** [comment]
so a little confusingly it appears the apex class was created during one of these runs, so at least it got fired off, not sure if something timed out or what ... also seems like we could have hit an error due to a duplicate class name that just isn't being surfaced ...

**Comment by joeferraro** [comment]
What is the value of your "mm_subl_location" global setting, out of curiosity?

**Comment by ralphcallaway** [comment]
think that might be it ..

```
{
  "windows": "C:\\Program Files\\Sublime Text 3\\sublime_text.exe",
  "linux": "/usr/bin/subl",
  "osx": "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl"
}
```

at least on my machine it needs to be "/Applications/Sublime Text 3.app/Contents/SharedSupport/bin/subl"

seems like it's working now (did require restarting the app and st3), thanks for looking at this!

**Comment by joeferraro** [comment]
Cheers @ralphcallaway. regardless, we need to throw that exception if the core attempts to open the newly created metadata and is unable to due to an invalid "mm_subl_location" value. will attempt to reproduce on my side and patch
