### ISSUE TITLE
mm_default_subscription in settings is ignored

### ISSUE THREAD

**Issue by CloudHugger** [joeferraro/MavensMate#516]
Hi there,
Despite changing user and default settings files, if I extend the mm_default_subscription to include additional metadata ie. PermissionSet, Settings or CustomLabels at project creation these are totally ignored and the standard defaults are all we get and each project then needs to be manually extended. Anyone else found the same ?

**Comment by joeferraro** [comment]
@CloudHugger please update your issue according to the guidelines: https://github.com/joeferraro/MavensMate/blob/master/CONTRIBUTING.md

thx!

**Comment by CloudHugger** [comment]
I'll close it out. Thanks.
