### ISSUE TITLE
Mavensmate Test Runner UI - Test Results tab not shown in IE

### ISSUE THREAD

**Issue by Aging-Hippie** [joeferraro/MavensMate#517]
Sublime Text 3
Mavensmate 4.0.5
Internet Explorer 11

Select Mavensmate|Unit Testing|Open Apex Test Runner UI
(Browser window opens with warning)
Click "Allow Blocked Content"
Run any test
Test Results tab does not appear

For reasons not connected to Apex development, I need to keep MSIE as the default browser if at all possible.  Is there any way to get Mavensmate to use a specific browser instead of the default, or are there settings that will enable the test runner UI to work properly?

**Comment by joeferraro** [comment]
we will not be fixing this issue as the upcoming version is no longer dependent on the user's local browser. if you're interested in installing the beta, please head over to: https://github.com/joeferraro/MavensMate-SublimeText#install
