### ISSUE TITLE
How to setup dev version of node with electron app

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/MavensMate#518]
Now that settings are managed in the new electron app, it's not clear how to tie things to a development build of the core api. 

Used to be you'd set `mm_developer_mode` to `true` and then set the python and mm.py locations, is there an analog for the node version?

We'd been approximating this by launching the mm server on a different port and then switching st3 over to that port ... but figure there has to be a more direct route.

fyi @nsjonas

**Comment by joeferraro** [comment]
@ralphcallaway when I'm developing the core, I `cd` to the root of `mavensmate` and run `bin/server --verbose` ... this will typically run on 8000 and I can load the app in my browser at `http://localhost:8000/app/home/index'

I also set `mm_app_server_port` in sublime to 8000

if you're specifically working on the `mavensmate-app` project (which is mostly the chrome (wrapper) of the mavensmate UIs found in THIS project), then I cd to `mavensmate-app/app` and run `electron .` which will run the app locally on port 56248. 

More than likely, the bulk of your dev will be on the source code contained within this project.

Make sense?

**Comment by ChuckJonas** [comment]
@joeferraro so I think I'm pretty close to getting the "core" setup... but running into a key chain issue any time I try to issue a command.  Any ideas?
```
error:   Could not get project settings -->System keychain is not support and there is no "password" property in project config/.settings file.
error:   Could not initiate existing Project instance: System keychain is not support and there is no "password" property in project config/.settings file.
error:   Could not add project: System keychain is not support and there is no "password" property in project config/.settings file. -> Error: System keychain is not support and there is no "password" property in project config/.settings file.
    at /Users/charles/code/mmTesting/node_modules/mavensmate/lib/mavensmate/project.js:1328:18
    at tryCatch2 (/Users/charles/code/mmTesting/node_modules/mavensmate/node_modules/bluebird/js/main/util.js:53:21)
    at Promise._resolveFromResolver (/Users/charles/code/mmTesting/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:544:13)
    at new Promise (/Users/charles/code/mmTesting/node_modules/mavensmate/node_modules/bluebird/js/main/promise.js:82:37)
    at Project._getPassword (/Users/charles/code/mmTesting/node_modules/mavensmate/lib/mavensmate/project.js:1314:10)
    at /Users/charles/code/mmTesting/node_modules/mavensmate/lib/mavensmate/project.js:715:14
    at /Users/charles/code/mmTesting/node_modules/mavensmate/node_modules/fs-extra-promise/node_modules/fs-extra/node_modules/jsonfile/index.js:19:5
    at fs.js:258:14
    at /Users/charles/code/mmTesting/node_modules/mavensmate/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:42:10
    at Object.oncomplete (fs.js:97:15)
```

**Comment by joeferraro** [comment]
it's likely that you're having trouble installing `keytar` on your system. what is the output when you run `npm install mavensmate`?

**Comment by ChuckJonas** [comment]
Yea... looks I'm getting tons of errors (not sure how I missed that before).   It's probably an problem with my configuration but I opened an [issue on the keytar github](https://github.com/atom/node-keytar/issues/31) to see if they can offer any insight.

**Comment by ChuckJonas** [comment]
@joeferraro finally got it running. I had updated node to 4.x but had an old install higher in my PATH and somehow didn't notice...  Anyways, excited to start mucking around
