### ISSUE TITLE
v5.0.0-beta.5 | MavensMate.app | New Project | [Open in Sublime] - Does not open in sublime

### ISSUE THREAD

**Issue by pfeilbr** [joeferraro/MavensMate#520]
### Steps to Reproduce

1. MavensMate.app (Electron) | New Project
2. Fill in details
3. Select metadata
4. Project created successfully
5. Click [Open in Sublime] button and nothing happens

### Details

![](http://static-content-01.s3-website-us-east-1.amazonaws.com//Screenshot_9_18_15__10_36_AM_1BAC5920.png)

[response.json with stack trace](https://gist.github.com/pfeilbr/115a7f4abc2507a6eaa0)

Context

![](http://static-content-01.s3-website-us-east-1.amazonaws.com//open-project_js_1BAC5BDE.png)

**Comment by joeferraro** [comment]
@pfeilbr lovely bug report, i thank you! yes, I'm actually aware of this issue, just forgot to post as an open issue. This will be fixed in the upcoming release.

**Comment by pfeilbr** [comment]
@joeferraro great to hear.  Really enjoying the new version.  Thanks!
