### ISSUE TITLE
407 proxy authentication required error

### ISSUE THREAD

**Issue by KoenVM** [joeferraro/MavensMate#523]
The company where we are working at changed their proxy server and since then, we are unable to work with mavensmate anymore.
We always get the 407 proxy authentication error.

We checked the proxy settings "mm_http_proxy" and "mm_https_proxy" and tried with simply putting the address and port of the proxy there like the examples say as well as putting the username and password there.

From our internal IT/network support, we got the following reply:

"As explained, the new proxies will not allow clear text authentication for obvious security reason.
if your plugin does not support Kerberos or NTLM authentication, it will not work."

So, question is, does mavensmate support either kerberos or ntlm proxy authentication?
If yes, how does it need to be configured?

Any help would be greatly appreciated, we are a big fan of manvesmate and don't want to move to a different tool.

**Comment by joeferraro** [comment]
@KoenVM i'm pretty sure this is resolved in mavensmate-app, can you confirm?

**Comment by KoenVM** [comment]
@joeferraro not entirely sure... As even with the mavensmate-app , I still needed to use the CNTLM app to handle proxy authentication. If I remember it well from the research I did on this issue, the cause here was probably the underlying urllib library from python that didn't support this type of authentication.
But in any case, for me the workaround with the CNTLM app is workable.
Here is a good tutorial on how to setup CNTLM:
http://stormpoopersmith.com/2012/03/20/using-applications-behind-a-corporate-proxy/

**Comment by joeferraro** [comment]
tracking here: https://github.com/joeferraro/MavensMate-app/issues/24#issuecomment-144939874
