### ISSUE TITLE
Getting git error few times a day... Help?

### ISSUE THREAD

**Issue by OlegForce** [joeferraro/MavensMate#526]
<img width="416" alt="screenshot 2015-09-28 15 37 51" src="https://cloud.githubusercontent.com/assets/2013992/10146460/fd1c6862-65f6-11e5-9734-74531962ede6.png">

**Comment by OlegForce** [comment]
This just pops up a few times a day while I am working on my code.

**Comment by joeferraro** [comment]
hm, i think this is a package control setting, i suggest you submit that issue to their repo https://github.com/wbond/package_control

closing for now. feel free to re-open if it becomes clear this is a mavensmate issue

**Comment by OlegForce** [comment]
thanks Joe. It's not happening in MM5 any longer, so we are good. :)
