### ISSUE TITLE
Mavensmate not able to connect behind corporate proxy

### ISSUE THREAD

**Issue by vineethunique88** [joeferraro/MavensMate#527]
Following is the log -

reloading /Users/vmadamsh/Documents/mavens_workspace/MDTDEV/src/classes/AddCampaignRequestData.cls
[MAVENSMATE] failed to send community activity
reloading Packages/User/mavensmate.sublime-settings
[MAVENSMATE]: Calling mm_interface
[MAVENSMATE]: OPERATION: refresh
[MAVENSMATE]: {'params': {'files': ['/Users/vmadamsh/Documents/mavens_workspace/MDTDEV/src/classes/AddCampaignRequestData.cls']}, 'context': <MavensMate.mavensmate.RefreshActiveFileCommand object at 0x104007bd0>}
[MAVENSMATE]: mm command: 
[MAVENSMATE]: '/Users/vmadamsh/Library/Application Support/Sublime Text 3/Packages/User/MavensMate/mm/mm' -c SUBLIME_TEXT_3 -o refresh
[MAVENSMATE]: {"workspace": "/Users/vmadamsh/Documents/mavens_workspace", "files": ["/Users/vmadamsh/Documents/mavens_workspace/MDTDEV/src/classes/AddCampaignRequestData.cls"], "project_name": "MDTDEV"}
[MAVENSMATE]: response from mm: {"body": "No internet connection", "stack_trace": "Traceback (most recent call last):\n  File \"mm.request\", line 69, in execute\n  File \"mm.request\", line 61, in __setup_connection\n  File \"mm.project\", line 75, in __init__\n  File \"mm.sfdc_client\", line 86, in __init__\n  File \"mm.sforce.base\", line 590, in getUserInfo\n  File \"suds.client\", line 542, in __call__\n  File \"suds.client\", line 602, in invoke\n  File \"suds.client\", line 637, in send\n  File \"suds.transport.http\", line 77, in send\n  File \"suds.transport.http\", line 118, in u2open\n  File \"urllib2\", line 400, in open\n  File \"urllib2\", line 418, in _open\n  File \"urllib2\", line 378, in _call_chain\n  File \"urllib2\", line 1215, in https_open\n  File \"urllib2\", line 1177, in do_open\nURLError: <urlopen error [Errno 8] nodename nor servname provided, or not known>\n", "success": false}

Have been trying to fix this for a few days now, trying all the combinations with username and without but nothing seems to work. Here are my proxy config

"mm_http_proxy" : "http:\/\/vdesh:Vintest8#@proxy-phoenix.rctc.com:8080",

"mm_https_proxy" : "http:\/\/vdesh:Vintest8#@proxy-phoenix.rctc.com:8080",

Always gives me the issue "No Internet Connection"

**Comment by schmimae** [comment]
I am receiving a similar error when using the new MavensMate standalone app. Upon starting, I receive two error messages:

[Window Title]
Error

[Main Instruction]
A JavaScript error occured in the main process

[Content]
Uncaught Exception:
Error: connect ECONNREFUSED 192.30.252.126:443
    at Object.exports._errnoException (util.js:814:11)
    at exports._exceptionWithHostPort (util.js:837:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1044:14)

[OK]

[Window Title]
Error

[Main Instruction]
A JavaScript error occured in the main process

[Content]
Uncaught Exception:
Error: socket hang up
    at createHangUpError (_http_client.js:203:15)
    at TLSSocket.socketCloseListener (_http_client.js:235:23)
    at emitOne (events.js:82:20)
    at TLSSocket.emit (events.js:169:7)
    at TCP._onclose (net.js:467:12)

[OK]



I used the same value for the HTTP and HTTPs proxy parameters as I have been using before the MavensMate standalone app was available (using proxy authentication). I also defined the HTTP(S)_PROXY environment variables. Furthermore I tried all different combinations of with/without authentication, with/without escaping slashes etc. - unfortunately to no avail.

If you need any further info, I will be happy to provide it.

**Comment by joeferraro** [comment]
dup of https://github.com/joeferraro/MavensMate-app/issues/24#issuecomment-144939874
