### ISSUE TITLE
After upgrade cannot login

### ISSUE THREAD

**Issue by donaldrivard** [joeferraro/MavensMate#528]
I am now on version MavensMate for Sublime Text v5.0.0. I am prompted to fix my current project.
When I enter the username/password/security token I get an error that

Account is required.

I am not sure about the account. I can use the SF IDE with these same credentials and they were working with the previous version of MM this morning. 

Don

**Comment by joeferraro** [comment]
Hi @donaldrivard what platform are you please?

**Comment by donaldrivard** [comment]
OSX version 10.10.3

**Comment by joeferraro** [comment]
@donaldrivard apologies for the issue. A few questions: were you running the Sublime Text v5 betas or did you upgrade directly from v4? What command are you running that prompts MavensMate to fix your project? As a workaround, you can go to your keychain and search for the id in your project's config/.settings file and update the password directly there.

**Comment by donaldrivard** [comment]
Hi Joe,
I did upgrade from 4. When I open a project and then choose Open Project in Sublime. I am then presented with

Your project's credentials are either invalid or expired. Please update them below.
The Project Name is empty but locked so I cannot update
I add my username/password/token select Sandbox.

**Comment by donaldrivard** [comment]
I checked my keychain and the password was correct, though I did resave and still the same error

**Comment by donaldrivard** [comment]
I removed my config directory and let this version create a new project from the directory and now all is good. So something in the config. I will close the issue. Thanks!

Don
