### ISSUE TITLE
Mavensmate cannot deploy to server because of INVALID_LOGIN

### ISSUE THREAD

**Issue by nutchanon-pho** [joeferraro/MavensMate#529]
With the update of the new Mavensmate 5, I am no longer able to perform any "Deploy to Server". The error message is "INVALID_LOGIN: Invalid username, password, security token; or user locked out."
I have checked the login history of the account I used for the org connection and there was a success login from "Other Apex API" which should be the case of the org connection from Mavensmate. However, when the actual deployment is done, there is that error.

**Comment by joeferraro** [comment]
Hi have you tried deleting/re-creating the org connection? What platform are you on?

**Comment by nutchanon-pho** [comment]
Yes, I just did that a moment ago just to double check again. The problem still occurred even when I re-create the org connection. For more information, the project I am working on was also being developed with the previous version of the Mavensmate. I didn't create the new project with the new Mavensmate.

**Comment by joeferraro** [comment]
What platform are you on, please?

**Comment by nutchanon-pho** [comment]
Oops, I'm so sorry I missed out on that question.
I am running on Mac OSC Yosemite version 10.10.5

**Comment by cwarheit** [comment]
My colleague and I are seeing this as well, both on Yosemite 10.10.5.  I have removed and re-created all of my deployment connections and closed and restarted the Mavensmate app.

**Comment by Eaton-Cirrius** [comment]
Same issue here.  Running Windows 7 64bit and v0.0.6 of MM UI.

**Comment by joeferraro** [comment]
dup of https://github.com/joeferraro/MavensMate-app/issues/41

fix is here: https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.7
