### ISSUE TITLE
Line number of error missing on compile error

### ISSUE THREAD

**Issue by grim09** [joeferraro/MavensMate#530]
When compilation of an apex class fails it would give me the error and the line number of the error, but now it only gives me the error and no line number.

I have checked but I don't think there is a setting for this that I have accidentally turned off?

I am on MavensMate for Sublime Text v5.0.0.

![screen shot 2015-09-30 at 11 49 20](https://cloud.githubusercontent.com/assets/6033653/10191156/7ddafbee-6769-11e5-95cf-700595a0791a.png)

**Comment by joeferraro** [comment]
We're just returning what the salesforce api returns, here's what I get:

<img width="922" alt="changepasswordcontroller_cls_ _another_cool_project" src="https://cloud.githubusercontent.com/assets/54157/10236620/f329b3d8-6875-11e5-8da1-85b7e6d9cb9d.png">

**Comment by sjonwilson** [comment]
I've had this problem and discovered that I had the tooling API disabled. Turning it back on seemed to give me the line numbers again.
I think I turned off tooling to get rid of another error: [ERROR]: An unexpected error occurred. Please include this ErrorId if you contact support: 680115099-16715 (1754791447)
It feels like I often get get a different reply when I change that setting.

**Comment by dancinllama** [comment]
I had this issue as well, and enabling the Tooling API for compiling fixed it.

**Comment by bhargavkodali2010** [comment]
enabling Tooling API did the trick, thanks!

**Comment by kidtsunami** [comment]
The resolution is to enable the Tooling API:
![mavensmate_and_line_number_of_error_missing_on_compile_error_ _issue__530_ _joeferraro_mavensmate](https://user-images.githubusercontent.com/504253/29088476-067a1252-7c2e-11e7-95d6-cbeb85a3c590.png)
