### ISSUE TITLE
Mavensmate Refresh All deletes .git filder (under 'src' folder)

### ISSUE THREAD

**Issue by rafiepstein** [joeferraro/MavensMate#532]
Hello,
I have just upgraded to latest Mavensmate with 0.0.6 server.
It seems that every time id do Refresh All (on the root project inside Sublime/Mavensmate), the .git sub-folder (under 'src') is deleted.
I have tried it several times, and this is consistent.
I Also tried adding, but it didn't help:
 "folders": [
        {
            "folder_exclude_patterns": [
                "config/.symbols",
		"src/.git"
            ], 
            "path": "."
        }
    ]

Any suggestions?

**Comment by joeferraro** [comment]
Sure, I'm curious why your .git directory is located in your "src" directory. From my experience, this is unusual (it's usually in the project root)

**Comment by rafiepstein** [comment]
Thanks for your quick response.
No special reason. This i show I have been working with about 10 SFDC Projects with previous version.
Are you suggesting to configure the .git at the parent of the 'src'? 
Say: 'MavensMate\SV Dev3'
instead of 'MavensMate\SV Dev3\src' ?

If that's the best practice, I can reconfigure. No big deal.

**Comment by joeferraro** [comment]
`MavensMate\SV Dev3` is typically where our .git directory would be located. Unfortunately, in the current MavensMate codebase, we treat the src directory as pretty transient during cleans/refreshes, so my recommendation would be to initiate git from the project root to avoid us wiping it out :+1:

**Comment by joeferraro** [comment]
closing, but feel free to ask any additional questions you may have

**Comment by rafiepstein** [comment]
Just saying thanks. Good clarification and we will follow your best practice!
