### ISSUE TITLE
Could not install mavens mate app

### ISSUE THREAD

**Issue by archita6** [joeferraro/MavensMate#534]
I am not able to install the Maven Mate app in the windows 7 getting following error :

![image](https://cloud.githubusercontent.com/assets/6512067/10199570/2a0101a2-6756-11e5-86d3-2a579ba1bc30.png)

**Comment by archita6** [comment]
How can the above error be resolved

**Comment by joeferraro** [comment]
Maybe try deleting your C:\Program Files (x86)\MavensMate directory and trying the install again? Perhaps try the install as admin?

**Comment by archita6** [comment]
I do not have the MavenMate dir in the location. After I download the zip file from the https://github.com/joeferraro/MavensMate-app/releases location . I unzipped and clicked on MavenMateSetup and installer starts and i get the following error. I have tried several times by redownloading the zip file again and deleting the old one but no luck

**Comment by joeferraro** [comment]
Please try running the installation as administrator.

**Comment by archita6** [comment]
It is a corporate machine I cannot login as administrator. I will try to get an administrator install it.

**Comment by joeferraro** [comment]
ok thanks @archita6. unfortunately, I don't have a better option at the moment.

**Comment by archita6** [comment]
@joeferraro  Thanks for your help

**Comment by archita6** [comment]
@joeferraro  Thanks for your help. I was able to install it as administrator

**Comment by joeferraro** [comment]
cheers!
