### ISSUE TITLE
.local-store pointing to unmanaged/*", but unmanaged missing

### ISSUE THREAD

**Issue by rafiepstein** [joeferraro/MavensMate#535]
Hi,
File names in .loacl-store point to "unpackaged/*" (i.e., "unpackaged/staticresources/FancyBox.resource").
However, unpackaged folder (WIn 8) does not exists.
Is that a concern?
If is, what's the best way to fix?
Thanks,

**Comment by joeferraro** [comment]
unpackaged is a remote (salesforce) location, so no worries. we use that as a key, not as a reference to a physical location on your drive.
