### ISSUE TITLE
Unable to run app when using proxy

### ISSUE THREAD

**Issue by OlegForce** [joeferraro/MavensMate#536]
Getting "connect ETIMEOUT 96.43.150.124:443" when trying to create a project in MavensMate app on Windows 7. I have proxy settings in the app, but seems that it's not using those for connection.

**Comment by joeferraro** [comment]
hi @OlegForce, we're tracking proxy issues here: https://github.com/joeferraro/MavensMate-app/issues/24

specifically, you may want to update to 0.0.7-beta1 which attempts to resolve the proxy issue: https://github.com/joeferraro/MavensMate-app/issues/24#issuecomment-144445363

**Comment by joeferraro** [comment]
if 0.0.7-beta1 works for you, would you kindly reply to that thread? cheers

**Comment by OlegForce** [comment]
@joeferraro thanks :) This worked ! I do still get some error popups on initial startup of MM. See screenshots.

![screenshot 2015-09-30 13 31 08](https://cloud.githubusercontent.com/assets/2013992/10200994/a64e5e8c-6777-11e5-881d-9fed8beec5cb.png)
![screenshot 2015-09-30 13 30 55](https://cloud.githubusercontent.com/assets/2013992/10200996/a931aa6e-6777-11e5-8311-0375c74894de.png)

**Comment by OlegForce** [comment]
There is also some strange error when trying to create a new class.

![screenshot 2015-09-30 13 34 54](https://cloud.githubusercontent.com/assets/2013992/10201074/163cff6e-6778-11e5-80a1-40e743acbd25.png)

**Comment by joeferraro** [comment]
@OlegForce cheers. i believe those pop-ups may be an issue contacting GitHub to retrieve update information.
Re: the streaming error: is there anything unique about your org? Is this production, sandbox, developer? Do you have a custom domain?

**Comment by OlegForce** [comment]
it's a sandbox on Winter'16 release and with "My Domain" enabled. I use "Sandbox" connection from a dropdown.

**Comment by joeferraro** [comment]
The streaming issue may be a problem with the way you configured your proxy. Can you paste your proxy settings (you can change the values for security purposes, just need to see the general format)?

**Comment by OlegForce** [comment]
http://http.proxy.somedomain.com:1234 - please note that "http" subdomain is indeed present in the proxy url and not a typo :)

**Comment by joeferraro** [comment]
@OlegForce that's no good :-1: I've pushed a new version of mm-app that will allow the streaming listener setup to fall down gracefully for folks with a proxy (that is only until we can figure out the root issue)
https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.7-beta2

**Comment by OlegForce** [comment]
Thanks for taking time to look into this issue Joe.
