### ISSUE TITLE
Unable to open any other SFDC Projects in Sublime

### ISSUE THREAD

**Issue by rafiepstein** [joeferraro/MavensMate#537]
Hi,
After the upgrade, Sublime alway starts with a certain project, and I am unable to switch.
1. ctrl-shift-o does not respond at all.
2. Using the menu, Mavensmate | Project | Open i get the list of available projects and select one, but nothing happens. The project doe snot open.

Any suggestions?
Thanks,

**Comment by joeferraro** [comment]
There is a fix coming to resolve the issue when trying to open a project from ST. However, it's important to note that you can simply open your project's directory using the standard ST open directory dialog.

**Comment by rafiepstein** [comment]
Thanks. I just discovered that I can open from the app server; just another workaround.
