### ISSUE TITLE
Request to the local MavensMate server failed. Error initializing project...

### ISSUE THREAD

**Issue by hemmeter** [joeferraro/MavensMate#540]
I was getting issues with my projects in Sublime Text not being able to connect to the MavanesMate app. After some troubleshooting, I ended up re-installing Mavensmate.app. It is now at v5.0.0.

If I run Sublime Text 3 with Mavensmate.app running already, I get a "Happy Coding" message in the console. If it's not running, I get "Could not contact local MavensMate server, please ensure MavensMate-app is installed and running". Ideally, it'd auto-load Mavensmate.app, but not the end of the world. I did try setting mm_start_mavensmate_app=true in my user settings. It doesn't always work.

So now I am running Sublime with Mavensmate.app running and get Happy Coding message. However, all my projects cannot be found. Trying to edit a project or creating a new project gets "Request to the local MavensMate server failed. Error initializing project..." in the console.

Ideas? 

In the Global Settings of Mavensmate.app, I set the mm_workspace value thinking that might be the problem. Didn't help.

In the Global Settings of Mavensmate.app, I checked the mm_mavensmate_app_path value, but it was already correct.

Sorry I might be mixing up issues all in one, but I think I have most resolved except for connections to the projects. 

I'm on Yosemite 10.10.5, MavensMate for Sublime Text v5.0.0, Mavensmate.app v0.0.6 and Sublime Text 3 Build 3083.

**Comment by joeferraro** [comment]
Hi Scott, can you generate logs? (configured in mm-app global settings)

**Comment by hemmeter** [comment]
So... I figured it out and it's a PEBKAC situation. Remember how I mentioned that "In the Global Settings of Mavensmate.app, I set the mm_workspace value thinking that might be the problem. Didn't help."?

Turns out I missed a folder in the path when entering mm_workspace value. :|

You can pretend this issue never happened.

**Comment by joeferraro** [comment]
@hemmeter no worries. what was the exact error you were getting? seemingly it wasn't helpful enough, so I'd like to enhance it if possible.

**Comment by hemmeter** [comment]
"Request to the local MavensMate server failed. Error initializing project: Could not find project. Please ensure your mm_workspace global setting is configured properly and your project is located in a valid mm_workspace"

As you can see, it's a pretty good error message. I just didn't get to the right folder.

**Comment by joeferraro** [comment]
We're going with:

"MavensMate could not find project with the id: <your project id>. This is likely because you are trying to open a project that does not reside in a valid mm_workspace. Please go to MavensMate-app global settings and ensure this project is located in a valid mm_workspace."

:+1:

**Comment by hemmeter** [comment]
ok. on a side note, every time I open MavensMate.app, the osx firewall asks me to allow incoming connections for it. I tried to whitelist it in the firewall, but it still is asking everytime. Could be user error again.

**Comment by joeferraro** [comment]
interesting, will have a peek

**Comment by twench** [comment]
[
  "C:\\Users\\dthomas\\Documents\\salesforce\\salesforce_Sandbox"
]


Error initializing project: MavensMate could not find project with the id: XFDJBOX1ZTEU5UJPH524R7VQ5NJ0HNB7. This is likely because you are trying to open a project that does not reside in a valid mm_workspace. Please go to MavensMate-app global settings and ensure this project is located in a valid mm_workspace.

been going in circles here for hours. i am not sure why i was forced to change but now im just lost on how to get this going. anymore suggestions?

**Comment by twench** [comment]
when i try to make a new project i get this error message... 

tunneling socket could not be established, cause=getaddrinfo ENOTFOUND 8080 8080:80

**Comment by seanhharrison** [comment]
@twench Sounds like it might be a different problem and this particular issue has been Closed. Do us a favor and open a new issue with all the juicy technical info (versions, etc.)
