### ISSUE TITLE
How To: Run specific Apex test methods and Synch with Server

### ISSUE THREAD

**Issue by afaubel** [joeferraro/MavensMate#542]
In the version 5 release notes it mentions the following two features:

- Run specific Apex test methods
- Sync with server command

Does anyone know how these can be accessed?

**Comment by joeferraro** [comment]
To run specific Apex test methods, open a test class and run:

<img width="443" alt="screen shot 2015-10-01 at 6 58 24 am" src="https://cloud.githubusercontent.com/assets/54157/10219071/dc2c9a86-6809-11e5-8421-f6a652d1485c.png">


To sync with the server, open Apex/VF metadata and run the "Sync with Server" comamnd
