### ISSUE TITLE
Feature Request: Reduce minimum width setting  for MavensMate-app when in windowed mode

### ISSUE THREAD

**Issue by cdanhowell** [joeferraro/MavensMate#543]
The app has a minimum width (and height, but I am personally not concerned about that) setting that is rather large for smaller screen sizes. It can't be resized to take up a smaller section of the screen. Considering the ample white-space of the app (while on the home screen, at least), it would be nice to be able to shrink that down some.

Thanks!

**Comment by joeferraro** [comment]
thanks for the request! this has been reduced in 0.0.9.

**Comment by cdanhowell** [comment]
Excellent, much appreciate it!
