### ISSUE TITLE
Compiling project causes all files to 'conflict' with server

### ISSUE THREAD

**Issue by dkaskoun** [joeferraro/MavensMate#547]
It seems that every time I do a compile of my entire project, any class/page/trigger I try to save brings up the message that says 'A conflict has been detected. xyz.cls was last modified by XYZ on 2015-10-01T15:32:19.000+0000'. This gets annoying, as I either have do a force-save each new file I touch after a compile, click on the diff just for it to tell me there are no changes, or clean the entire project after every compile.

**Comment by ralphcallaway** [comment]
assuming the conflict is valid (which seems likely with a full compile), your best option would be to turn off the conflict check before compiling the project, go to the global settings and uncheck "Check conflicts before compile"

bear in mind the conflict check is timestamp driven, so it's easy for things to get out of sync, when i'm doing dev i typically refresh a file from the server before i start editing it, that lets me make sure there aren't unexpected changes in there, and if the local/server timestamps weren't initially in sync the refresh gets them there. It's an extra step, but honestly, unless you're the only person in the org, it's a good safety practice

**Comment by joeferraro** [comment]
@ralphcallaway thanks for chiming in. actually this was a bug bc when we compiled we weren't updating the project's local store with the most recent server copies, so technically the project was out of sync with the server (which had just been updated)

**Comment by ralphcallaway** [comment]
@joeferraro figured something was happening in there, always nice to have a work around

you're output is mind blowing these days, feel like i'm downloading a new version daily, very exciting stuff, definitely seeing some good performance improvements :100:

**Comment by joeferraro** [comment]
fix available in https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.7
