### ISSUE TITLE
Was MM5 a silent upgrade? If so, it shouldn't be

### ISSUE THREAD

**Issue by deckblad** [joeferraro/MavensMate#548]
I don't recall having agreed to a major version upgrade. It just sort of happened.

Although no harm came to me. I'd strongly suggest this upgrade require some user intervention before being pushed through. At least for major version updates. I'd hate to have been in the middle of a production hotfix and have to spend extra time re-setting up my IDE.

Thank you very much for your hard work. I really appreciate what you've created for us.

**Comment by joeferraro** [comment]
@deckblad I agree this is a scary proposition, but this is a Package Control issue, not a MavensMate issue, unfortunately. You have the ability to control auto installation of packages via Package Control settings: https://packagecontrol.io/docs/settings

make sense?

We've also included details on how to run the MM for ST v4 if necessary: https://github.com/joeferraro/MavensMate-SublimeText#install

**Comment by deckblad** [comment]
Thank you for the explanation.
