### ISSUE TITLE
Project Clean only keeping Classes

### ISSUE THREAD

**Issue by djorgji** [joeferraro/MavensMate#552]
Clean Project is deleting all files and only recreating classes, even though my package.xml looks as follows:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
    <types>
        <members>*</members>
        <name>ApexClass</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexComponent</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexPage</name>
    </types>
    <types>
        <members>*</members>
        <name>ApexTrigger</name>
    </types>
    <types>
        <members>*</members>
        <name>StaticResource</name>
    </types>
    <version>34.0</version>
</Package>
```

**Comment by joeferraro** [comment]
hi @djorgji can you update your issue according to the guidelines? thanks!

https://github.com/joeferraro/MavensMate/blob/master/CONTRIBUTING.md#submitting-issues

**Comment by djorgji** [comment]
It is not the editor, since the files simply don't exist in the file system. I already searched and I could not find anything about this issue... 

I have a work around right now where if I select the folders individually in sublime's sidebar and refresh from server it downloads the contents for pages, triggers, components and static resources, but if I "Clean Project" It deletes everything but Classes.

**Comment by joeferraro** [comment]
@djorgji the contribution guidelines ask for your platform and mavensmate version(s) where applicable.

**Comment by djorgji** [comment]
Windows, Sublime Text 3, 5.0.7 MavensMate app.

**Comment by joeferraro** [comment]
What version of windows, please and 32 or 64 bit?

**Comment by djorgji** [comment]
Windows 10, 64 bit.

**Comment by joeferraro** [comment]
5.0.7 of mm-app is not valid, which version? https://github.com/joeferraro/MavensMate-app/releases

**Comment by djorgji** [comment]
Had v0.0.7-beta5, updating to v0.0.9-beta2. I am going to retry on new version.

**Comment by djorgji** [comment]
Okay it did it again on the newest version.

**Comment by joeferraro** [comment]
ok, can you please generate logs (setup is done in mm-app settings) and paste relevant logs? thanks

**Comment by joeferraro** [comment]
@djorgji There are some super pesky PERM-related issues with node on windows. this update changes the way we do cleans/refreshes/edits of the src directory. let me know if it works for you: https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.10-beta4

**Comment by joeferraro** [comment]
closing, if it's still an issue, please re-open. cheers
