### ISSUE TITLE
Mavensmate not working

### ISSUE THREAD

**Issue by newUserAdi** [joeferraro/MavensMate#554]
I have installed the Mavensmate-app in my C:\Program Files and when I run mavensmate, it does not do anything, in task manager I see that Mavensmate.exe is running,
This is what I did,
Sublime >> Package Control >> Remove Package >> Mavensmate
Installed Mavensmate-app for Windows v0.0.7 - MavensMate-app-v0.0.7-win-x64-setup.zip
unzip and install. run it, 
Install Sublime >> Package Control >>  Install Package >> Mavenmate. 
But its not working
What am I doing wrong?

Thanks

**Comment by joeferraro** [comment]
Are you behind a proxy?

**Comment by newUserAdi** [comment]
No

**Comment by joeferraro** [comment]
you're more than welcome to install v4: https://github.com/joeferraro/MavensMate-SublimeText#version-4-no-longer-supported

**Comment by newUserAdi** [comment]
Will try that. Thanks

**Comment by garyspencer** [comment]
I think this might be a python issue.?
