### ISSUE TITLE
Package Visibility: Type is not visible Error

### ISSUE THREAD

**Issue by baohle** [joeferraro/MavensMate#555]
I'm receiving this error: "Package Visibility: Type is not visible" when attempting to compile my code. I was able to use Mavensmate to update my code before by changing a mm_compile_with_tooling_api to false but that setting is no longer available or at least I can't see it.

**Comment by joeferraro** [comment]
this option is available in global mavensmate-app settings

<img width="709" alt="mavensmate" src="https://cloud.githubusercontent.com/assets/54157/10265888/e1068118-6a0f-11e5-959f-e15505b7cd04.png">
