### ISSUE TITLE
mavensmate 5.0 refresh clean does not retrieve standard objects metadata

### ISSUE THREAD

**Issue by TCS-JMI** [joeferraro/MavensMate#557]
In the previous mm v4, with <types><members>*</members><name>CustomObject</name></types> in package.xml, the metadata for both custom AND standard objects were retrieved.
Now with the same package.xml, standard objects metadata are not retrieved.

**Comment by joeferraro** [comment]
this fix is available in https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.10-beta1
