### ISSUE TITLE
I AM SICK OF BUGS

### ISSUE THREAD

**Issue by kushney** [joeferraro/MavensMate#559]
WHEN I REFRESH PROJECT IN MAVENSMATE IT PUTS PACKAGE.XML IN 'unpackaged' FOLDER AND I CANNOT REFRESH FILES. WHY DO YOU CONTINUE DEVELOPING THIS SHIT WITH BUGS???

**Comment by joeferraro** [comment]
http://contributor-covenant.org/version/1/2/0/

**Comment by harshal-gajare** [comment]
@kushney That is uncalled for. Its a open source project. If you don't like it, please stop using it. @joeferraro has been working round the clock helping fix any issues.

**Comment by kushney** [comment]
@harshal-gajare Sorry I got a bit nervous. Mavensmate is the best option for salesforce developing, but I can't understand what was bad in previous versions, they worked ok, and after I updated to the latest, there appeared a lot of bugs

**Comment by kushney** [comment]
@harshal-gajare open source is nothing about it. Project has to be stable anyway. And if there are a lot of bugs this is measure of your's work quality.
