### ISSUE TITLE
Should DandBCompany.object be part of custom objects package?

### ISSUE THREAD

**Issue by deckblad** [joeferraro/MavensMate#560]
The standard object for Data.com, DandBCompany.object, is included when downloading all non-managed-package objects. I don't think it can be updated via Metadata API. Should it be included as part of the custom packages or only downloaded if mm_ignore_managed_metadata is unchecked? Or, could there be an MM option to filter out certain filenames from the project metadata explorer?

I ask because it becomes a bother to want to "select all" on the objects metadata folder but then have to always remove the file from my deployments to SFDC.

Thank you.

**Comment by joeferraro** [comment]
I noticed that coming down via the metadata api as well. I'd like to avoid introducing filters to the metadata returned from salesforce beyond what we have in place now.

**Comment by deckblad** [comment]
Fair enough. Is/can there (be) a place in the User config to store "never download this metadata name" values?

**Comment by deckblad** [comment]
Continuing discussion on MM-App project.

https://github.com/joeferraro/MavensMate-app/issues/92
