### ISSUE TITLE
No sound after updating to 5

### ISSUE THREAD

**Issue by CSTufts** [joeferraro/MavensMate#561]
I am severely missing my on save file sounds. since Updating to 5 they have not been firing on success or failure. any ideas of what might have happened (I did update them to custom sounds with a custom path within my custom setting and now I cannot get to the preference file to update it, I can't even remember where the darned thing is...)

thanks

**Comment by joeferraro** [comment]
dup of https://github.com/joeferraro/MavensMate-SublimeText/issues/645
