### ISSUE TITLE
Atom not supported?

### ISSUE THREAD

**Issue by raJSN** [joeferraro/MavensMate#562]
Searched on google and found that previously, Atom was not supported due to some file permission issue. But, now there is no disclaimer like this, and Windows 7 is present among supported platform.

Platform: 32 bit windows 7
MM version:  1.0.6
MM app version: v0.0.9
Steps to reproduce:
1. Go to Atom textpad > Mavensmate > Project > New Project > (Mavensmate app will be opened).
2. Provide credentials for the org and hit on create project.
3. Got error "Editor not supported". However, if i check the directory, I found that the package is infact created but with *.sublime-project name.
So, is there any setting that I am missing for Atom in Windows 7 (32 bit)

**Comment by raJSN** [comment]
Is there any configuration settings that i need to do in Mavensmate app?

**Comment by joeferraro** [comment]
Hi, can you please update your issue according to the guidelines? thanks! https://github.com/joeferraro/MavensMate/blob/master/CONTRIBUTING.md

**Comment by raJSN** [comment]
Hi @joeferraro, Thanks for your comment. I have updated my issue details.

**Comment by ipavlic** [comment]
The default path to Atom executable in MavensMate is wrong. `editor.js:195` throws the error after `client.js:74` fails to resolve the atom executable in `_findSupportedEditors` method.

**Comment by joeferraro** [comment]
will be available in mm-app 0.0.10-beta4
