### ISSUE TITLE
Trouble opening Mavensmate

### ISSUE THREAD

**Issue by sirimudindi** [joeferraro/MavensMate#566]
I have been using mavensmate and from last week i was asked to install mavens mate app for my windows and still i have few errors. when i set the 
mm_workspace to "mm_workspace" : ["C:\\siri.potturi\\extweb\\force.com\\workspace"], it throws an error Unexpected Token. When i set workspace to  { "mm_workspace" : "C:/siri.potturi/extweb/force.com/workspace" } , it says Request to the local MavensMate server failed. Error initializing project: path must be a string. I havent changed any other settings. Please suggest what have to be done to use my mavens mate again.

**Comment by joeferraro** [comment]
Hi, have you tried to set it as:

```
["C:\\siri.potturi\\extweb\\force.com\\workspace"]
```

**Comment by sirimudindi** [comment]
yes, it says unexpected token

**Comment by joeferraro** [comment]
Can you post a screenshot of your setting?

**Comment by sirimudindi** [comment]
sure, please find the attached
![error png](https://cloud.githubusercontent.com/assets/15001037/10316750/cafd9ae8-6c15-11e5-8982-5df3da5a47c5.PNG)

**Comment by joeferraro** [comment]
you need to remove the trailing comma from your setting

**Comment by sirimudindi** [comment]
I did, but same error

**Comment by joeferraro** [comment]
ok your setting should look like this:

![windows_8](https://cloud.githubusercontent.com/assets/54157/10316933/d6074a6e-6c2f-11e5-940a-c27897f5d3f5.png)

notice there's no "mm_workspace" in the box

**Comment by sirimudindi** [comment]
I have changed like you suggested and it worked, but when i went back to amvenmate and try to refresh files from server this is the error that i have got
Request to the local MavensMate server failed. Error initializing project: ENOENT: no such file or directory, scandir 'C:\siri.potturi\extweb\force.com\workspace'

**Comment by sirimudindi** [comment]
Hey, it worked, i missed users after C: thanks for all u r help and quick response. Really appreciate it

**Comment by sirimudindi** [comment]
Hi, i went to my mavens mate, reentered my credentials and im still getting this error. Please suggest
In version 5+ of MavensMate for Sublime Text, there is a new companion app called MavensMate-app. You must download, install, and run this application in order for the MavensMate for Sublime Text plugin to operate. For more information, please visit https://github.com/joeferraro/MavensMate-app

**Comment by sirimudindi** [comment]
DO i have to change any other settings ?

**Comment by ralphcallaway** [comment]
@sirimudindi since this is a separate issue could you log a seperate ticket and include the details outlined in the contribution guidelines? https://github.com/joeferraro/MavensMate/blob/master/CONTRIBUTING.md
