### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by zokito** [joeferraro/MavensMate#570]
I've seen a lot of negative comments related to the latest releases of MM. I just wanted to make an opposite remark and thank you @joeferraro for all of the effort and time spent creating this. I presume you have a "regular" job with all the challenges everyone else here is facing, and I know how much will and "free" time must have been invested in creating this great FREE tool.

So to put it short thank you so much and keep up the great work!

P.S.
Please feel free to close the issue.

**Comment by TCS-JMI** [comment]
++  same feeling: thanks a lot for this really powerfull tool , that daily provides us a good productivity on Salesforce implementaitons.   
Thanks also to have provided the possibility of working on V4 ("V6").
Regards

**Comment by harshal-gajare** [comment]
+1 . I agree. It is a great tool and I am glad I don't have to use eclipse. @joeferraro Thank you for all your work creating and supporting this .

**Comment by Eaton-Cirrius** [comment]
I concur, MM is a fantastic tool!  

Mad props for all your hard work!  Truly!!

**Comment by garyspencer** [comment]
Concur.  
Forget the haters.  
Nice work is being done here by everyone involved!

**Comment by jpesusich** [comment]
My sincerest thank you for your hard work and dedication to this project - I really prefer what your team has created over the developer console and eclipse/force ide.  Thank you.

**Comment by KentigernEnnis** [comment]
Hear, hear!
The best SFDC dev tool out there!

**Comment by Heiberg5** [comment]
I share that sentiment. Thank you Joe!!!

**Comment by joeferraro** [comment]
cheers, chaps
