### ISSUE TITLE
Feature Request:  Opt-in Preference for blind updates and/or rollbacks

### ISSUE THREAD

**Issue by Eaton-Cirrius** [joeferraro/MavensMate#573]
Please don't blindly rollback.  Maybe there were more people having problems then I'm aware but V5 was working great with some minor tweaks.  Then all of a sudden we come into the office and MM blows up because the app decided to do a blind rollback?!  Seriously?
![image](https://cloud.githubusercontent.com/assets/10838246/10344529/5ca577bc-6ce9-11e5-886c-c76094a4d04f.png)

Suggestion with all do respect, consider adding the option to opt-in to blind updates and/or rollbacks and leave the choice to the User.  

Thanks for all the hard work!

**Comment by Eaton-Cirrius** [comment]
Let me clarify.  Separate options for both auto-install New Releases and Rollbacks if that makes sense.

**Comment by joeferraro** [comment]
Hi, apologies for the inconvenience, but unfortunately, I can't please everyone. Update preferences are controlled by Package Control. You can configure whether to auto update and/or install prereleases via Package Control settings: https://packagecontrol.io/docs/settings
