### ISSUE TITLE
Unable to use 'local' mm_template_location template repository with v0.0.9

### ISSUE THREAD

**Issue by jpesusich** [joeferraro/MavensMate#575]
My mm_template_location is set to 'local' and it is a valid path to a cloned version of the github repository. I was able to use this feature prior to the app release and haven't been able to use my own templates with MavensMate-app v0.0.6 -v0.0.9 on both windows and osx releases. It appears that it is still behaving as the 'remote' behaviour. I have downloaded the template project and am still unable to pull local templates when creating new meta data. I appreciate all of the work that has been done on this and hope its just another configuration setting I am missing. Thank you.

**Comment by joeferraro** [comment]
dup of https://github.com/joeferraro/MavensMate-app/issues/69 (fixed in 0.0.10-beta3
