### ISSUE TITLE
Unable to retrieve pasdsword from the keychain store

### ISSUE THREAD

**Issue by haripopuri** [joeferraro/MavensMate#577]
I uninstalled (Sublime, MavensMate everything, deleted folders from user app data roaming directory) and installed fresh. I am still getting this error.

Operation: Your MavensMate project needs to be upgraded. Opening the upgrade UI.
Timestamp: Wed, 07 Oct 2015 22:58:57
   Result: [OPERATION FAILED]: Unable to retrieve password from the keychain store.

What can I do now? Is there any workaround?

Thanks
Hari

**Comment by LKozakewycz** [comment]
Fix:

https://github.com/joeferraro/MavensMate-SublimeText/issues/705#issuecomment-146154726

**Comment by joeferraro** [comment]
cheers @LKozakewycz
