### ISSUE TITLE
Errors displayed without formatting, just plain json

### ISSUE THREAD

**Issue by anbeque** [joeferraro/MavensMate#586]
Sometimes errors are displayed in json without parsing.

This is an example (using tooling API and v4.0.5):

{"success": false, "numberComponentsDeployed": "0", "checkOnly": false, "numberTestsTotal": "0", "createdByName": "xxxx", "lastModifiedDate": "2015-10-14T09:05:21.000Z", "createdBy": "xxxx", "runTestsEnabled": false, "status": "Failed", "details": {"runTestResult": {"numFailures": "0", "numTestsRun": "0", "totalTime": "0.0"}}, "numberComponentErrors": "0", "done": true, "ignoreWarnings": false, "numberTestErrors": "0", "rollbackOnError": true, "createdDate": "2015-10-14T09:05:11.000Z", "errorStatusCode": "ALREADY_IN_PROCESS", "completedDate": "2015-10-14T09:05:21.000Z", "id": "xxxx", "errorMessage": "null: The changes you requested require salesforce.com to temporarily lock your organization's administration setup. However, the administration setup has already been locked by another change. Please wait for the previous action to finish, then try again later.", "numberComponentsTotal": "0", "numberTestsCompleted": "0"}

Is there any way of getting this errors parsed?

Thanks,
Angela.

**Comment by pbattisson** [comment]
Hi Angela

Could you provide the details listed in the contributing guide at https://github.com/joeferraro/MavensMate/blob/master/CONTRIBUTING.md so we can have a look into this in more detail and confirm?

Thanks

Paul

**Comment by anbeque** [comment]
Hi Paul, 

Thank you for pointing me to the right direction about how to report an issue. I will configure my mavesmate app to get debug logs and I'll try to reproduce the issue to be able to give you all the information you require. 

Please, keep this issue open until I can provide the right info.

Thanks again,
Angela.

**Comment by pbattisson** [comment]
@anbeque Closing this old issue out.
