### ISSUE TITLE
Cleaning project returns random results

### ISSUE THREAD

**Issue by Katulka** [joeferraro/MavensMate#587]
I cleaned a project and all of the metadata was gone locally.

I cleaned again and I have everything but "pages" contents

I cleaned again and now "pages" and "triggers" is all that I have, classes, components are blank

Here's the output

[MAVENSMATE]: Calling mavensmate adapter
[MAVENSMATE]: OPERATION: clean-project
[MAVENSMATE]: {'context': <MavensMate.mavensmate.CleanProjectCommand object at 0x00000005C5FA6240>}
[MAVENSMATE]: http://localhost:56248/execute?command=clean-project&async=1&pid=LZJ544SP3ITIFTU1K92I7MSI0R0EVHQ3
[MAVENSMATE]: response from MavensMate
[MAVENSMATE]: <http.client.HTTPResponse object at 0x00000005C5C6EB70>
[MAVENSMATE] skipped community activity
ReadDirectoryChangesW fails with ERROR_ACCESS_DENIED
[MAVENSMATE]: {'complete': True, 'result': {'message': 'Project cleaned successfully'}, 'id': 'dd636130-767f-11e5-bcd9-ed58c9ab5c9c', 'operation': 'clean-project'}

MM v7.0.0-beta.1
MMApp 0.0.9
Win 10
ST3 3083

**Comment by joeferraro** [comment]
@Katulka I've been fixing many windows-related PERM issues in the 0.0.10 betas. Long story short, node on Windows runs into intermittent PERM issues that are incredibly hard to reproduce at times. My solution was to fundamentally change the way edits/cleans/refreshes/etc happen within the project directory to circumvent those issues.

Can you see whether 0.0.10-beta6 resolves this issue? https://github.com/joeferraro/MavensMate-app/releases

If it does, could you kindly close this issue? Cheers

**Comment by Katulka** [comment]
That update worked for me, thanks @joeferraro for the prompt reply.
