### ISSUE TITLE
Resource Bundle Still not working my end.

### ISSUE THREAD

**Issue by viraj89** [joeferraro/MavensMate#588]
I have :
Windows 7 - 64 bit, 
MavensMate for Sublime Text v6.0.0 running
Sublime Text 3 running 

Tried everything after seeing the comments at issue #375, but still unable to create a bundle! I know that might sound awful but I need you guys help here and tell me what's wrong with my way.

I have a folder called "folder". In that folder I have folder "CSS" and it has 2 css files, then I have "JS" folder and it has 5 js files. and so on. What I did is right clicked the "folder" and selected Add to "folder.rar" and then uploaded this to my static resource. This I see successfully at the static at MM!

Now the challenging thing begins. I right click the folder "folder.resource" from staticResource --> MM---> Create Resource Bundle(s)

In the console I just see as :- 
" Creating Resource Bundle(s)" 
Dead end. Nothing after that.

It do create folder as shown in the video but it has nothing in it. Its empty. 

Deleted the rar file from static resource, refreshed then tried. Did almost 5 times, didn't work.

Please help me @joeferraro, @cjones700, @nwalsh82 , @jungleeforce, @frankzimper

Thanks.

PS: Issue I see closed here - https://github.com/joeferraro/MavensMate/issues/375

Hence created this new

**Comment by joeferraro** [comment]
Hi @viraj89, please do not create duplicate issues. We are no longer making fixes to the API that runs version 6 of the plugin (https://github.com/joeferraro/mm). Of course it's open source, so anyone may make fixes and submit a PR. 

I'd recommend [installing v7 of the Sublime Text plugin](https://github.com/joeferraro/MavensMate-SublimeText#version-7-betas), where we've made a host of updates/fixes including fixes to the resource bundle functionality. Let me know if you have issues running v7. Cheers.
