### ISSUE TITLE
IP Addresses to permit in Firewall for MavensMate

### ISSUE THREAD

**Issue by ddawson17** [joeferraro/MavensMate#599]
Hi,

I am using MavensMate at work and I am behind a very strict firewall. Do you have a list of IPs that can be whitelisted in the Firewall for MavensMate to both push and pull metadata successfully?

We have already whitelisted the Salesforce IPs (Eclipse works behind the firewall) but I think MavensMate calls a few other servers before going to Salesforce and these are the problematic IPs.

Or if downgrading the tooling/metadata API version that is used will fix this issue (I have read a few people doing this and it starts working) then please let me know.

Thanks in advance!

**Comment by ralphcallaway** [comment]
not sure if there is a full list, but some sources that come to mind (you'll have to research what IPs they use)
- github
- package control

that said, these are mostly for upgrades, you should be good to with just the salesforce ip addresses
