### ISSUE TITLE
Add ability to cancel current request

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/MavensMate#600]
app: v0.0.10
st: v7.0.0-beta.1

From time to time compiling is really really slow. Seems like the issue is with Salesforce taking for ever to retrieve the resulting compiled class.

In these cases it would be useful to have the ability to cancel the current request. The current option is to close mavensmate then re-open and repeat request.

**Comment by ralphcallaway** [comment]
With a recent example, after closing and restarting mavensmate refreshing the file revealed that the file was indeed compiled. Tailing the logs prior to closing mavensmate shows that it's continually checking doing an operation status check (which I'm assuming is the retrieve of the resulting file).

**Comment by steals** [comment]
+1 I'm also experiencing this issue from time to time and it would be really helpful to have such command that we can map for a hotkey.

**Comment by brosiusad** [comment]
+1  See #597 for a very recent example of where this would have been very helpful to me.

**Comment by joeferraro** [comment]
I'm closing this as there's often no way to intercept a request once it's been submitted to salesforce. in certain instances (long deploy) it's technically possible, but we don't have the bandwidth to look into it at this time
