### ISSUE TITLE
Getting ```Bad_Id``` when trying to create new project

### ISSUE THREAD

**Issue by OlegForce** [joeferraro/MavensMate#614]
OSX 10.10.5 MBP Late 2013
MM v0.0.10 standalone app
No firewall
"New project" > enter credentials, click create.
Dev org

MavensMate logs. Configure logging via MavensMate-app settings, run your failing operation to generate logs, and paste relevant logs to your issue.
If relevant, your Salesforce server (e.g., cs18, c31, na7, etc.)

<img width="738" alt="screenshot 2015-12-03 10 23 25" src="https://cloud.githubusercontent.com/assets/2013992/11564601/10843a94-99a8-11e5-8e7c-95703e446ed4.png">

**Comment by ralphcallaway** [comment]
@OlegForce can you please update your issue according to the guidelines? thanks! https://github.com/joeferraro/MavensMate/blob/master/CONTRIBUTING.md

**Comment by OlegForce** [comment]
It looks like the problem only happens when you select production for dev org...

**Comment by ralphcallaway** [comment]
@OlegForce so just gave that a try and I'm able to create a new project with the dev org

if you can get a log for the failed operation we can likely figure this out, see https://github.com/joeferraro/MavensMate/blob/master/CONTRIBUTING.md

**Comment by OlegForce** [comment]
I am not able to get logs. Don't worry about it. There is a workaround.
