### ISSUE TITLE
Error while saving lightning component

### ISSUE THREAD

**Issue by manimaran99** [joeferraro/MavensMate#623]
Hi There

I'm getting error while saving Lightning component on Mavensmate (MavensMate-app V0.0.11-beta1)
Operation: Compiling: mytest.cmp
Timestamp: Mon, 07 Dec 2015 10:54:21
   Result: [OPERATION FAILED]: local variable 'meta_type' referenced before assignment

Need help

Thanks
Mani

**Comment by ralphcallaway** [comment]
@manimaran99 can you please update your issue according to the guidelines? thanks! https://github.com/joeferraro/MavensMate/blob/master/CONTRIBUTING.md

**Comment by manimaran99** [comment]
@ralphcallaway  Apologise for the inconvenience  , Please find the information presented as per the guidelines

Your platform (OSX, Linux, Windows) and architecture (32 or 64 bit)
- Mac 10.10.5 (Yosemite) 64 bit
The MavensMate version(s), i.e. MavensMate plugin version and MavensMate-app version
-  MavensMate plugin version V6.0 & MavensMate-app V0.0.11-beta1, 
Whether you are behind a firewall and/or proxy
- No
Specific steps to reproduce
- Created  new lightning Component via App 
- Trying to edit the  Lightning component 
- Getting error local variable 'meta_type' referenced before assignment
MavensMate logs. Configure logging via MavensMate-app settings, run your failing operation to generate logs, and paste relevant logs to your issue.
If relevant, your Salesforce server (e.g., cs18, c31, na7, etc.)
- Attached Logs 
- NA34
[mavensmate.log.zip](https://github.com/joeferraro/MavensMate/files/54456/mavensmate.log.zip)

**Comment by ralphcallaway** [comment]
thanks @manimaran99 looking at the attached logs and I don't see any details for that command in there, can you repeat the error you're getting and then attach the logs for that action

if you look at the attached version you'll see that it only details one command 'open project' which succeeds, i'd expect to see a compile metadata command, or compile lightning command running then an error with the meta_type referenced undefined

**Comment by manimaran99** [comment]
Hi @ralphcallaway  for some reason compile command is not loged to log file. Attached screenshot of the error i get
<img width="1364" alt="screen shot 2015-12-07 at 11 38 18 am" src="https://cloud.githubusercontent.com/assets/797370/11637582/15003aaa-9cd7-11e5-8611-e957cbdbcb64.png">

**Comment by ralphcallaway** [comment]
@manimaran99 got it, that means there error is happening at the ST3 package before it calls out to our mavensmate core

can you open the sublime text console and paste the contents generated after repeating the operation? that will give us the stack trace for your error

**Comment by steals** [comment]
I belive Lightning Components supported only in the version 7 of the Sublime Text plugin and not in version 6. And actually version 6 of the plugin does not use MavensMate app, and use old mm api. Therefore there are no logs in the attached file.

@manimaran99 Install the latest beta of the ST plugin (https://github.com/joeferraro/MavensMate-SublimeText#version-7-betas) and you should be able to successfully save your lightning components.

**Comment by manimaran99** [comment]
Thanks @steals @ralphcallaway After installing 7 beta, Issue is resolved  Thanks For your help
