### ISSUE TITLE
circle ci test parallelization causes test failures

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/MavensMate#628]
circle ci tests are set up to run in parallel, this is causing tests to fail with admin operation already in process

i'd suggest removing parallel test runs are break up the two paths into integration and fixture based tests so only one path will be making calls to a real salesforce org

for example https://circleci.com/gh/joeferraro/MavensMate/452
```
  1) mavensmate delete-metadata should create then delete metadata from server:
     UNKNOWN_EXCEPTION: admin operation already in progress
      at HttpApi.getError (node_modules/jsforce/lib/http-api.js:240:13)
      at node_modules/jsforce/lib/http-api.js:85:22
      at node_modules/jsforce/node_modules/promise/lib/core.js:33:15
      at flush (node_modules/jsforce/node_modules/promise/node_modules/asap/asap.js:27:13)
```

**Comment by joeferraro** [comment]
@ralphcallaway have CI set up on travis now using 5 VMs running separate tests against 5 different dev environments. all good!
