### ISSUE TITLE
Compilation is very slow (Apex, Visualforce, StaticRes)

### ISSUE THREAD

**Issue by wojciechSlodziak** [joeferraro/MavensMate#631]
Ever since I started using Sublime and MavensMate for Sublime to develop Salesforce apps I'm having very long save times (1min - 3min). It doesn't matter what kind of file it is - always super long.

I've seen similar issue closed: https://github.com/joeferraro/MavensMate/issues/52
I tried installing newest versions of Sublime (3083) and MavensMate (4.0.2) but this doesn't help.

Also setting: "mm_compile_with_tooling_api" is set to true.

Any tips? How can i help to solve this problem?

**Comment by bonhomie** [comment]
Have you tried to edit the project from MavensMate app by unchecking the files that you don't need to use? It doesn't improve the performance that much but it does help.

**Comment by kurtfairfield** [comment]
Also, having very slow compile times.  Any action on this issue?

**Comment by joeferraro** [comment]
dup of https://github.com/joeferraro/MavensMate/issues/676
