### ISSUE TITLE
Lightning Components through force-cli Problems

### ISSUE THREAD

**Issue by thomasxhoban** [joeferraro/MavensMate#632]
I have hit a roadblock trying to implement MavensMate from within our corporate environment.   It looks like to get features that access lightning components through MavensMate, it needs to post requests through force-cli.  When force-cli tries to login, we get failure because our corporate policy does not (and will not according to our network team) allow internet access from the windows command prompt (even if I beg).

Can you tell me if in the near future road map, if this dependency on force-cli will be removed and if the product will use a more direct way of accessing lightning meta-data.  I can't help but notice that force-cli is not needed for custom objects, fields, classes, triggers, etc.  So why is it needed for lightning?

Are there any other implementation options we can consider for managing lightning components that don't involve force-cli and the windows command prompt?

Thanks,
Tom Hoban

**Comment by joeferraro** [comment]
Hi Tom,

There is no dependency on force-cli, in fact we don't use it at all. Can
you be more specific with the error you're receiving?

**Comment by thomasxhoban** [comment]
We are trying to understand how you can pull lightning components into a mavensmate project.  In searching for help, I stumbled across a package called sublime-lightning.  Sorry I mistakenly thought this was part of the mavensmate offering.  But I see now this is not your package so I apologize. 

However, I am still at a loss of how we can manage lightning components with the base Mavensmate offering.  Can you point us to documentation that shows us the correct way to create, edit, save,... lightning components with Mavensmate?  Thanks.

Tom

**Comment by brosiusad** [comment]
@thomasxhoban which version of MM are you on?  The latest version of the ST plugin (v7.0.0-beta.1) includes tools for creating Lightning components and with my limited experience with them thus far, they seem to be working well for me.

Note in this screenshot both the commands for creating new Lightning component metadata as well as the supporting package.xml structure

![image](https://cloud.githubusercontent.com/assets/2386805/12919193/8dcda4a0-cf08-11e5-84dd-599f84c220f9.png)
