### ISSUE TITLE
moved project folder, now getting an error

### ISSUE THREAD

**Issue by ryanhuff** [joeferraro/MavensMate#633]
I moved a project folder, then changed the default `mm_workspace` property (it's not set at the Project or User level). When I try to save an Apex class, I get a message that says `Could not find project in workspace: [old location]`

I've looked everywhere... Help?

**Comment by ralphcallaway** [comment]
sounds like there is some configuration that wasn't updated

i'd suggest deleting the project and recreating as the quickest route to dealing with this ..

**Comment by ryanhuff** [comment]
Thanks for the quick reply, Ralph. Doesn't seem like this method is
supported anymore:
https://mavensmate.com/Plugins/Sublime_Text/Existing_Projects (complains
that the folder already exists)

**Comment by ralphcallaway** [comment]
did you delete the folder it says exists?

**Comment by ryanhuff** [comment]
No - I'm right clicking on the folder from MM and choosing create project
-- like the page suggests. I really don't want to delete it, as I have the
existing git repo there.

**Comment by ryanhuff** [comment]
I just want to reset this thing... are there any hidden configuration files?

**Comment by ralphcallaway** [comment]
most of it is in the /config folder, you can try just deleting that folder and then doing the right click from folder again ...

my workflow is, download git repo to my workspace, open in sublime text, right click root folder, click mavensmate->create project ... works for me now, but it always seems to give people trouble at first ...

**Comment by ryanhuff** [comment]
finally got it working, but had to recreate the whole project/folder.
thanks fro your responsiveness.

**Comment by ralphcallaway** [comment]
glad that got you going, the original workflow wasn't really designed with source control in mind (it's kind of expecting that the mavensmate ui creates the folder structure which doesn't work for git repos), so it's not ideal, but once you've done it a couple times it's pretty quick
