### ISSUE TITLE
MavensMate on Windows Vista

### ISSUE THREAD

**Issue by geribe** [joeferraro/MavensMate#636]
Hi there 
I installed Sublime Text 3 & MavensMate. Configured it, set the mm_workspace path, but when I want to create a new project it comes up with the following error:
WindowsError: [Error -2146893795] Provider DLL failed to initialize correctly
[MAVENSMATE] failed to send community activity

Please note I am on Vista 32bit, could this be the reason. This as I saw the supported OSes are Windows 7 & up. Am I able to use a previous version to work on a Vista pc? 

Thanks for you response
Trevor

**Comment by joeferraro** [comment]
Unfortunately, we cannot support every OS (this is a fully-volunteer very small team), so Vista is unsupported. Cheers.
