### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by PawelWozniak** [joeferraro/MavensMate#641]
Since 4 months no update and MavensMate app seems to be aboded after issuing v6 which is renamed v4.

I would like to switch to Atom editor but if MM app will not be developed anymore then there is no point to do that.

Joe could you please provide information about future of this project?

**Comment by ralphcallaway** [comment]
with regards to the mm app, i've been using it for the last four months without issue (although not everyone has shared that experience)

i can't speak for joe, but in the past there have been intermittent large pushes for new functionality, this is all done on a volunteer basis, so there is only as much time to work on this as everyones day job allows

**Comment by joeferraro** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/9281517-128929765_6-s4-v1.png?palette=1&width=246)

**Comment by Katulka** [comment]
The MM App and v7 beta of MM have been excellent for 4 months for me as well.
