### ISSUE TITLE
Read-only project? 

### ISSUE THREAD

**Issue by dannybusiness** [joeferraro/MavensMate#642]
Hello,
I was wondering if it was possible to make a project read-only? Essentially, I would like to take weekly snapshots of our production org's metadata using maven's mate and git and not have any risk of updating the org in any way. If that's not possible, could someone let me know what specific commands sequence would allow me to update a project from the server without editing any files on production? I'm using v6 on Windows with Sublime Text. Thanks!

**Comment by ralphcallaway** [comment]
You look at using ant for this, we use it for a daily auto checkout for all
our customers

**Comment by joeferraro** [comment]
agree, i'd use ant/force.com migration tool for this. you could use the mavensmate cli as well to create a project:

```
mavensmate new-project <<< '{ "name" : "myproject", "workspace" : "/path/to/workspace", "username" : "foo@bar.com", "password" : "foo", package: { "ApexClass" : "*" } }'
```
