### ISSUE TITLE
TLS 1.0 Problem

### ISSUE THREAD

**Issue by mvcmania** [joeferraro/MavensMate#645]
Hello, when i attempt to convert existing project to mavensmate project, after i enter my sf credentials , returns me to error message like below :
Server raised fault: 'UNSUPPORTED_CLIENT: TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https.'

Is this something that i can configure in my org or is this a mavensmate bug ?
Thanks

**Comment by bonhomie** [comment]
Have you recently reviewed your org's TLS setting?

**Comment by mvcmania** [comment]
Could you tell me , how can i review my org's TLS setting?

**Comment by bonhomie** [comment]
https://help.salesforce.com/apex/HTViewSolution?urlname=TLS-1-0-Disablement-Critical-Update-Console-CRUC-Setting&language=en_US

**Comment by mvcmania** [comment]
Thanks for the link. I was able to deactivate TLS 1.0 > requirement and convert my project. But mavensmate should handle this at the end , right ?

**Comment by bonhomie** [comment]
Let's hope so, I guess you can tag this post as an enhancement

**Comment by mvcmania** [comment]
as soon as i learn how to do add label, i can do so :)

**Comment by pcmela** [comment]
I have same problem on my OSX system. But I had tested it also on notebook with Windows where on the same sandbox org is everything ok. It seems that it could be dependent on version of python or something, but I have not found the solution already.

**Comment by goarnold** [comment]
I ran into the same issue and was able to resolve it by installing v7 beta. 

Here is the original link to the issue: https://github.com/joeferraro/MavensMate-SublimeText/issues/769

Here is the link to how to install the v7 beta for sublime: https://github.com/joeferraro/MavensMate-SublimeText#version-7-betas

**Comment by joeferraro** [comment]
dup. v7 doesn't use TLS 1.0. stable v7 coming soon
