### ISSUE TITLE
Error creating new project [Error 5] Access is denied

### ISSUE THREAD

**Issue by avisser** [joeferraro/MavensMate#656]
I know it's been around before. I'll give you all the info you want - promise.

Windows 7, SP1 - 64-bit Sublime
MM v6.0.0 - API v0.2.41 (first installed today)
No firewall or proxy - Windows firewall is disabled - no AV

# Steps
I have an existing Eclipse-based Salesforce project w/ Git source control
After creating my workspace directory (`c:/source/mm_workspace`), I right click my Eclipse directory (`c:/source/salesforce`) and go through the New MavensMate project workflow.

After typing in the credentials to my developer account, I'm presented with the error: `[Error 5] Access is denied: u'C:\\\\source\\\\salesforce\\\\.git\\\\objects\\\\00\\\\dd3bda67685453adaf10fa924108d2aaea58b9'`

Here's the stacktrace I see in mmui.log
```
{"body": "[Error 5] Access is denied: u'C:\\\\source\\\\salesforce\\\\.git\\\\objects\\\\00\\\\dd3bda67685453adaf10fa924108d2aaea58b9'", "stack_trace": "Traceback (most recent call last):\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.request\", line 93, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.commands.project\", line 150, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.commands.project\", line 42, in execute\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\mm.project\", line 122, in retrieve_and_write_to_disk\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\shutil\", line 300, in move\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\shutil\", line 247, in rmtree\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\shutil\", line 247, in rmtree\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\shutil\", line 247, in rmtree\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\shutil\", line 252, in rmtree\n  File \"C:\\Users\\Administrator\\Desktop\\ghook\\build\\mm\\out00-PYZ.pyz\\shutil\", line 250, in rmtree\nWindowsError: [Error 5] Access is denied: u'C:\\\\source\\\\salesforce\\\\.git\\\\objects\\\\00\\\\dd3bda67685453adaf10fa924108d2aaea58b9'\n", "success": false}
```

I ended up deleting the `.git` directory to see if there was something special with it, but it then started failing on `salesforce/Referenced Packages`

# My analysis
I'm attaching the ProcMon logs of the error happening. They are in both native ProcMon format and .CSV. I also have a screen shot of the error in ProcMon.

What I see:
* Everything is running as me - I'm almost certain this isn't a permissions error
* I'm not sure why, but it looks like MavensMate is trying to move all of the code from my project dir to the workspace
 * It appears that the "copy all the files to the workspace" part of the move succeeds. I see my project files in the workspace.
 * The failure occurs when "delete the old files" part of the move happens.
 * Here are the Win32 details: ![event properties 2016-03-29 12 41 37](https://cloud.githubusercontent.com/assets/1444364/14116012/c037520a-f5ab-11e5-9524-5767d465608b.png)
 * ![event properties 2016-03-29 12 42 29](https://cloud.githubusercontent.com/assets/1444364/14116062/f312aac6-f5ab-11e5-89ea-9ad55437d77d.png)
 
If I had to guess, I'd say that a reference to the file is still being held by mm.exe, making the delete fail. What I don't understand is why the file is being deleted at all. 

ProcMon logs:
[mm_procMon.zip](https://github.com/joeferraro/MavensMate/files/193873/mm_procMon.zip)

**Comment by cferr59** [comment]
I had the same issue. Creating a new project uses Python's shutil.rename() function to move the source to the destination folder (line 122 of project.py in the mm project).  For whatever reason, I believe the Windows search indexer (searchprotocolhost.exe) is interfering with this operation and it is not reliable. 

I ended up switching to MavensMate 7 for SublimeText (prerelease) which uses the node.js based MavensMate-app instead of the older Python based mm project.

**Comment by joeferraro** [comment]
Hey guys, I'm no longer supporting the python-based mm executable, not because I don't love you guys, but because I only have so much time in the day :) Hopefully this isn't an issue in the node-based MavensMate-app.

**Comment by cferr59** [comment]
This works fine in the node based version.  It seems isolate to the Python implementation on Windows.
