### ISSUE TITLE
How do I compile a single file?

### ISSUE THREAD

**Issue by christianbundy** [joeferraro/MavensMate#661]
I'm working on a large project that takes a couple minutes with `compile-project` on the command-line, is there a way to only compile the files that I've changed? Thanks!

**Comment by joeferraro** [comment]
two ways:

`cd /my/project/path`

(single)
```
mavensmate compile /path/to/metadata.cls
```

(multiple)
```
mavensmate compile <<< '{ "paths" : [ "/path/to/MyTestClass.cls", "/path/to/MyTestClass2.cls" ] }'
```

**Comment by christianbundy** [comment]
@joeferraro Thanks, is this documented somewhere or should I add it? Cheers!

**Comment by joeferraro** [comment]
@christianbundy np. it's listed in the readme, but will add the multiple paths as well
