### ISSUE TITLE
write EPROTO

### ISSUE THREAD

**Issue by lifewithryan** [joeferraro/MavensMate#662]
Trying to either refresh an existing project or re-check it out all together and I'm getting  a "write EPROTO"  error. There are no further details with said error on the screen.
![screen shot 2016-04-22 at 9 26 33 am](https://cloud.githubusercontent.com/assets/334111/14744422/59118932-086c-11e6-9a99-e803b00d0422.png)

This is only happening with one of my orgs so far. Other orgs/projects seem to be working just fine, but because the error is so vague, I'm having a hard time tracking down what is blowing up. I am using Mavensmate v0.0.10 with the latest version of sublime on a Macbook Pro running El Capitan. This just started happening...

**Comment by joeferraro** [comment]
seems to be an open node issue. i'm going to close here as there's nothing to do until they resolve it over there. i've subscribed to the issue in the meantime https://github.com/nodejs/node/issues/3692
