### ISSUE TITLE
Compile hangs for specific class

### ISSUE THREAD

**Issue by ChuckJonas** [joeferraro/MavensMate#665]
I'm running into an issue where I can't seem to compile a single class.  Other classes and meta-data types seem to compile fine.  I can also save the class using the developer console without issue.

I've loaded Mavensmate up in the debugger and I've tracked down where I think the issue is happening but not sure how to debug further.

The issue seems to be that the Promise on line 292 of _checkConflicts (lib/mavensmate/compiles.js) never executes it's "then" function.

![screen shot 2016-05-06 at 12 51 45 pm](https://cloud.githubusercontent.com/assets/5217568/15083309/b33cdaa6-1389-11e6-817f-2353351a80ad.png)

_Breakpoint on line 394 is never hit when compiling one of my classes._

Please let me know if there is any other information I can give you.

**Comment by ChuckJonas** [comment]
Figured it out (sorta)... seem like a bit of a WTF.

The query in file.js "serverCopy" file isn't returning any rows.  Here's were it starts to get weird...

The file that won't compile is **QuoteController2**.

When I run the SOQL generated on line 337, I get no results.  
![screen shot 2016-05-06 at 1 34 35 pm](https://cloud.githubusercontent.com/assets/5217568/15084218/56b04cc2-138f-11e6-8d24-ebf2414e33ee.png)

However, I can confirm the file does exist in the system, but for some reason querying based on the name doesn't return it...
![screen shot 2016-05-06 at 1 33 08 pm](https://cloud.githubusercontent.com/assets/5217568/15084201/390217b4-138f-11e6-9137-4bafea1a0695.png)

Seems like a SF platform bug.

**Comment by ChuckJonas** [comment]
Also, Unchecking "Check conflicts before compile (mm_compile_check_conflicts)" will allow the file to save

**Comment by joeferraro** [comment]
merged PR, thx
