### ISSUE TITLE
connect ETIMEDOUT issue when refreshing from server

### ISSUE THREAD

**Issue by murray245** [joeferraro/MavensMate#668]
Hi

I am not technical so going to try and explain this simply. I have installed the upgrade to Sublime today and updated the MavensMate plugin to V7. Then installed the MavensMate App and logged in successfully to my salesforce org. When trying to refresh from server I get the error: connect ETIMEDOUT 

Please can you assist?

**Comment by JJHarry** [comment]
murray245, 

I've gotten a connection timeout error many times when working from work, and its because I am behind a proxy. In order to allow MM and Sublime to get out of your network you will need to configure the proxy settings in your mavens mate user settings. You can obtain your proxy settings from your company sys admin.  

Let me know if that doesn't solve your error.

**Comment by murray245** [comment]
Hi

Thanks so much for teh reply. I am not on a company proxy but have figured
out that it was my UAC settings that were blocking this.


Regards,

Taryn Murray

Agilitude Consultant

"What would you do if you had *more time*?"

+27113125625

+27832711501 <%2B27823201653>

taryn.murray@agilitude­.co.za <russell@agilitude.co.za>

www.agilitude­.co.za <http://www.agilitude.co.za/>


[image: Certif Admin]

**Comment by murray245** [comment]
Hi

It seems i am still receiving this error. I am working from a home internet
connection with no proxy settings. My UAC is turned off and I have even
tried turning my firewall off to see if this resolves the issue, but it
does not and i still receive this error. I have turned off my anti virus
and this also does not allow me through. Please advise soonest

[image: Inline images 1]
[image: Inline images 2]


Regards,

Taryn Murray

Agilitude Consultant

"What would you do if you had *more time*?"

+27113125625

+27832711501 <%2B27823201653>

taryn.murray@agilitude­.co.za <russell@agilitude.co.za>

www.agilitude­.co.za <http://www.agilitude.co.za/>


[image: Certif Admin]

**Comment by JJHarry** [comment]
It doesn't look like  your pictures are showing up. Also, what version are you using?

**Comment by murray245** [comment]
Hi

I am using sublime text 3, with mavens mate v7 and the mavens mate app is
v0.0.11-beta1.

Yesterday when it worked I was on a customers network and when I turned uac
off it worked. Now on my own network, which is really unsecured it doesn't
work

Regards
Taryn


On Thursday, 19 May 2016, JJ Harry <notifications@github.com> wrote:

> It doesn't look like your pictures are showing up. Also, what version are
> you using?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joeferraro/MavensMate/issues/668#issuecomment-220339620>
>


-- 
Regards, Taryn Murray

**Comment by JJHarry** [comment]
Do you get the error when you are trying to create a project? When I was receiving the error that was when I got it.

**Comment by murray245** [comment]
Hi

I only get this error when refreshing a current project. So, i have a
current open project and when I choose refresh from server in the app it
gives me that error


Regards,

Taryn Murray

Agilitude Consultant

"What would you do if you had *more time*?"

+27113125625

+27832711501 <%2B27823201653>

taryn.murray@agilitude­.co.za <russell@agilitude.co.za>

www.agilitude­.co.za <http://www.agilitude.co.za/>


[image: Certif Admin]
