### ISSUE TITLE
All static resources not being pulled

### ISSUE THREAD

**Issue by iDev0urer** [joeferraro/MavensMate#671]
I am working in an org that has in excess of 150 static resources. Not all of them should be pulled, and they aren't when using an IDE like Welkin (which I hate). MavensMate is only pulling 20 of them

**Comment by iDev0urer** [comment]
Seems like the resources that aren't being pulled are ones that have a prefix and a suffix. Ex CC_Assets_CW

**Comment by joeferraro** [comment]
are those managed static resources?

**Comment by iDev0urer** [comment]
No they aren't, and after some more digging it looks like it's not pulling in pages that have a prefix and suffix either. We have a lot of files like that in our org that are branched with the CC prefix, a name, and  a suffix of the user's initials.

**Comment by iDev0urer** [comment]
Although when I try an add a new resource that doesn't have the prefix/suffix and then refresh the staticresources folder I don't get anything new

**Comment by joeferraro** [comment]
Hm, not sure, I'll need more information to diagnose it, including logs.

**Comment by iDev0urer** [comment]
I figured it out by using the `Project Metadata` tab when creating my project. It just didn't download the files I needed by default for some reason
