### ISSUE TITLE
Nobody panic. Salesforce is deprecating TLS 1.0

### ISSUE THREAD

**Issue by aklef** [joeferraro/MavensMate#678]
This is a Xpost from https://github.com/joeferraro/MavensMate-SublimeText/issues/800

I've been getting the exact error as seen below, linked from https://github.com/joeferraro/MavensMate-SublimeText/issues/797 as of today.
> ERROR:suds.client: {SF_USERID} {SF_PASSWORD} {"body": "Server raised fault: 'LOGIN_DURING_RESTRICTED_DOMAIN: cannot log in from current domain'", "stack_trace": "Traceback (most recent call last):\n File \"C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.request\", line 93, in execute\n File \"C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.commands.project\", line 39, in execute\n File \"C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.project\", line 112, in retrieve_and_write_to_disk\n File \"C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.sfdc_client\", line 96, in init\n File \"C:\Users\Administrator\Desktop\ghook\build\mm\out00-PYZ.pyz\mm.sfdc_client\", line 110, in login\nWebFault: Server raised fault: 'LOGIN_DURING_RESTRICTED_DOMAIN: cannot log in from current domain'\n", "success": false} 

Esentially, this: https://help.salesforce.com/apex/HTViewSolution?id=000221207 is happening.

See https://help.salesforce.com/apex/HTViewSolution?urlname=TLS-1-0-Disablement-Critical-Update-Console-CRUC-Setting&language=en_US

#645  was created as part of this change and the listed solution was as follows:

> goarnold commented on Mar 10
> I ran into the same issue and was able to resolve it by installing v7 beta.
> 
> Here is the original link to the issue: joeferraro/MavensMate-SublimeText#769
> 
> Here is the link to how to install the v7 beta for sublime: https://github.com/joeferraro/MavensMate-SublimeText#version-7-betas

Meaning that MavensMate itself needs to be upgraded to v7 everywhere PRONTO.

These issues from the MavensMate-SublimeText repo are all related to this
https://github.com/joeferraro/MavensMate-SublimeText/issues/799
https://github.com/joeferraro/MavensMate-SublimeText/issues/797
https://github.com/joeferraro/MavensMate-SublimeText/issues/769

**Comment by joeferraro** [comment]
v7 does not use TLS1.0 and a stable v7 is on the way
