### ISSUE TITLE
Client[commandClassName] is not a function - error while trying to create a new project

### ISSUE THREAD

**Issue by digamberprasad** [joeferraro/MavensMate#679]
Hi,

I have installed MavensMate version 7 and while trying to create a new project it's giving me error "Client[commandClassName] is not a function". I am using it on Mac. Any help is highly appreciated.

Regards

**Comment by mhenris** [comment]
Same here.  :(

**Comment by joeferraro** [comment]
https://github.com/joeferraro/MavensMate/commit/e97f69304503658fa45b856faba136fba7f81ae2

**Comment by mhenris** [comment]
I see that this ticket is resolved but is there a new build with the fix?  I'm locked in jail currently and can't start new projects :(

**Comment by joeferraro** [comment]
this when into 0.0.47 https://github.com/joeferraro/MavensMate/commit/1cd25303195991599d8ccdd15e6d73fa1fca50a7

**Comment by mhenris** [comment]
Yay!
