### ISSUE TITLE
Polling Time-out on all deployments from v7 Beta

### ISSUE THREAD

**Issue by gefiltepez** [joeferraro/MavensMate#683]
I cannot deploy using the new Maven's Mate beta

- OSX
- v0.0.10 (app), v7 (plugin)
- Yes I am behind a firewall
- Steps to reproduce:  attempt any deployment from any sandbox into production
- Saleforce server NA15

[Screenshot](http://i.imgur.com/hRZq90F.png)

**Comment by joeferraro** [comment]
How long are these deployments?

**Comment by joeferraro** [comment]
https://github.com/joeferraro/MavensMate/commit/a33f547b1f24cfdffc5a843b5adec46acb599a69 attempts to resolve. please try with 0.0.11-beta.3 and re-open if it persists. thanks!
