### ISSUE TITLE
Resource Not Found. Response content: [{u'errorCode': u'NOT_FOUND', u'message': u'The requested resource does not exist'}]

### ISSUE THREAD

**Issue by sdhaliwal16** [joeferraro/MavensMate#684]
I am not able to create a new project on MavenMate. The following error is shown: 
Resource Not Found. Response content: [{u'errorCode': u'NOT_FOUND', u'message': u'The requested resource does not exist'}]

**Comment by pbattisson** [comment]
This typically happens when you are trying to access a resource you do not have permissions for. Have you checked:

- Correct username/password/security token
- Correct org type
- Your user is able to connect via the API

Can you also check what version of MM, what plugin etc. you are using?

**Comment by sdhaliwal16** [comment]
//set to desired Salesforce.com API version (tooling api functionality requires 27.0+)
	"mm_api_version" : "35",
Password/username/token is correct. 
I am able to authenticate 

MavensMate v6.0.0

**Comment by joeferraro** [comment]
We're no longer supported v6 as it's using TLS 1.0, which is no longer supported by Salesforce for security purposes. Please update to v7 and re-open this issue if it persists. Cheers
