### ISSUE TITLE
Resource Not Found. Response content: [{u'errorCode': u'NOT_FOUND', u'message': u'The requested resource does not exist'}]

### ISSUE THREAD

**Issue by sdhaliwal16** [joeferraro/MavensMate#685]
I am not able to create a new MavenMate Project. The following error is being displayed: 

Resource Not Found. Response content: [{u'errorCode': u'NOT_FOUND', u'message': u'The requested resource does not exist'}]

**Comment by pbattisson** [comment]
Closing duplicate of #684
