### ISSUE TITLE
Unit Test Results not displaying

### ISSUE THREAD

**Issue by tylerzika** [joeferraro/MavensMate#688]
I have v0.0.10

When I run a test it tells me if it passes or fails, but doesn't show anything else (class coverage & trigger coverage)
<img width="996" alt="screen shot 2016-07-08 at 4 00 41 pm" src="https://cloud.githubusercontent.com/assets/1011888/16703770/3dc33072-4525-11e6-9488-5cb5daae8d96.png">

<img width="990" alt="screen shot 2016-07-08 at 4 01 01 pm" src="https://cloud.githubusercontent.com/assets/1011888/16703772/419bb214-4525-11e6-9150-832b7f1843fc.png">

**Comment by pbattisson** [comment]
Dumb question, but you have clicked the dropdown icon next to where it says "Test Results" yeah? Thats where you get the choice to see coverage etc.

**Comment by pbattisson** [comment]
Closing as no response from @tylerzika - please reopen if the problem is still occurring.

**Comment by chriskarpyszyn** [comment]
I also do not see Class Coverage as well. I click the drop down icon in Test Results, and when I select Class Coverage, all I get is a search bar.

**Comment by joeferraro** [comment]
@chriskarpyszyn is this your issue? https://github.com/joeferraro/MavensMate/issues/727

**Comment by chriskarpyszyn** [comment]
No. I synced my meta data and also checked that option listed in #727. I'm on a Windows 8 laptop. 

Is there any more details I can provide to help debug?
