### ISSUE TITLE
disable auto-deploy, save files locally?

### ISSUE THREAD

**Issue by yperez** [joeferraro/MavensMate#689]
Is there a way to disable auto-deploy to server on save with mavens mate?
I'm working with a git repo and sometimes need to make local changes to my files without wanting to push them to the sandbox. 
Is there any way I can just save them locally and deploy when I'm ready using "deploy to server"?

Thanks for your help!

**Comment by pbattisson** [comment]
Have a look at User Plugin Settings under the settings menu and change 
```"mm_compile_on_save" : true```
to 
```"mm_compile_on_save" : false```
