### ISSUE TITLE
Error initializing project: Could not start system streaming listener: Cannot read property 'NodeHttp' of undefined

### ISSUE THREAD

**Issue by rkmalik** [joeferraro/MavensMate#692]
I am facing this issue while refreshing the project from the server or I am trying to save to server. 

Though it is creating a new project form the server successfully. Same it fails to refresh from the server again. 

I have also checked the mm_workspace location that is correct. 

localhost:56248/app/home.. 

Thanks in advance.

**Comment by Katulka** [comment]
I am having the same issue.  I just updated to v0.0.11-beta4 MM app.  Upon 2nd open of the MM app I am getting this error:

![10_17_33-error](https://cloud.githubusercontent.com/assets/6976559/17591719/55672d1c-5fad-11e6-84b3-340ca69ac962.png)

**Comment by joeferraro** [comment]
Hey guys, appreciate the enthusiasm, but these beta builds are for testing
only, as you can see in the release notes. Please download the latest
stable build
https://github.com/joeferraro/MavensMate-app/releases/tag/v0.0.10

**Comment by joeferraro** [comment]
i promise we'll have a stable release soon 👍

**Comment by Katulka** [comment]
Anytime!  I'm more of a guinea pig as I'm not doing as much development.... so no worries here I'll always test :)  

I'd suggest that the messaging at the top or the MM app "New version ... is available"  be disabled for beta builds.  You are going to have people assuming, not realizing, etc... who install and have issues.  Save yourself that headache.
