### ISSUE TITLE
v0.0.11-beta.1 Can't scroll-x on test results

### ISSUE THREAD

**Issue by kylethornton** [joeferraro/MavensMate#702]
v0.0.11-beta.1

Sublime Text 3

OS X 10.11.6

No

Run unit tests that fail. if the window isn't wide enough you can't see results without making window wider. Should be able to scroll the test results horizontally.

<img width="877" alt="mavensmate_and_new_issue_ _joeferraro_mavensmate" src="https://cloud.githubusercontent.com/assets/757939/18275298/4293267a-7414-11e6-9d8d-7fb787b70dcd.png">

**Comment by kylethornton** [comment]
This seems like there is also a text wrapping issue here. wrapping the text might solve the issue as well but I think you still might need to be able to scroll as well. ideally (personal opinion) the info before the stack trace would wrap and the stack trace itself would not.

**Comment by joeferraro** [comment]
yeah i'm going to wrap the table cols and we should be ok

**Comment by joeferraro** [comment]
available in https://github.com/joeferraro/MavensMate-Desktop/releases/tag/v0.0.11-beta.2

**Comment by kylethornton** [comment]
While we can now scroll on the coverage results, still can't scroll right on a failed test (see previous screenshot). You will need to create a test that fails in order to test it.

**Comment by joeferraro** [comment]
@kylethornton mind confirming whether this is good to go?

**Comment by kylethornton** [comment]
All good.
