### ISSUE TITLE
View Manager: Closing all views and view manager modal leaves you stuck.

### ISSUE THREAD

**Issue by kylethornton** [joeferraro/MavensMate#704]
Version : v0.0.11-beta.1

SublimeText 3

OS X 10.11.6

N/A

- Open view manger
- Close all views
- Close view manager modal

Left with blank screen. #

**Comment by joeferraro** [comment]
Available in https://github.com/joeferraro/MavensMate-Desktop/releases/tag/v0.0.11-beta.2
