### ISSUE TITLE
Unable to see code coverage for a class.

### ISSUE THREAD

**Issue by abhidotnet** [joeferraro/MavensMate#707]
* **MavensMate-App Version**:v0.0.10 
* **MavensMate Version**:v7.0.0

* **Editor**:Sublime Text

* **Platform/Version**:Windows 7 64-bit

* **Proxy Details**:No.

* **Salesforce Server**:cs27

I am no longer able to see the code coverage for an individual class. The menu option has been replaced with the Org Wide Coverage menu option.

**Comment by joeferraro** [comment]
bug is: https://github.com/joeferraro/MavensMate-SublimeText/blob/master/lib/response_handler.py#L333
