### ISSUE TITLE
Could not create Trace Flags: LogType is required.: LogType

### ISSUE THREAD

**Issue by harshal-gajare** [joeferraro/MavensMate#714]
MM for ST 7.0.0
MM-app v0.0.10
mm_api_version v37.0

SublimeText 3

Mac OS X 10.11.6

No Proxy

CS44/Any server

Mavensmate Menu -> Debugging -> Start logging issues the error 

Could not create Trace Flags: LogType is required.: LogType

Also, trying to execute Anonymous Apex via Execute apex gives the same errror message in the MM app

No logs are being generated

**Comment by harshal-gajare** [comment]
This works with SF API version 34 but fails from 35 onwards.

**Comment by joeferraro** [comment]
@harshal-gajare cheers for the report. This is patched in the upcoming v0.0.11-beta.2
