### ISSUE TITLE
Unable to verify first certificate

### ISSUE THREAD

**Issue by esthere** [joeferraro/MavensMate#716]
* **MavensMate Version**: 7

* **Editor**: Sublime

* **Platform/Version**:Windows 10 64bit

* **Proxy Details**:none

* **Salesforce Server**:cs3

Since I had to upgrade to Mavens Mate 7, I am unable to connect to my sf account. I am getting the error "Error initializing project: unable to verify the first certificate". I have tried uninstalling and re-installing, I have tried installing the beta version and the full release version. How can I resolve this issue? I have both Sublime Text and Mavens Mate desktop app running.

**Comment by joeferraro** [comment]
@esthere appreciate the bug report and I'm sorry you're running into this issue. Give [0.0.11-beta.2](https://github.com/joeferraro/MavensMate-Desktop/releases) a try and see if your issue persists. Cheers.

**Comment by esthere** [comment]
I did, no luck.

**Comment by joeferraro** [comment]
Related: https://github.com/Microsoft/vscode/issues/155

**Comment by esthere** [comment]
I tried adding in "http.proxyStrictSSL": false 

to my user settings, and no luck.

Thanks so much for your time!

Do you have any other suggestions?

**Comment by joeferraro** [comment]
@esthere I think we're going to need to configure the underlying http transport to allow non-strict SSL https://github.com/joeferraro/MavensMate/issues/721
