### ISSUE TITLE
Can't save apex class

### ISSUE THREAD

**Issue by Galexanra** [joeferraro/MavensMate#722]
* **MavensMate Version**: MavensMate-app v0.0.10

* **Editor**: sublime text v7.0.0

* **Platform/Version**: Windows 7 32-bit

* **Proxy Details**: 

* **Salesforce Server**: eu6

 Cann't save apex class: it's try to save it, I see the progress runner, but it can't. And it is trying until I stop it. Reloading metadata, reinstall mavensmate didn't help.
![image](https://cloud.githubusercontent.com/assets/22210416/18539580/2161b8ea-7b21-11e6-9b6b-3ccfb990ccc4.png)

**Comment by joeferraro** [comment]
Please re-test with https://github.com/joeferraro/MavensMate-Desktop/releases/tag/v0.0.11-beta.3

**Comment by Galexanra** [comment]
Thank you, so I re-test it with this version and get error:  Result: [ERROR]: Server copy query returned no results: Select LastModifiedById, LastModifiedDate, LastModifiedBy.Name, Body From ApexClass Where Name = 'CreateSaleOpportunityController'

**Comment by joeferraro** [comment]
@Galexanra does that ApexClass exist in the org you're connecting to? This error message is common when you attempt to compile metadata that does not exist in the org.

**Comment by Galexanra** [comment]
yes, it exists and I can compile it in developer console

**Comment by joeferraro** [comment]
`Select LastModifiedById, LastModifiedDate, LastModifiedBy.Name, Body From ApexClass Where Name = 'CreateSaleOpportunityController'` this is a SOQL query performed against the org you're connected to. It's returning 0 results. Are you sure you've authenticated to the correct environment? This error is very common when you have a project with local metadata that is not from the org you've authenticated to.

**Comment by Galexanra** [comment]
I'm sure, because I compile another classes from this organization and it's ok

**Comment by joeferraro** [comment]
Ok, without a debug log, it's difficult to debug this issue, because the server response is saying that ApexClass does not exist. Please generate a log and upload to this issue. Thanks.
 
<img width="793" alt="mavensmate" src="https://cloud.githubusercontent.com/assets/54157/18585509/523d95d2-7be5-11e6-9a0c-d012ea344818.png">

**Comment by Galexanra** [comment]
It's not save any logs

**Comment by Galexanra** [comment]
Finally, I removed this apex class and created it again with the same name. Now, It normally works. Thanks for your attention

**Comment by joeferraro** [comment]
@Galexanra I actually reproduced this issue on an Apex Class in one of my dev orgs while debugging with @kidtsunami. For whatever reasons, the server was not returning the Apex Class in a SOQL query by id, but when we searched using LIKE or for all Apex Classes, it was returned. Seemed like a server bug/anomaly and not much we could do to resolve it other than delete/recreate it as you have done.
