### ISSUE TITLE
Issue of  Version*0.0.11-beta.3*:

### ISSUE THREAD

**Issue by sanjuoo7** [joeferraro/MavensMate#723]
* **MavensMate Version*0.0.11-beta.3*:

* **Sublime**:

* **Windows 10 64 bit**:

* **Proxy Details**:

* **Salesforce Server**:

Issue 1.) Unable to create multiple projects(two projects on sandbox) on mavensmate as after creating a project it store the information (OAuth) so couldn't allow to enter credentials for other projects.

issue 2.) Could not able to get back to mavensmate home page from OAuth page.

**Comment by joeferraro** [comment]
Hi @sanjuoo7, not sure what you mean by "create multiple projects", but https://github.com/joeferraro/MavensMate-Desktop/releases/tag/v0.0.11-beta.4 has added browser controls (back/forward/reload) to OAuth pages to make sure you can navigate away if necessary.

**Comment by sanjuoo7** [comment]
Hello @joeferraro , all issues raised are closed thanks for providing great salesforce IDE.

**Comment by joeferraro** [comment]
cheers @sanjuoo7
