### ISSUE TITLE
MM-app : Deploy to server not working 

### ISSUE THREAD

**Issue by harshal-gajare** [joeferraro/MavensMate#725]
MavensMate Version: v7.0.0 , mm-app 0.0.11-beta3

Editor: ST

Platform/Version: OS X

Proxy Details: None

Salesforce Server: CS44 , api v36

When deploying to server I get a error message of "expired access/refresh token" . No logs are generated. Tried closing the app and starting it back up again.

**Comment by joeferraro** [comment]
@harshal-gajare did you try to delete/re-create your deployment connection?

**Comment by harshal-gajare** [comment]
@joeferraro I did when I started using the beta-2 version but did not after downloading and using beta-3. I am going to delete the connections and try again.

**Comment by harshal-gajare** [comment]
@joeferraro so deleting and re-adding the connections worked. 👍
