### ISSUE TITLE
MM-app v.0.0.11-beta.2: Class coverage is not displayed running Unit Tests

### ISSUE THREAD

**Issue by fracarma** [joeferraro/MavensMate#727]
* **MavensMate Version**: 0.0.11-beta.2

* **Platform/Version**: Windows 7

When run Unit Test, not Class Coverage nor Trigger Coverage are displayed. The Server and Client Console don't display any error.

![testerr1](https://cloud.githubusercontent.com/assets/12348998/18553893/98eecd12-7b62-11e6-862a-c7d3a15c88f6.PNG)

![testerr2](https://cloud.githubusercontent.com/assets/12348998/18553896/9d8c804e-7b62-11e6-91d5-de649e7edf7c.PNG)

**Comment by joeferraro** [comment]
Are you subscribed to all ApexClasses in your org?

**Comment by fracarma** [comment]
Yes. That is the situation after a `Refresh Metadata Index`:

![testerr3](https://cloud.githubusercontent.com/assets/12348998/18554719/66ae933e-7b65-11e6-8436-60c49ec4a780.PNG)

**Comment by fracarma** [comment]
Ok, I have tried with another project and the class coverage is displayed. I will try to figure out what is going on with that particular project.

**Comment by fracarma** [comment]
Ok, I have found the problem. On the SalesForce Sandbox I was working on there were enabled an option for the Test Execution:

![testerr4](https://cloud.githubusercontent.com/assets/12348998/18555725/26b24646-7b69-11e6-8db9-c2d0b184e131.PNG)

So, @joeferraro sorry for bother. An enhancement could be to display a warning if this option is selected maybe (if it is possible to know using SF API).

**Comment by joeferraro** [comment]
ah very interesting. thanks!

**Comment by epohlabel** [comment]
I am not seeing my code coverage from the test runner UI. I have checked the Apex Execution options in the org per the above comment and NONE of the options are enabled. I am able to see that the test passed - but there is no indication of coverage whatsoever. 
![image](https://cloud.githubusercontent.com/assets/22889260/19440058/7183541e-944e-11e6-8f76-60a79ba011bd.png)

**Comment by mir701** [comment]
@epohlabel  hey, not sure if you have solved this. I ran into same issues and after went thru all the related issues, i found out the reason. so 1. Store Only Aggregated Code Coverage must be Unchecked, 2. You have to subscribe to all ApexClass in your org which is shown above.

**Comment by mch1234** [comment]
I am having the same issue as described before. I am subscribed to all Apex Classes ( just means checking every box and updating project, right?) and the checkbox Store Only Aggregated Code Coverage in unchecked in SF.

I am not getting any errors there is just nothing shown for code coverage. Only pass/fail.

Any suggestions?

**Comment by AdamB1** [comment]
Having this issue - even though the [ ] Store only ... checkbox is unticked, and have checked all Project Metadata

**Comment by n00bed** [comment]
How do you subscribe to all Apex classes?

**Comment by n00bed** [comment]
I am still having the issue as well. I have done both the steps, checking the box and checked all Project Metadata.

**Comment by fracarma** [comment]
@AdamB1 @mch1234 
if a test doesn't cover any Apex Class or Trigger, the coverage is not displayed. Checking with the developer console could you see any class covered by your tests?

**Comment by jrr700** [comment]
I just started using Mavensmate and have this very same issue.. Are we all doing something wrong?  I have followed the steps above but no luck.. The Developer Console works fine.

**Comment by jrr700** [comment]
I only get code coverage when it is 100% now...
