### ISSUE TITLE
Unable to open existing project

### ISSUE THREAD

**Issue by mdorus** [joeferraro/MavensMate#728]
* **MavensMate Version**: 7.0.0

* **Editor**: Sublime Text 3

* **Platform/Version**:Windows 10 64-bit

* **Proxy Details**:No

* **Salesforce Server**:cs13

Hello,  When after updating MavensMate to 7, I cannot open any existing projects.    I select the project I want from my list of projects and I get this error: "MavensMate is unable to connect to Salesforce. Please re-authenticate to continue."    I select the environment as Sandbox and click 'Connect' which brings up the login window.  I enter my password and get the following error: 'Please check your username and password. If you still can't log in, contact your Salesforce administrator.'    

I know the password is correct because I can log in through the normal Salesforce UI, Eclipse, and Workbench.

**Comment by fracarma** [comment]
@mdorus Are you trying to login in a sandbox environment? At the moment (for sure on the MM-app v.0.0.11-beta2) if you select the *Sandbox* option for *Salesforce Environment Type* on the Update Project Credentials page, the system points at the wrong URL (http://login.salesforce.com).

A workaround is to select *Custom URL* for *Salesforce Environment Type* and insert the URL `https://test.salesforce.com`:

![workaroundmm](https://cloud.githubusercontent.com/assets/12348998/18556027/5d54a706-7b6a-11e6-97c2-650579356f5a.PNG)

That works for me

**Comment by mdorus** [comment]
@fracarma thanks for the quick reply.   You're solution worked for me.

**Comment by joeferraro** [comment]
fyi @mdorus @fracarma 0.0.11-beta.3 resolves the sandbox dropdown issue
