### ISSUE TITLE
MM-app : Cancel button does nothing 

### ISSUE THREAD

**Issue by harshal-gajare** [joeferraro/MavensMate#730]
* **MavensMate Version**: mm-app v0.0.11-beta.3

* **Editor**: ST

* **Platform/Version**: OS X 

* **Proxy Details**: none

* **Salesforce Server**: any

The cancel button on the various MM-app views like , deploy, run tests dosen't do anything. Not sure if this is a bug or something still under development. Can that be updated to just navigate back to the Project Home view ?

**Comment by joeferraro** [comment]
@harshal-gajare you're right, it does nothing right now :) but yes, I think it should navigate back to the project home view

**Comment by harshal-gajare** [comment]
@joeferraro  great ... btw I am loving the new re-invented/re-designed MM so to speak .. great job as always !

**Comment by harshal-gajare** [comment]
@joeferraro tested this with v.0.0.11-beta5 and works great
