### ISSUE TITLE
[Bug]: Installation Splash Image Does Not Automatically Close

### ISSUE THREAD

**Issue by lynnellemmanuel** [joeferraro/MavensMate#742]
* **MavensMate Version**: v0.0.11-beta4

* **Editor**: N/A

* **Platform/Version**: Windows 8.1 64-bit

* **Proxy Details**: N/A

* **Salesforce Server**: N/A

Just install MavensMate v0.0.11-beta4 and you'll see that the "Installing" splash image keeps in the background even though the installation process is already done.

![screenshot 48](https://cloud.githubusercontent.com/assets/7625546/18574171/ff64e096-7bfc-11e6-9a35-0b903674829b.png)

**Comment by joeferraro** [comment]
Hm, certainly have never seen this before.

**Comment by lynnellemmanuel** [comment]
Just install MavensMate Version v0.0.11-beta4 in Windows 8.1 64-bit and you'll reproduce the bug.

**Comment by lynnellemmanuel** [comment]
I've installed v0.0.11-beta 5 and the bug is now gone.
