### ISSUE TITLE
OAuth Problem?

### ISSUE THREAD

**Issue by billdunigan** [joeferraro/MavensMate#743]
7.0.1

Sublime

Windows 10 64-bit

No

CS2

I select Mavensmate/Project/New Project from SublimeEdit menu
New login popup box appears.
I enter "Sandbox" for environment and click "Connect"
A login screen appears
I enter my sandbox userid and password
I get a login failure, please see attached screenshot
![capture](https://cloud.githubusercontent.com/assets/10727533/18631677/5ecc9efc-7e41-11e6-8fb4-c9f02b63b9b9.JPG)

**Comment by joeferraro** [comment]
This was a known issue that has been patched since [v0.0.11-beta.3](https://github.com/joeferraro/MavensMate-Desktop/releases/tag/v0.0.11-beta.3). What version of Desktop are you running?

**Comment by joeferraro** [comment]
Given the screenshot depicts the Oauth screen without browser navigation, this version of Desktop is older than v0.0.11-beta.3. Closing for now. @billdunigan please feel free to re-open if v0.0.11-beta.3+ does not solve you issue. Cheers
