### ISSUE TITLE
"Could not retrieve DebugLevel: sObject type 'DebugLevel'" on Excute Apex error in Desktop App

### ISSUE THREAD

**Issue by ajfrederick** [joeferraro/MavensMate#749]
* **MavensMate Version**: 7.0.1

* **Editor**: Sublime Text 3

* **Platform/Version**: Windows 10 64-bit

* **Proxy Details**: none

* **Salesforce Server**: na24

Execute Anonymous produces this error in Desktop app:

Error: Could not retrieve DebugLevel: sObject type 'DebugLevel' is not supported.

**Comment by joeferraro** [comment]
What version of the Salesforce API are you running? What version of Desktop are you running?

**Comment by ajfrederick** [comment]
API: v34
Desktop: beta.5

**Comment by ajfrederick** [comment]
or rather 0.0.11 beta.5. The newest version as of today.

**Comment by joeferraro** [comment]
@ajfrederick cheers. DebugLevel was introduced in v36 I believe. Please update your Desktop Salesforce API version accordingly. Unfortunately, it's incredibly difficult to maintain backwards compatibility with every Salesforce API change, so the solution is to keep your API version current. Thanks.

**Comment by ajfrederick** [comment]
Thanks for the speedy reply and I will keep it updated from now on but unfortunately I'm getting the same error after updating.

**Comment by joeferraro** [comment]
did you restart the app?

**Comment by ajfrederick** [comment]
Ah of course! I just did but now we have this:

Error: Could not create Trace Flags: This entity is already being traced by a trace flag with a start and expiration date that overlap this trace flag's start and expiration date.: Traced Entity ID

**Comment by joeferraro** [comment]
@ajfrederick that's a Salesforce server error that prevents duplicate Trace Flags. You may have set Trace Flags in another app (dev console, as an example). Run the Stop Logging command in  Sublime which will clear Trace Flags that you've created for your user. Then run the Start Logging command to start listening for streaming logs again.

**Comment by ajfrederick** [comment]
Awesome! After trying various things Clearing the trace flags in the dev console with the query editor with use tooling API set to true did it. Thanks for everything, Joe. You're doing the lawds work. Really awesome support.

**Comment by joeferraro** [comment]
cheers @ajfrederick

**Comment by vaclavlukasek** [comment]
I have same issue, stop debuging / stop logging work fine
Result: Success: Stopped logging for debug users
but even when I run debuging / start debuging, it fail again with same error 
Result: [ERROR]: Could not retrieve DebugLevel: sObject type 'DebugLevel' is not supported.

**Comment by FinnArild** [comment]
Yes. Same issue here with API version 36 and flushing debug logs.
