### ISSUE TITLE
Can't create New Project.  Redirect to SSO for different client.

### ISSUE THREAD

**Issue by ChuckJonas** [joeferraro/MavensMate#752]
- **MavensMate Desktop Version**:v0.0.11-beta.5

- **Editor**: Sublime

- **MavensMate Plugin Version**: v7.0.0

- **Platform/Version**: Mac 10.11

- **Salesforce API Version**: 34

- **Salesforce Server**: na45 (the client with okta SSO) na35 (the new project that I can't create)

I created a project for a client that uses Okta SSO (although I don't login with it).  Now every-time I try to create a new project I'm redirect to their okta login page (https://myclient.okta.com/) to login in the mavensmate login window.  I've tried using custom URL's & clearing cookies but nothing seems to work.   I imagine that reinstalling Mavensmate might do the trick but I'd prefer not to have to do that everytime I create a new project.

Really missing the Password + Token option

**Comment by ChuckJonas** [comment]
and... now I can't even login to the first project I created.  My refresh token expired (after 1 day 👎 ) and now when I go to re-authorize, it takes me to the okta page.  Since I'm not actually an SSO user, I can't login.  Rolling back to a pre-SSO.

**Comment by fracarma** [comment]
I think I have got the same problem. Every time I want to open a project, have to insert my credentials. But when I try to open a second project, I am redirect to the same Callback URL of the previous project, without asking me to enter the credentials

![errormmcredentials1](https://cloud.githubusercontent.com/assets/12348998/18704489/5ca2e776-7fea-11e6-926a-6d0c192f9845.PNG)

![errormmcredentials2](https://cloud.githubusercontent.com/assets/12348998/18704493/5fcf5790-7fea-11e6-993e-f28c639ec755.PNG)

**Comment by celador** [comment]
Bump.  Installed the latest version last night and cannot change the login for a new project.  It brings up the OAuth page and lets me login, but then when prompted for the name, it has the old login and the input is disabled.

**Comment by fracarma** [comment]
@celador Yeah, it's a bug. A workaround I follow is simply to click on the __not you?__ link, this permits you to change the username:

![accessmm](https://cloud.githubusercontent.com/assets/12348998/19143500/a6dd5004-8ba4-11e6-8c7e-900d5491ab3e.PNG)
