### ISSUE TITLE
UI: Toast prevents clicking on view manager

### ISSUE THREAD

**Issue by kylethornton** [joeferraro/MavensMate#753]
v0.0.11-beta.6

Sublime

OSX 10.11.6

37

Settings > Global Settings change a value and produce success message at top of screen. Try to open view manager and can't click icon until toast is dismissed (or goes away on it's own)

<img width="1136" alt="screen_shot_2016-09-21_at_9_11_00_am__2_" src="https://cloud.githubusercontent.com/assets/757939/18712231/7354fb8a-7fdb-11e6-8c2b-4cc86fb064dc.png">

**Comment by joeferraro** [comment]
Cheers for the report. This is intended functionality as it stands now. Success toasts, specifically, display temporarily, so a second or two more and you can be on your merry way. Errors are sticky and should be acknowledged before navigating. Will re-open if this changes.
