### ISSUE TITLE
Mavensmate Desktop for Mac - Fails to Open when installed in applications folder

### ISSUE THREAD

**Issue by bpasham** [joeferraro/MavensMate#754]
* **MavensMate Desktop Version**: v0.0.11-beta.5

* **Editor**: Atom 1.10.2

* **MavensMate Plugin Version**:1.0.9

* **Platform/Version**: Mac OS X 10.11.6

* **Proxy Details**: No Proxy

* **Salesforce API Version**: 37

* **Salesforce Server**: N/A

Open Mavenmate dmg file. Drag Mavensmate package on to Applications shortcut
Click on Launcher button ... find Mavenmate .. Click on Mavensmate

Error: Cannot Open

will be displayed

*Mavensmate application opens fine when when opened directly from within dmg or Installed anywhere else. I Installed to a local folder within my profile and it works fine.*

**Comment by joeferraro** [comment]
What is the value of your "Allow apps downloaded from" setting?

![security___privacy_and_mavensmate_desktop_for_mac_-_fails_to_open_when_installed_in_applications_folder_ _issue__754_ _joeferraro_mavensmate](https://cloud.githubusercontent.com/assets/54157/18750828/c3bc89a6-80aa-11e6-84ac-d8820623633d.png)

**Comment by joeferraro** [comment]
Also is it just the .dmg that's causing an issue? Do you experience the same result if you download and extract the .app from the .zip distro?

**Comment by bpasham** [comment]
1. Setting is Mac App Store and identified developers (btw - Anywhere option is removed in Sierra)
2. Same behaviour for both Zip and dmg distros - That's in El-Capitan only. 

However the good news is that the issue is resolved after upgrading to Sierra. Both packages are working fine on Sierra.

**Comment by joeferraro** [comment]
@srosen confirms that fixing disk permissions with either disk utility or a tool like Onyx resolves this issue
