### ISSUE TITLE
Project Name is disabled for "New Project from Existing"

### ISSUE THREAD

**Issue by bobteplitsky** [joeferraro/MavensMate#760]
When I try to create a MavensMate project from an existing directory, the Project Name field is disabled, making it impossible to create the project.  Am I missing something?

* **MavensMate Desktop Version**:  0.0.10

* **Editor**: Sublime Text 3

* **MavensMate Plugin Version**:  7.0.1

* **Platform/Version**:  OS X 10.11.6

* **Proxy Details**:  No

* **Salesforce API Version**:  36

* **Salesforce Server**: na35

**Repro Steps:**
- Start MavensMate desktop
- Start Sublime 3
- Create a new file
- Drag an existing folder into the left column of Sublime.  The folder must have a sub folder called "src" that contains Salesforce metadata tree
- Right mouse click on the top level folder in Sublime left column
- Choose MavensMate -> Create MavensMate Project...
- In MavensMate desktop the Project Name input field is disabled, making it impossible to create the project

<img width="724" alt="mm-from-existing" src="https://cloud.githubusercontent.com/assets/5531622/18769491/5ed54ffe-80e2-11e6-98a8-c9ed448ead0d.png">

<img width="995" alt="mm-project-disabled" src="https://cloud.githubusercontent.com/assets/5531622/18769493/639e11e2-80e2-11e6-95ec-d9abb077ae8f.png">

**Here is the contents of the Sublime Text console:**

[MAVENSMATE]: Calling mavensmate adapter
[MAVENSMATE]: OPERATION: new-project-from-existing-directory
[MAVENSMATE]: {'body': {'args': {'ui': True, 'origin': '/Users/bob/Development/fc/fc-mm-dev'}}}
[MAVENSMATE]: http://localhost:56248/execute?command=new-project-from-existing-directory&async=1
[MAVENSMATE]: posting to MavensMate:
[MAVENSMATE]: b'{"args": {"ui": true, "origin": "/Users/bob/Development/fc/fc-mm-dev"}}'
[MAVENSMATE]: response from MavensMate
[MAVENSMATE]: <http.client.HTTPResponse object at 0x10456a910>
[MAVENSMATE]: {'operation': 'new-project-from-existing-directory', 'id': '4e7146a0-811d-11e6-a705-dd47cc874914', 'result': {'message': 'Success'}, 'complete': True}
[MAVENSMATE] skipped community activity

**Comment by olegkord** [comment]
I hope they fix this quick...its literally not letting me work and commit updates to org states

**Comment by dzmitry-chernik-itechart** [comment]
I have the same issue with 7.0.1

**Comment by bobteplitsky** [comment]
Hoping to workaround this by trying out Atom for the first time.  Same issue there.  Was following these directions and when I get to the MM window "New Project from Existing" the Project Name is disabled :(  

https://simplysalesforce.com/2016/03/10/mavensmate-for-atom-how-to-link-a-new-project-to-an-existing-repository/

**Comment by bobteplitsky** [comment]
Good news!  If you want to workaround this issue with a different text editor and MavensMate, try Atom (https://atom.io/).  It's very simple to setup and runs with the same MM desktop app, and best of all the feature to create a project from an existing folder works.  Directions on how to do it (once you have installed Atom) are located here:  https://simplysalesforce.com/2016/03/10/mavensmate-for-atom-how-to-link-a-new-project-to-an-existing-repository/

**Comment by bobteplitsky** [comment]
Thanks @joeferraro !

**Comment by kennesk** [comment]
How can I get 7.0.2 installed in Sublime for Windows? Package Control keeps pulling 7.0.1. I have the exact problem as stated above.

**Comment by kennesk** [comment]
Thanks for the help! Works now.
