### ISSUE TITLE
Class code coverage is missing

### ISSUE THREAD

**Issue by dagish** [joeferraro/MavensMate#766]
* **MavensMate Desktop Version**: v0.0.10
* **Editor**: Sublime text build 3126.
* **MavensMate Plugin Version**: V. 7.0.1
* **Platform/Version**: Windows 10 64-bit
* **Proxy Details**: Unknown
* **Salesforce API Version**: 34.0
* **Salesforce Server**: cs87

Hi,

I'm trying to get code coverage per specific test class.
After running a test class from the mavensmate desktop application, moving to the class coverage is leading to a blank page.
I added 2 screenshots. One of the passed tests and the other of the class coverage tab.
![1](https://cloud.githubusercontent.com/assets/6702910/18814502/d0270692-831d-11e6-9112-47489f1636e7.PNG)
![2](https://cloud.githubusercontent.com/assets/6702910/18814503/d0276326-831d-11e6-8456-27d6e3bfc5ae.PNG)

Can you please check this issue?

Thanks.

**Comment by msenyk** [comment]
I have the same issue with **cs86** sandbox. Developer edition works fine.

**Comment by harshal-gajare** [comment]
Check if Store Only Aggregated Code Coverage is turned on in your org ?

![image](https://cloud.githubusercontent.com/assets/5017173/18956912/299e0b84-862b-11e6-8dd4-fb68527a2977.png)

**Comment by msenyk** [comment]
Yes, you were right. "Store Only Aggregated Code Coverage" checkbox was turned on.
Thanks a lot! I guess the issue has resolved.

**Comment by dagish** [comment]
@harshal-gajare Thanks for the solution!

**Comment by logiebearroar** [comment]
I have checked multiple times and my Store Only Aggregated Code Coverage is not checked, but still only pass/fail when running tests. No additional code coverage.

Has anyone else had this issue? I have tried just about everything I can think of.

Thanks 

Randy

**Comment by dagish** [comment]
Hi Randy,

I'm sorry but i don't have an idea why it is not working if the checkbox is unchecked.
I think it's better if you'll open a new thread on this issue because i'm not sure anyone will notice your issue on this closed thread.

Thanks,
Gad.

**Comment by logiebearroar** [comment]
Thanks for the help Gad! I have opened a new thread (fingers crossed).
