### ISSUE TITLE
Refresh From Server error when refreshing parent folder.    inFolderTypeDirectoryNames.indexOf

### ISSUE THREAD

**Issue by jacobraccuia** [joeferraro/MavensMate#769]
* **0.0.1.1 beta 4**:

* **Sublime*:

* **MM for Sublime 7.0.0**:

* **OSX  10.11.4**:

* **none**:

* ****:

* **na 34**:

Trying to refresh from server - clicking a folder.  I get the error below.

inFolderTypeDirectoryNames.indexOf

Somehow my sublime mavens mate plugin got updated and I couldn't figure out how to roll back so I had to get the MM desktop plugin and now I"m getting this issue.  It works fine if I try to refresh individual files

**Comment by jacobraccuia** [comment]
My mavens mate is not set up correctly..

**Comment by deckblad** [comment]
@jacobraccuia I'm seeing this same problem. What did you have to change?

**Comment by spredmore** [comment]
@jacobraccuia I also get this error. What did you do to fix it?

**Comment by dmchaplin** [comment]
Same Here.  What was the fix?
@jacobraccuia @deckblad @spredmore

**Comment by jacobraccuia** [comment]
@dmchaplin This was along time ago and I don't remember what I had set up wrong.  To everyone above, I had notifications blocked from github for some reason, so I'm sorry for not being able to help!

Make sure you have the latest MavensMate installed! I have no idea what I did though :(

**Comment by SuperPluck** [comment]
If this error is in the EmailTemplate folder, the error is because that contentType does not suport the wildcard '*' on the package.xml. Not sure about other contentTypes though...

**Comment by spredmore** [comment]
@dmchaplin I was never able to fix this. Sometimes when I right click on a folder and hit "Refresh from Server", it works. Other times it doesn't. When it doesn't, I go into Mavensmate Desktop and hit Edit Project, then Update Project.

**Comment by troveryor** [comment]
I'm definitely in the same situation. 

Oddly, it's only a problem in one of my folders though ( reports ).
Everything else in /src updates just fine (classes, components, objects, pages, reportTypes, staticresources, triggers).
