### ISSUE TITLE
Commands are not registered

### ISSUE THREAD

**Issue by fischgeek** [joeferraro/MavensMate#785]
* **MavensMate Desktop Version**: beta5

* **Editor**: VS Code

* **MavensMate Plugin Version**: Cloned from https://github.com/joeferraro/MavensMate-VisualStudioCode

* **Platform/Version**: Win10 x64

* **Proxy Details**: n/a

* **Salesforce API Version**: 34

* **Salesforce Server**: cs2 (sandbox)

Installed VS Code (C:\Program Files (x86)\Visual Studio Code\
Cloned the MM VS Code plugin repo.
Copied to %USERPROFILE%\.vscode\
Verified extension in VS Code
--At this point I tested the commands in the CLI (^+p) and there are registered MM commands, but they all throw errors saying that the command was not found.
Installed MM beta5
Updated VS Code path in MM from C:\Program Files\Code\Code.exe to C:\Program Files (x86)\Visual Studio Code\Code.exe
Created a new project in MM
Connected to sandbox
Opened project in VS Code
Tested the MavensMate plug in again. Same issues where the commands are not found.

P.S. Good luck at Dream Force this week!

**Comment by joeferraro** [comment]
closing as this was a prerelease

**Comment by joeferraro** [comment]
... and thanks for the good luck!

**Comment by fischgeek** [comment]
Great! Looking forward to the release!
