### ISSUE TITLE
MavensMate doesn't recognise VS Code Editor

### ISSUE THREAD

**Issue by qswh** [joeferraro/MavensMate#795]
* **MavensMate Desktop Version**: 0.0.11-beta 6

* **Editor**: code

* **MavensMate Plugin Version**:  0.4.0

* **Platform/Version**: Windows 8 64-bit

* **Proxy Details**: no

* **Salesforce API Version**: 36

* **Salesforce Server**: cs31

Followed all instructions and changed settings in both Mavensmate desktop and VS code for their paths. 

Not sure about this instruction so I didn't do anything. But in Mavensmate Desktop, there's no editor option for VS code. (Sublime text editor is shown with no issue)
Open the extension project in VS Code
Open a Terminal with ctrl+`
Run npm install
Develop!

Try to open the project folder within VS code anyway, but saving seems only impact local folder, not committing back to Salesforce. I guess it's because Mavensmate Desktop and VS code didn't connect each other? However, the paths in both app are definitely set to the correct values. Please help.

**Comment by kidtsunami** [comment]
@qswh is there a MavensMate status bar item in the bottom left hand corner of VS Code?

![mavensmate_status_bar](https://cloud.githubusercontent.com/assets/504253/19348989/b7e63d5a-911e-11e6-9c92-c3a076c84827.png)

**Comment by harshal-gajare** [comment]
@kidtsunami I am facing the same issue and I can see MavensMate in the status bar. I am on VS Code 1.6.0 

![image](https://cloud.githubusercontent.com/assets/5017173/19349074/270686b8-911f-11e6-83dc-533a27d1256f.png)

**Comment by kidtsunami** [comment]
Thanks! Can you try running the command "Convert To MavensMate Project"

**Comment by harshal-gajare** [comment]
@kidtsunami  You can ignore my issue. I had missed a step to "Shell Command : Install code in PATH" All looks great now.

**Comment by qswh** [comment]
Please ignore this. Somehow it shows up after I restart my work PC over the weekend.

**Comment by joeferraro** [comment]
cheers @qswh
