### ISSUE TITLE
Cannot find module './mavensmateExtension'.

### ISSUE THREAD

**Issue by NikiforovAll** [joeferraro/MavensMate#796]
* **MavensMate Desktop Version**: MavensMate-Desktop-0.0.11-beta.6

* **Editor**: vs code
 

* **MavensMate Plugin Version**: 0.4.0

* **Platform/Version**:
Ubuntu 14.04.5 LTS

  I toggled developer tools and found that mavensmate extension is not loaded correctly: 

> mainThreadExtensionService.ts:89Activating extension `DavidHelmer.mavensmate` failed: Cannot find module './mavensmateExtension'.

When I tried to run commands from command palette I've got error. 

>  command 'mavensmate.newApexClass' not found

**Comment by kidtsunami** [comment]
@NikiforovAll thanks for the feedback!

I've just published 0.4.2, can you download it and give a try?

**Comment by kidtsunami** [comment]
https://github.com/kidtsunami/MavensMate-VisualStudioCode/commit/35fe6371d7d94073eb76691c3c841e394f4a6ad8

**Comment by NikiforovAll** [comment]
It works. Thank you.
