### ISSUE TITLE
Test Runner UI not showing code coverage information

### ISSUE THREAD

**Issue by epohlabel** [joeferraro/MavensMate#801]
* **MavensMate Desktop Version**:

* **SublimeText**:

* **MavensMate for Sublime Text v7.0.2**:

* **64-bit Windows 8.1 Pro**:

* **NOPE**:

* **Salesforce API Version 36.0**:

* **Salesforce Server na35 - Developer Edition**:

Create a test class in SublimeText - 
Save class - 
select MavensMate->UnitTesting->Open Apex Test Runner UI from Sublim Text menu bar -
check the box beside the test class in MavensMate desktop UI and click Run Tests -
Test shows as passed - but there is no coverage information at all. Checked the Test Results tab and the Test Results, Class Coverage, and Trigger Coverage subtabs but they are all blank:

![image](https://cloud.githubusercontent.com/assets/22889260/19448331/6e0a9844-946f-11e6-98f2-93f6d09c1a86.png)

![image](https://cloud.githubusercontent.com/assets/22889260/19448350/8187c59a-946f-11e6-8ac7-fbe64f918b5c.png)

![image](https://cloud.githubusercontent.com/assets/22889260/19448370/939d28ba-946f-11e6-8c78-1a4dc449d7dd.png)

When I look at the trigger I was attempting to test in the SFDC UI - I can see there that it was 100% covered - but I expected to see some indication of coverage in MavensMate - I am VERY VERY NEW at this and am in the process of teaching myself to code.

**Comment by joeferraro** [comment]
dup of https://github.com/joeferraro/MavensMate/issues/782

**Comment by epohlabel** [comment]
Apologies! I tried searching without luck - I will look through this thread!
