### ISSUE TITLE
Ability to run Test Class without leaving VSCode

### ISSUE THREAD

**Issue by ChuckJonas** [joeferraro/MavensMate#827]
* **MavensMate Desktop Version**: Beta 6

* **Editor**: VSCODE

* **MavensMate Plugin Version**: 0.6.1

* **Platform/Version**: OS

On Sublime Text, there are two options to run tests:  `Run Test Async` which returns the results inside of the console, or `Open Test Runner`.  Currently VSCode only supports the latter.  Would be nice if you could run test with a single key binding and get results back in the console.

**Comment by ChuckJonas** [comment]
@kidtsunami I've pretty much implemented this, but wanted to get some feedback on the design.  

Do you think it would be better to add a separate command for this (something like `run test async` or just have a configuration point that changes the behavior of the current command `runTestsInConsole: true`.

**Comment by kidtsunami** [comment]
@ChuckJonas definitely as a separate command, I've had uses for either command without wanting to pop back to settings to change.

**Comment by ChuckJonas** [comment]
Agreed.  I'll submit a PR in the next day or 2.

**Comment by ChuckJonas** [comment]
joeferraro/MavensMate-VisualStudioCode#9
