### ISSUE TITLE
command 'mavensmate.toggleOutput' not found

### ISSUE THREAD

**Issue by joeferraro** [joeferraro/MavensMate#838]
* **Editor**: VS Code

* **MavensMate Plugin Version**: 0.6.1

"command 'mavensmate.toggleOutput' not found" when clicking "MavensMate" in the VS Code bar.

![untitled-1](https://cloud.githubusercontent.com/assets/54157/20182538/17f0cd92-a730-11e6-9606-2cd9da830148.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/196929402075618/210844669725219)

**Comment by robcowell** [comment]
I get this for all MM commands under VS Code, including Open Project/New Project... macOS version of VS Code (1.8.1), plugin version 0.6.2

**Comment by kidtsunami** [comment]
@ChuckJonas mind confirming and closing?
