### ISSUE TITLE
OAuth Refresh token missing causing constant relogin 

### ISSUE THREAD

**Issue by OlegForce** [joeferraro/MavensMate#841]
I was wondering if there is a reason for ConnectedApp that is being used not including refresh token? My token expires all the time and I have to reauthenticate... Hope this is not a duplicate issue. 

Thanks.

* **MavensMate Desktop Version**: 11 beta 6

* **Editor**: Sublime  3

* **MavensMate Plugin Version**: 7

* **Platform/Version**:Mac OS X Sierra

* **Proxy Details**: N/A

* **Salesforce API Version**: 37/38

* **Salesforce Server**: login/test

**Comment by ChuckJonas** [comment]
@OlegForce this is a know issue that should have been fixed in [v0.0.11-beta.7](https://github.com/joeferraro/MavensMate-Desktop/releases/tag/v0.0.11-beta.7).  If you still experience this issue after upgrade, please let us know.

**Comment by OlegForce** [comment]
Thank you. I will give it a try.
