### ISSUE TITLE
On Mac MavensMate keeps compiling and never stops

### ISSUE THREAD

**Issue by ritsnuno** [joeferraro/MavensMate#842]
* **MavensMate Desktop Version**: 1.0.9

* **Editor**: Atom 1.12.2

* **MavensMate Plugin Version**: Mavensmate-Atom 1.0.9

* **Platform/Version**: OS X 10.11.6

* **Proxy Details**:

* **Salesforce API Version**: 38.0

* **Salesforce Server**: na24

At start, the MavensMate App could not connect to the Atom app, so I changed the atom executable path to: "osx": "/Applications/Atom.app/Contents/Resources/app/atom.sh" and it did work from there, now the Atom app opens correctly.

The issue I'm experiencing: When saving a visualforce page or a class, although it saves to the org, it just keeps compiling and shows no error or other kind of message, and never stops.

Thanks!

**Comment by banderson5144** [comment]
Same issue here

**Comment by Szandor72** [comment]
+1 apparently, lost hours due to this :(

**Comment by joeferraro** [comment]
dup https://github.com/joeferraro/MavensMate/issues/846
