### ISSUE TITLE
Cannot Create Project, Freezing After Allowing Access

### ISSUE THREAD

**Issue by johnsolok** [joeferraro/MavensMate#864]
* v0.0.11-beta.7

* Sublime Text 3:

* Most Recent:

* Windows 7 Enterprise:

Configured to run through a local proxy on port 8080:

* 36.0:

* cs63:

This is a new installation. When I go to create my initial project:

1. Click NEW PROJECT
2. Select "Sandbox" for Salesforce Environment Type, click Connect
3. Enter sandbox credentials and click "Log In to Sandbox"
4. On "Allow Access?" page, click "Allow"
5. The page goes to "Redirecting..." with the graphic and eventually times out

In the Developer Tools the last action is in a (cancelled) status. 

![capture](https://cloud.githubusercontent.com/assets/24318571/20838671/2ed9af74-b86f-11e6-93ca-a0001f48f946.PNG)
 
I appreciate any help that can be provided, I'm almost 100% sure it is a network connectivity issue. It is frustrating me quite a bit.

Thanks,

John

**Comment by krishnaprasadsn** [comment]
I am running into same issue. Is it something to do with network or issue with new version of Mavensmate?

**Comment by ChuckJonas** [comment]
not sure if this would have any impact, but maybe try a different port?  Any reason why you aren't using the default `56248`?

**Comment by johnsolok** [comment]
I was able to resolve the issue by connecting outside of the proxy that my company is using. 

Unfortunately, I don't have much in the way of insight into what was preventing the connection. But, I encountered the same issue with the Data Loader.

I am closing this because I am no longer having the issue.

**Comment by pradeep-dani** [comment]
![image](https://cloud.githubusercontent.com/assets/15077583/25290257/e615d4f8-26ea-11e7-9521-17adad112cac.png)

I facing this issue to setup mavensmate for the first time.
