### ISSUE TITLE
Installing "MavensMat-Atom@1.0.10" failed.

### ISSUE THREAD

**Issue by js-restaurantlink** [joeferraro/MavensMate#890]
* v0.0.11-beta.7:

* atom:

* 1.0.10:

* OS X 10.12.2 .:

*No:

* No Salesforce project built yet :

* Not connecting to SF yet:

atom-settings view-isntall packages
search for MavensMate
click install

error messages...
Installing “MavensMate-Atom@1.0.10” failed.Hide output…

npm WARN deprecated node-uuid@1.4.1: use uuid module instead
npm WARN addRemoteGit git+https://github.com/Benvie/harmony-collections.git#e81b4b808359e2def9eeeabfdee69c2989e1fe96 resetting remote /Users/JeffStevens/.atom/.apm/_git-remotes/git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9 because of error: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! git clone --template=/Users/JeffStevens/.atom/.apm/_git-remotes/_templates --mirror https://github.com/Benvie/harmony-collections.git /Users/JeffStevens/.atom/.apm/_git-remotes/git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! Darwin 16.3.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/JeffStevens/.atom/.apm/.apmrc" "--userconfig" "/Users/JeffStevens/.atom/.apmrc" "install" "/private/var/folders/19/qjb3k7ks1kzfnsqgk57ghl4h0000gp/T/d-117017-1061-130j90j/package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=x64" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code 1

npm ERR! Command failed: git clone --template=/Users/JeffStevens/.atom/.apm/_git-remotes/_templates --mirror https://github.com/Benvie/harmony-collections.git /Users/JeffStevens/.atom/.apm/_git-remotes/git-https-github-com-Benvie-harmony-collections-git-e81b4b808359e2def9eeeabfdee69c2989e1fe96-f622d8c9
npm ERR! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/19/qjb3k7ks1kzfnsqgk57ghl4h0000gp/T/apm-install-dir-117017-1061-l0h89n/npm-debug.log

**Comment by steals** [comment]
clone  Mavensmate-Atom repo https://github.com/joeferraro/MavensMate-Atom.git) into your atom packages directory (~/.atom/packages) and update version of "emissary" dependency from 1.2.2 to 1.3.3 in packages.json. After that run npm install inside MavensMate-Atom directory

**Comment by karlkras** [comment]
Thanks @steals, maybe the repo should be updated with this fix? Or is this code abandoned?

**Comment by CodeMonkeyG** [comment]
@steals: Your solution worked for me. Thanks.

**Comment by kidtsunami** [comment]
@steals mind making a Pull Request? If not I'll dust off Atom and see if we can push a fix.

**Comment by dyehya** [comment]
Thanks @steals 
For anyone that isn't that technical trying to get it work:
Make sure Atom is closed before beginning.
1. Download the zip https://github.com/joeferraro/MavensMate-Atom of the source code [https://github.com/joeferraro/MavensMate-Atom/archive/master.zip](url)
2. Extract to your packages directory  (~/.atom/packages) or (C:\Users\\**Username**\\.atom\packages)
2b. Rename ~/.atom/packages/MavensMate-Atom-master to ~/.atom/packages/MavensMate-Atom or C:\Users\\**Username**\\.atom\packages\MavensMate-Atom-master to C:\Users\\**Username**\\.atom\packages\MavensMate-Atom
3. Install Node.JS if you haven't already [https://nodejs.org/](url)
4. From command-line navigate to the folder WITHIN the packages folder that you extracted. (~/.atom/packages/MavensMate-Atom) or (C:\Users\\**Username**\\.atom\packages\MavensMate-Atom)
5. From command line run: **npm install**
Note: Do **not** do npm install MavensMate-Atom as this will not work.
6. Start Atom error free :)

**Comment by steals** [comment]
@kidtsunami Sure, will do

**Comment by kidtsunami** [comment]
don't worry @steals already got one going https://github.com/joeferraro/MavensMate-Atom/commit/65ea2a23d2e362323bb8e1777773312fc18ffaf5

**Comment by kidtsunami** [comment]
Hi everyone, I hopefully resolved this issue with the following PR:
https://github.com/joeferraro/MavensMate-Atom/pull/348

This is MavensMate-Atom v1.1.0

I'll be closing this tomorrow unless someone raises an issue.

**Comment by kidtsunami** [comment]
Ok, no updates? Closing.
