### ISSUE TITLE
Login through frontdoor.jsp using connected app token results in chatter post via connected app

### ISSUE THREAD

**Issue by jonathanwiesel** [joeferraro/MavensMate#899]
Are you facing a similar issues on the new versions of MavensMate with Connected App OAuth:

https://developer.salesforce.com/forums/ForumsMain?id=9060G000000I2mpQAC

* **MavensMate Desktop Version**:
v0.0.10

* **Editor**:
Sublime Text

* **MavensMate Plugin Version**:
v7.0.2

* **Platform/Version**:
macOS 10.12.2

* **Salesforce API Version**:
37.0

**Comment by jonathanwiesel** [comment]
Just confirmed in the latest beta on MavensMate desktop this is actually happening

![screen shot 2017-02-13 at 11 07 05](https://cloud.githubusercontent.com/assets/1326781/22879086/a07dd0c8-f1dc-11e6-9b1f-332dd70acd82.png)

**Comment by kidtsunami** [comment]
@jonathanwiesel I'm not sure what the issue is here, you've authenticated through an App, and then performed some actions. The "from" part of those messages is useful for knowing how the person accessed salesforce.

This is definitely Salesforce behavior and has little do with MavensMate.

**Comment by jonathanwiesel** [comment]
@kidtsunami I understand it's what Salesforce intended. Is there a workaround for this? I don't believe many users that use this login shortcut would want that footer on their Chatter messages.
