### ISSUE TITLE
Self signed certificate in certificate chain

### ISSUE THREAD

**Issue by rsmithdev6** [joeferraro/MavensMate#912]
* **MavensMate Desktop Version**: 

 v0.0.11-beta.6

* **Editor**:

Sublime text 3

* **MavensMate Plugin Version**:

* **Platform/Version**: Windows 10 64-bit

* **Proxy Details**:

* **Salesforce API Version**: 36.0

* **Salesforce Server**:  cs6

<!-- Please enter specific steps to reproduce your issue below this comment. →

Click edit project
Choose workspace
Update metadata

Error:  Self signed certificate in certificate chain

**Comment by murcix** [comment]
Probably you have a Firewall or a special software that enforce the protection of your data. I have experience this issue with Triton AP-Endpoint enable

**Comment by rsmithdev6** [comment]
It appears the issue was caused by the Salesforce environment I was developing. It had a self signed certificate that had expired. To fix it I changed the setting of the API Client Certificate  to No Certificate

**Comment by adrianrecio** [comment]
@rsmithdev6 workaround works for my org.
