### ISSUE TITLE
VS Code Run All Tests in Current File

### ISSUE THREAD

**Issue by ralphcallaway** [joeferraro/MavensMate#916]
* **MavensMate Desktop Version**: v0.0.11-beta.7

* **Editor**: Code

* **MavensMate Plugin Version**: 0.6.4

* **Platform/Version**: OS X 10.10.5

* **Proxy Details**: no

* **Salesforce API Version**: n/a

* **Salesforce Server**: n/a

When using Sublime Text I can quickly run all the tests for a particular test class by opening the file and running the "Run All Apex Unit Tests For This Class". Super awesome if you like to avoid switching to ui driven interactions that require moving my hand to the mouse.

Would love to see this added into the VS Code extension.

**Comment by ChuckJonas** [comment]
This already exists: `Run Tests in Editor (async)`.  For better usability, i suggest giving it a keyboard shortcut (I use `cmd-t`)

**Comment by ralphcallaway** [comment]
sweet! there it is
