### ISSUE TITLE
Saving Resources in VSCode deletes local source

### ISSUE THREAD

**Issue by bruceharrison1984** [joeferraro/MavensMate#925]
* **MavensMate Desktop Version**: v0.0.11-beta.7

* **Editor**: VSCode

* **MavensMate Plugin Version**: v0.6.4

* **Platform/Version**: Windows 10 64-bit

* **Salesforce API Version**: 36

When trying to save a Salesforce resource, the entire contents of the local file is blanked. In my case, this was a javascript file for a Visualforce page. This also renders the local resource-meta.xml blank.

The file must be re-retrieved from Salesforce in order to restore the local copy, but saving seems to always result in the same issue, with the local copy becoming blanked. The server copy is never altered, so this is a recoverable error.

Once the error occurs, the "Problems" panel located in VSCode will report an error due to a missing object in a package.xml. In my case, it looks like this:
```
An object 'ACFP_Client_SignIn' of type StaticResource was named in package.xml, but was not found in zipped directory (1,1)
```

This issue does not seem to affect 'normal' Salesforce files such as classes and triggers. SublimeText 3 does not seem to be affected by this error, as I can happily work on javascript resources without issue.

After posting, I realize this issue seems to be the same as:
#902

**Comment by kidtsunami** [comment]
@bruceharrison1984 are you able to reproduce this in a developer org that you can share with us?

**Comment by bruceharrison1984** [comment]
@kidtsunami, i can set one up tomorrow

**Comment by bruceharrison1984** [comment]
@kidtsunami I provisioned a developer org and it indeed suffers from the same problem.

I'm going to add you as a user in the org based on your github email, so you should receive an activation email from Salesforce in the near future. Your account is System Admin.

The org is completely bare except for a single javascript file in the static resources.

**Comment by bruceharrison1984** [comment]
I was using this feature incorrectly, and trying to upload files from the static resources within the SRC folder instead of using the resource-bundles feature of mavensmate. Closing this issue

**Comment by clebertxr** [comment]
@bruceharrison1984  After encountering your comment I think I'm using it the wrong way too.

What is the right way to do this?
