### ISSUE TITLE
Mavensmate giving error "Error initializing project: self signed certificate in certificate chain"

### ISSUE THREAD

**Issue by Akshay-Mohan-007** [joeferraro/MavensMate#930]
Hi Team,

Since yesterday I am getting the error in Mavensmate whenever i try to open my pre-configured project
"Error initializing project: self signed certificate in certificate chain". My project was working perfectly fine till 14-Feb-2017.

* **MavensMate Desktop Version**:  v0.0.10

* **Editor**: Sublime

* **MavensMate Plugin Version**: app-v0.0.10

* **Platform/Version**: windows 10 64 bit

* **Proxy Details**: No

* **Salesforce API Version**:  39

* **Salesforce Server**: cs60

Issue comes on 
1) Trying to refresh project
2) Trying to create new project
3) Trying to open existing project

Would appreciate a quick response :)
Thanks
Akshay

**Comment by Akshay-Mohan-007** [comment]
Guys any updates on the issue?

**Comment by hraichandani** [comment]
I'm also getting same error in MavensMate since morning. Not able to refresh/save any file in Sublime.

**Comment by hraichandani** [comment]
Hey Akshay,

While googling, I found one post, following which above mentioned problem was solved - http://mauricekremer.dscloud.me/untitled/

**Comment by Akshay-Mohan-007** [comment]
Thanks a lot @hraichandani ! Worked perfectly!!

**Comment by pradeep-dani** [comment]
@hraichandani @Akshay-Mohan-007 

I am facing same issue & above link is broken, please share another link or the solution details.

Thanks

**Comment by aritrikdas** [comment]
The above link is not working, can anyone please provide solution for the same?

**Comment by kamalrao49** [comment]
I am not able to access http://mauricekremer.dscloud.me/untitled/ link 
can you pls past in comments what steps have to do .

**Comment by alvarsdu** [comment]
Please @hraichandani @Akshay-Mohan-007 
Can you help me to solve the same mistake?

**Comment by vnissankula** [comment]
1 - Open the windows explorer
2 - Right click "this pc" and choose "properties"
3 - Click "Advance system settings"
4 - Click "environment variables"
5 - Click "new" on the "user variables"
6 - Create variable NODE_TLS_REJECT_UNAUTHORIZED with value 0
7 - Click "OK" and reboot the machine.

Please try this. It worked for me.

**Comment by alvarsdu** [comment]
@vnissankula I did and it not working for me, now Mavensmate quits unexpectedly and does not complete the project creation.

**Comment by kamalrao49** [comment]
@vnissankula  Thank you ....
It is work for me .

**Comment by pradeep-dani** [comment]
@vnissankula Thanks, It is works .
