### ISSUE TITLE
debug logs are being stored on local desktop.. eating memory like GBs everyday. need to stop from downloading logs

### ISSUE THREAD

**Issue by praveenmakam2012** [joeferraro/MavensMate#931]
* **MavensMate Desktop Version**: v0.0.11-beta.7

* **Editor**: sublime

* **MavensMate Plugin Version**: v7.0.2

* **Platform/Version**: windows 7 - 32bit

* **Proxy Details**: no

* **Salesforce API Version**: 36

* **Salesforce Server**: Na4

I have configured the projects and been using mavensmate for quite sometime. but, recently I started seeing that debug logs are getting stored on to my local system which is actually consuming a lot of memory and internet. I would like to know if there is a setting which would stop these logs from downloading. Thanks.

**Comment by harshal-gajare** [comment]
@praveenmakam2012 You can run the stop logging command and flush debug logs to clean this up.

**Comment by praveenmakam2012** [comment]
harshal,

It would be helpful if you could provide the command to flush the logs.
And, if there is a configuration set up where I can say I dont want logs to
be stored on my system.

**Comment by pbattisson** [comment]
@praveenmakam2012 If you look in the MavensMate menu in Sublime Text the options are there.

<img width="508" alt="screen shot 2017-02-20 at 17 02 32" src="https://cloud.githubusercontent.com/assets/795556/23134917/7c4daacc-f78e-11e6-88bd-3bc493b905ca.png">

**Comment by arturjsfCGI** [comment]
Im trying to get logs in my /log folder but with no sucess.

My project is in C:\Work\MyProject
 "mm_log_location": "C:\Work\MyProject\logs"
I use Windows 7, VS Code and MavensMate

When I run some Apex Code from MavensMate.....
![waesdf](https://user-images.githubusercontent.com/35462687/35528506-f2b2ec90-0525-11e8-880e-b127710f29ba.JPG)

It only apears in my SF Console
![123123](https://user-images.githubusercontent.com/35462687/35528582-37fecb02-0526-11e8-9b8a-82527ec17ff0.JPG)

And I want something like this.
https://salesforce.stackexchange.com/questions/36964/how-can-i-get-debug-log-in-mavensmate
