### ISSUE TITLE
Unable to comment out Visualforce page in vscode

### ISSUE THREAD

**Issue by Jasonlhy** [joeferraro/MavensMate#939]
* **MavensMate Desktop Version**: v0.0.11-beta7

* **Editor**: vscode, version 1.1

* **MavensMate Plugin Version**: 0.6.4

* **Platform/Version**: Windows 7

* **Proxy Details**: N/A

* **Salesforce API Version**: 39

* **Salesforce Server**: ap2

# For Line comment
1. Put the cursor on a line containing `<apex>` tag
2. Press `ctrl+/` or open command palette to run `Toggle Run Comment`
3. Nothing happened

# For Block comment
1. Select a few lines containing `<apex>` tag
2. Press `shift+alt+a` or open command palette to run `Toggle Block Comment`
3. Nothing happened

I just upgraded to vscode version 1.1 today, but the problem also happened in version 1.9

**Comment by ChuckJonas** [comment]
I've noticed this as well.  I think we just need to add a language configuration file [here](https://github.com/kidtsunami/MavensMate-VisualStudioCode/tree/master/languages).

**Comment by kidtsunami** [comment]
I think you're right @ChuckJonas I'll have a look tomorrow

**Comment by kidtsunami** [comment]
Thanks @ChuckJonas for handling this, I checked it out and published v0.7.0 with it!

**Comment by Jasonlhy** [comment]
@ChuckJonas @kidtsunami thanks for the quick help :+1:
