### ISSUE TITLE
Development Login doesn't work

### ISSUE THREAD

**Issue by JPWallhorn** [joeferraro/MavensMate#941]
* **MavensMate Desktop Version**: v0.0.11-beta.7

* **Editor**: Sublime Text 

* **MavensMate Plugin Version**: v7.0.2

* **Platform/Version**: OS X 10.12.3

* **Proxy Details**: N/A

* **Salesforce API Version**: v39

* **Salesforce Server**: CS71

When I create a new project and choose "Development" I can't login. I use my username in add '.dev' in the end (same as the salesforce sandbox login) but it keeps spinning. The login doesn't work. I tested the same credentials in my web browser and it's not a problem. 

When I choose 'Development' and just login with my normal username and password, I actually login into the production environment. I can tell by not being able to create an APEX controller. 

Error message: Can't create APEX Class in active organization.

**Comment by ChuckJonas** [comment]
Are you trying to login to a sandbox org?  If so, use the `Sandbox` org type from the login dropdown

**Comment by JPWallhorn** [comment]
No, I haven't. I tried only Developer. I will try Sandbox and report back here.

**Comment by JPWallhorn** [comment]
Thank you, that worked.
