### ISSUE TITLE
Mavensmate does not accept the wildcard token "*" in package.xml

### ISSUE THREAD

**Issue by tuskiomi** [joeferraro/MavensMate#966]
* **Most recent**:

* **Sublime**:

* **Most recent**:

* **Win 10 64 bit**:

* **N/A**:

* **39**:

* **Na35**:

Editing the package.xml such that the members token of the customObject namespace contains a single member '*' doesn't change the behavior of Mavens mate, not does it download custom object; it rewrites the package.xml file and reverts it to the previous state.

**Comment by kidtsunami** [comment]
Unfortunately, not every metadata type supports the wildcard option when selecting metdata.

See chapter 10 in the [Metadata API Developer Guide](https://resources.docs.salesforce.com/sfdc/pdf/api_meta.pdf)
