### ISSUE TITLE
MavensMate, multiple sandboxes and git version control

### ISSUE THREAD

**Issue by aireater** [joeferraro/MavensMate#973]
* **MavensMate Desktop Version**:  v0.0.11-beta7

* **Editor**: Atom

* **MavensMate Plugin Version**: 1.0.10

* **Platform/Version**:  OS X 10.11.6

* **Salesforce API Version**: 36

* **Salesforce Server**: cs66

How do you manage multiple sandboxes with git source control? 

For example, I have a developer sandbox where I code my changes then promote them to a full sandbox where other developers work as well. 

In git, I decided to map each sandbox (dev and full) to their own branches. 

In mavensmate am I expected to keep separate directories for each sandbox?

**Comment by ChuckJonas** [comment]
This is a major grievance with mm.  We have the same setup and the best way is just to edit the project username and pass then clean when you want to switch orgs.  mm does have a feature called deployment connection, which I've been wanting to implement a way to do a fast swap between them.

**Comment by aireater** [comment]
@ChuckJonas Thanks, I tried that - it didn't work. I'll live with the two directories for now.
