### ISSUE TITLE
Unable to push changes to token lightning components

### ISSUE THREAD

**Issue by isalew** [joeferraro/MavensMate#992]
* **MavensMate Desktop Version**: v0.0.11-beta.7

* **Editor**: atom

* **MavensMate Plugin Version**: 1.0.10

* **Platform/Version**: OS X 10.12.5

* **Proxy Details**: N/A

* **Salesforce API Version**: 39.0 & 40.0

* **Salesforce Server**: cs13

Steps to Reproduce:
- Create a lightning component bundle called `defaultTokens` as per [doc instructions](https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/tokens_create_bundle.htm)
- Make changes in local IDE to `defaultTokens.tokens` file and push via mavensmate. As per [this documentation](https://developer.salesforce.com/docs/atlas.en-us.lightning.meta/lightning/tokens_bundles.htm), the component should be updatable via the Metadata API.

**Comment by pbattisson** [comment]
Hi @isalew - design tokens were only developer preview in Spring 17 and as far as I know are still only in a preview state (though let me know if I am incorrect). As they are therefore pre-beta they are not currently supported - sorry. Hopefully they will be GA'ed and fully supported following that.
